# Viewing and Cleaning

### Importing Libraries

In [24]:
import pandas as pd
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', 100)
import _pickle as pickle

### Loading the Data

In [25]:
test  = pd.read_csv("test.csv")

weather = pd.read_csv("weather.csv")

### Viewing the DFs

In [26]:
test

,Id,Date,Address,Species,Block,Street,Trap,AddressNumberAndStreet,Latitude,Longitude,AddressAccuracy
0,1,2008-06-11,"4100 North Oak Park Avenue, Chicago, IL 60634,...",CULEX PIPIENS/RESTUANS,41,N OAK PARK AVE,T002,"4100 N OAK PARK AVE, Chicago, IL",41.954690,-87.800991,9
1,2,2008-06-11,"4100 North Oak Park Avenue, Chicago, IL 60634,...",CULEX RESTUANS,41,N OAK PARK AVE,T002,"4100 N OAK PARK AVE, Chicago, IL",41.954690,-87.800991,9
2,3,2008-06-11,"4100 North Oak Park Avenue, Chicago, IL 60634,...",CULEX PIPIENS,41,N OAK PARK AVE,T002,"4100 N OAK PARK AVE, Chicago, IL",41.954690,-87.800991,9
3,4,2008-06-11,"4100 North Oak Park Avenue, Chicago, IL 60634,...",CULEX SALINARIUS,41,N OAK PARK AVE,T002,"4100 N OAK PARK AVE, Chicago, IL",41.954690,-87.800991,9
4,5,2008-06-11,"4100 North Oak Park Avenue, Chicago, IL 60634,...",CULEX TERRITANS,41,N OAK PARK AVE,T002,"4100 N OAK PARK AVE, Chicago, IL",41.954690,-87.800991,9
5,6,2008-06-11,"4100 North Oak Park Avenue, Chicago, IL 60634,...",CULEX TARSALIS,41,N OAK PARK AVE,T002,"4100 N OAK PARK AVE, Chicago, IL",41.954690,-87.800991,9
6,7,2008-06-11,"4100 North Oak Park Avenue, Chicago, IL 60634,...",UNSPECIFIED CULEX,41,N OAK PARK AVE,T002,"4100 N OAK PARK AVE, Chicago, IL",41.954690,-87.800991,9
7,8,2008-06-11,"4100 North Oak Park Avenue, Chicago, IL 60634,...",CULEX ERRATICUS,41,N OAK PARK AVE,T002,"4100 N OAK PARK AVE, Chicago, IL",41.954690,-87.800991,9
8,9,2008-06-11,"6200 North Mandell Avenue, Chicago, IL 60646, USA",CULEX PIPIENS/RESTUANS,62,N MANDELL AVE,T007,"6200 N MANDELL AVE, Chicago, IL",41.994991,-87.769279,9
9,10,2008-06-11,"6200 North Mandell Avenue, Chicago, IL 60646, USA",CULEX RESTUANS,62,N MANDELL AVE,T007,"6200 N MANDELL AVE, Chicago, IL",41.994991,-87.769279,9
10,11,2008-06-11,"6200 North Mandell Avenue, Chicago, IL 60646, USA",CULEX PIPIENS,62,N MANDELL AVE,T007,"6200 N MANDELL AVE, Chicago, IL",41.994991,-87.769279,9
11,12,2008-06-11,"6200 North Mandell Avenue, Chicago, IL 60646, USA",CULEX SALINARIUS,62,N MANDELL AVE,T007,"6200 N MANDELL AVE, Chicago, IL",41.994991,-87.769279,9
12,13,2008-06-11,"6200 North Mandell Avenue, Chicago, IL 60646, USA",CULEX TERRITANS,62,N MANDELL AVE,T007,"6200 N MANDELL AVE, Chicago, IL",41.994991,-87.769279,9
13,14,2008-06-11,"6200 North Mandell Avenue, Chicago, IL 60646, USA",CULEX TARSALIS,62,N MANDELL AVE,T007,"6200 N MANDELL AVE, Chicago, IL",41.994991,-87.769279,9
14,15,2008-06-11,"6200 North Mandell Avenue, Chicago, IL 60646, USA",UNSPECIFIED CULEX,62,N MANDELL AVE,T007,"6200 N MANDELL AVE, Chicago, IL",41.994991,-87.769279,9
15,16,2008-06-11,"6200 North Mandell Avenue, Chicago, IL 60646, USA",CULEX ERRATICUS,62,N MANDELL AVE,T007,"6200 N MANDELL AVE, Chicago, IL",41.994991,-87.769279,9
16,17,2008-06-11,"7900 West Foster Avenue, Chicago, IL 60656, USA",CULEX PIPIENS/RESTUANS,79,W FOSTER AVE,T015,"7900 W FOSTER AVE, Chicago, IL",41.974089,-87.824812,8
17,18,2008-06-11,"7900 West Foster Avenue, Chicago, IL 60656, USA",CULEX RESTUANS,79,W FOSTER AVE,T015,"7900 W FOSTER AVE, Chicago, IL",41.974089,-87.824812,8
18,19,2008-06-11,"7900 West Foster Avenue, Chicago, IL 60656, USA",CULEX PIPIENS,79,W FOSTER AVE,T015,"7900 W FOSTER AVE, Chicago, IL",41.974089,-87.824812,8
19,20,2008-06-11,"7900 West Foster Avenue, Chicago, IL 60656, USA",CULEX SALINARIUS,79,W FOSTER AVE,T015,"7900 W FOSTER AVE, Chicago, IL",41.974089,-87.824812,8
20,21,2008-06-11,"7900 West Foster Avenue, Chicago, IL 60656, USA",CULEX TERRITANS,79,W FOSTER AVE,T015,"7900 W FOSTER AVE, Chicago, IL",41.974089,-87.824812,8
21,22,2008-06-11,"7900 West Foster Avenue, Chicago, IL 60656, USA",CULEX TARSALIS,79,W FOSTER AVE,T015,"7900 W FOSTER AVE, Chicago, IL",41.974089,-87.824812,8
22,23,2008-06-11,"7900 West Foster Avenue, Chicago, IL 60656, USA",UNSPECIFIED CULEX,79,W FOSTER AVE,T015,"7900 W FOSTER AVE, Chicago, IL",41.974089,-87.824812,8
23,24,2008-06-11,"7900 West Foster Avenue, Chicago, IL 60656, USA",CULEX ERRATICUS,79,W FOSTER AVE,T015,"7900 W FOSTER AVE, Chicago, IL",41.974089,-87.824812,8
24,25,2008-06-11,"1500 West Webster Avenue, Chicago, IL 60614, USA",CULEX PIPIENS/RESTUANS,15,W WEBSTER AVE,T045,"1500 W WEBSTER AVE, Chicago, IL",41.921600,-87.666455,8
25,26,2008-06-11,"1500 West Webster Avenue, Chicago, IL 60614, USA",CULEX RESTUANS,15,W WEBSTER AVE,T045,"1500 W WEBSTER AVE, Chicago, IL",41.921600,-87.666455,8
26,27,2008-06-11,"1500 West Webster Avenue, Chicago, IL 60614, USA",CULEX PIPIENS,15,W WEBSTER AVE,T045,"1500 W WEBSTER AVE, Chicago, IL",41.921600,-87.666455,8
27,28,2008-06-11,"1500 West Webster Avenue, Chicago, IL 60614, USA",CULEX SALINARIUS,15,W WEBSTER AVE,T045,"1500 W WEBSTER AVE, Chicago, IL",41.921600,-87.666455,8
28,29,2008-06-11,"1500 West Webster Avenue, Chicago, IL 60614, USA",CULEX TERRITANS,15,W WEBSTER AVE,T045,"1500 W WEBSTER AVE, Chicago, IL",41.921600,-87.666455,8
29,30,2008-06-11,"1500 West Webster Avenue, Chicago, IL 60614, USA",CULEX TARSALIS,15,W WEBSTER AVE,T045,"1500 W WEBSTER AVE, Chicago, IL",41.921600,-87.666455,8
30,31,2008-06-11,"1500 West Webster Avenue, Chicago, IL 60614, USA",UNSPECIFIED CULEX,15,W WEBSTER AVE,T045,"1500 W WEBSTER AVE, Chicago, IL",41.921600,-87.666455,8
31,32,2008-06-11,"1500 West Webster Avenue, Chicago, IL 60614, USA",CULEX ERRATICUS,15,W WEBSTER AVE,T045,"1500 W WEBSTER AVE, Chicago, IL",41.921600,-87.666455,8
32,33,2008-06-11,"2500 West Grand Avenue, Chicago, IL 60654, USA",CULEX PIPIENS/RESTUANS,25,W GRAND AVE,T046,"2500 W GRAND AVE, Chicago, IL",41.891118,-87.654491,8
33,34,2008-06-11,"2500 West Grand Avenue, Chicago, IL 60654, USA",CULEX RESTUANS,25,W GRAND AVE,T046,"2500 W GRAND AVE, Chicago, IL",41.891118,-87.654491,8
34,35,2008-06-11,"2500 West Grand Avenue, Chicago, IL 60654, USA",CULEX PIPIENS,25,W GRAND AVE,T046,"2500 W GRAND AVE, Chicago, IL",41.891118,-87.654491,8
35,36,2008-06-11,"2500 West Grand Avenue, Chicago, IL 60654, USA",CULEX SALINARIUS,25,W GRAND AVE,T046,"2500 W GRAND AVE, Chicago, IL",41.891118,-87.654491,8
36,37,2008-06-11,"2500 West Grand Avenue, Chicago, IL 60654, USA",CULEX TERRITANS,25,W GRAND AVE,T046,"2500 W GRAND AVE, Chicago, IL",41.891118,-87.654491,8
37,38,2008-06-11,"2500 West Grand Avenue, Chicago, IL 60654, USA",CULEX TARSALIS,25,W GRAND AVE,T046,"2500 W GRAND AVE, Chicago, IL",41.891118,-87.654491,8
38,39,2008-06-11,"2500 West Grand Avenue, Chicago, IL 60654, USA",UNSPECIFIED CULEX,25,W GRAND AVE,T046,"2500 W GRAND AVE, Chicago, IL",41.891118,-87.654491,8
39,40,2008-06-11,"2500 West Grand Avenue, Chicago, IL 60654, USA",CULEX ERRATICUS,25,W GRAND AVE,T046,"2500 W GRAND AVE, Chicago, IL",41.891118,-87.654491,8
40,41,2008-06-11,"1100 Roosevelt Road, Chicago, IL 60608, USA",CULEX PIPIENS/RESTUANS,11,W ROOSEVELT,T048,"1100 W ROOSEVELT, Chicago, IL",41.867108,-87.654224,8
41,42,2008-06-11,"1100 Roosevelt Road, Chicago, IL 60608, USA",CULEX RESTUANS,11,W ROOSEVELT,T048,"1100 W ROOSEVELT, Chicago, IL",41.867108,-87.654224,8
42,43,2008-06-11,"1100 Roosevelt Road, Chicago, IL 60608, USA",CULEX PIPIENS,11,W ROOSEVELT,T048,"1100 W ROOSEVELT, Chicago, IL",41.867108,-87.654224,8
43,44,2008-06-11,"1100 Roosevelt Road, Chicago, IL 60608, USA",CULEX SALINARIUS,11,W ROOSEVELT,T048,"1100 W ROOSEVELT, Chicago, IL",41.867108,-87.654224,8
44,45,2008-06-11,"1100 Roosevelt Road, Chicago, IL 60608, USA",CULEX TERRITANS,11,W ROOSEVELT,T048,"1100 W ROOSEVELT, Chicago, IL",41.867108,-87.654224,8
45,46,2008-06-11,"1100 Roosevelt Road, Chicago, IL 60608, USA",CULEX TARSALIS,11,W ROOSEVELT,T048,"1100 W ROOSEVELT, Chicago, IL",41.867108,-87.654224,8
46,47,2008-06-11,"1100 Roosevelt Road, Chicago, IL 60608, USA",UNSPECIFIED CULEX,11,W ROOSEVELT,T048,"1100 W ROOSEVELT, Chicago, IL",41.867108,-87.654224,8
47,48,2008-06-11,"1100 Roosevelt Road, Chicago, IL 60608, USA",CULEX ERRATICUS,11,W ROOSEVELT,T048,"1100 W ROOSEVELT, Chicago, IL",41.867108,-87.654224,8
48,49,2008-06-11,"1100 West Chicago Avenue, Chicago, IL 60642, USA",CULEX PIPIENS/RESTUANS,11,W CHICAGO,T049,"1100 W CHICAGO, Chicago, IL",41.896282,-87.655232,8
49,50,2008-06-11,"1100 West Chicago Avenue, Chicago, IL 60642, USA",CULEX RESTUANS,11,W CHICAGO,T049,"1100 W CHICAGO, Chicago, IL",41.896282,-87.655232,8
...,...,...,...,...,...,...,...,...,...,...,...
116243,116244,2014-10-02,"4200 West 65th Street, Chicago, IL 60621, USA",UNSPECIFIED CULEX,42,W 65TH ST,T235,"4200 W 65TH ST, Chicago, IL",41.776428,-87.627096,8
116244,116245,2014-10-02,"4200 West 65th Street, Chicago, IL 60621, USA",CULEX ERRATICUS,42,W 65TH ST,T235,"4200 W 65TH ST, Chicago, IL",41.776428,-87.627096,8
116245,116246,2014-10-02,"6200 North Mcclellan Avenue, Chicago, IL 60646...",CULEX PIPIENS/RESTUANS,62,N MCCLELLAN AVE,T236,"6200 N MCCLELLAN AVE, Chicago, IL",41.994679,-87.770899,8
116246,116247,2014-10-02,"6200 North Mcclellan Avenue, Chicago, IL 60646...",CULEX RESTUANS,62,N MCCLELLAN AVE,T236,"6200 N MCCLELLAN AVE, Chicago, IL",41.994679,-87.770899,8
116247,116248,2014-10-02,"6200 North Mcclellan Avenue, Chicago, IL 60646...",CULEX PIPIENS,62,N MCCLELLAN AVE,T236,"6200 N MCCLELLAN AVE, Chicago, IL",41.994679,-87.770899,8
116248,116249,2014-10-02,"6200 North Mcclellan Avenue, Chicago, IL 60646...",CULEX SALINARIUS,62,N MCCLELLAN AVE,T236,"6200 N MCCLELLAN AVE, Chicago, IL",41.994679,-87.770899,8
116249,116250,2014-10-02,"6200 North Mcclellan Avenue, Chicago, IL 60646...",CULEX TERRITANS,62,N MCCLELLAN AVE,T236,"6200 N MCCLELLAN AVE, Chicago, IL",41.994679,-87.770899,8
116250,116251,2014-10-02,"6200 North Mcclellan Avenue, Chicago, IL 60646...",CULEX TARSALIS,62,N MCCLELLAN AVE,T236,"6200 N MCCLELLAN AVE, Chicago, IL",41.994679,-87.770899,8
116251,116252,2014-10-02,"6200 North Mcclellan Avenue, Chicago, IL 60646...",UNSPECIFIED CULEX,62,N MCCLELLAN AVE,T236,"6200 N MCCLELLAN AVE, Chicago, IL",41.994679,-87.770899,8
116252,116253,2014-10-02,"6200 North Mcclellan Avenue, Chicago, IL 60646...",CULEX ERRATICUS,62,N MCCLELLAN AVE,T236,"6200 N MCCLELLAN AVE, Chicago, IL",41.994679,-87.770899,8
116253,116254,2014-10-02,"2900 West 85th Street, Chicago, IL 60652, USA",CULEX PIPIENS/RESTUANS,29,W 85TH ST,T237,"2900 W 85TH ST, Chicago, IL",41.738903,-87.695443,8
116254,116255,2014-10-02,"2900 West 85th Street, Chicago, IL 60652, USA",CULEX RESTUANS,29,W 85TH ST,T237,"2900 W 85TH ST, Chicago, IL",41.738903,-87.695443,8
116255,116256,2014-10-02,"2900 West 85th Street, Chicago, IL 60652, USA",CULEX PIPIENS,29,W 85TH ST,T237,"2900 W 85TH ST, Chicago, IL",41.738903,-87.695443,8
116256,116257,2014-10-02,"2900 West 85th Street, Chicago, IL 60652, USA",CULEX SALINARIUS,29,W 85TH ST,T237,"2900 W 85TH ST, Chicago, IL",41.738903,-87.695443,8
116257,116258,2014-10-02,"2900 West 85th Street, Chicago, IL 60652, USA",CULEX TERRITANS,29,W 85TH ST,T237,"2900 W 85TH ST, Chicago, IL",41.738903,-87.695443,8
116258,116259,2014-10-02,"2900 West 85th Street, Chicago, IL 60652, USA",CULEX TARSALIS,29,W 85TH ST,T237,"2900 W 85TH ST, Chicago, IL",41.738903,-87.695443,8
116259,116260,2014-10-02,"2900 West 85th Street, Chicago, IL 60652, USA",UNSPECIFIED CULEX,29,W 85TH ST,T237,"2900 W 85TH ST, Chicago, IL",41.738903,-87.695443,8
116260,116261,2014-10-02,"2900 West 85th Street, Chicago, IL 60652, USA",CULEX ERRATICUS,29,W 85TH ST,T237,"2900 W 85TH ST, Chicago, IL",41.738903,-87.695443,8
116261,116262,2014-10-02,"3400 West 77th Street, Chicago, IL 60652, USA",CULEX PIPIENS/RESTUANS,34,W 77TH ST,T238,"3400 W 77TH ST, Chicago, IL",41.753391,-87.707394,8
116262,116263,2014-10-02,"3400 West 77th Street, Chicago, IL 60652, USA",CULEX RESTUANS,34,W 77TH ST,T238,"3400 W 77TH ST, Chicago, IL",41.753391,-87.707394,8
116263,116264,2014-10-02,"3400 West 77th Street, Chicago, IL 60652, USA",CULEX PIPIENS,34,W 77TH ST,T238,"3400 W 77TH ST, Chicago, IL",41.753391,-87.707394,8
116264,116265,2014-10-02,"3400 West 77th Street, Chicago, IL 60652, USA",CULEX SALINARIUS,34,W 77TH ST,T238,"3400 W 77TH ST, Chicago, IL",41.753391,-87.707394,8
116265,116266,2014-10-02,"3400 West 77th Street, Chicago, IL 60652, USA",CULEX TERRITANS,34,W 77TH ST,T238,"3400 W 77TH ST, Chicago, IL",41.753391,-87.707394,8
116266,116267,2014-10-02,"3400 West 77th Street, Chicago, IL 60652, USA",CULEX TARSALIS,34,W 77TH ST,T238,"3400 W 77TH ST, Chicago, IL",41.753391,-87.707394,8
116267,116268,2014-10-02,"3400 West 77th Street, Chicago, IL 60652, USA",UNSPECIFIED CULEX,34,W 77TH ST,T238,"3400 W 77TH ST, Chicago, IL",41.753391,-87.707394,8
116268,116269,2014-10-02,"3400 West 77th Street, Chicago, IL 60652, USA",CULEX ERRATICUS,34,W 77TH ST,T238,"3400 W 77TH ST, Chicago, IL",41.753391,-87.707394,8
116269,116270,2014-10-02,"5100 West 63rd Place, Chicago, IL 60638, USA",CULEX PIPIENS/RESTUANS,51,W 63RD PL,T065A,"5100 W 63RD PL, Chicago, IL",41.777689,-87.749149,9
116270,116271,2014-10-02,"5100 West 63rd Place, Chicago, IL 60638, USA",CULEX RESTUANS,51,W 63RD PL,T065A,"5100 W 63RD PL, Chicago, IL",41.777689,-87.749149,9
116271,116272,2014-10-02,"5100 West 63rd Place, Chicago, IL 60638, USA",CULEX PIPIENS,51,W 63RD PL,T065A,"5100 W 63RD PL, Chicago, IL",41.777689,-87.749149,9
116272,116273,2014-10-02,"5100 West 63rd Place, Chicago, IL 60638, USA",CULEX SALINARIUS,51,W 63RD PL,T065A,"5100 W 63RD PL, Chicago, IL",41.777689,-87.749149,9
116273,116274,2014-10-02,"5100 West 63rd Place, Chicago, IL 60638, USA",CULEX TERRITANS,51,W 63RD PL,T065A,"5100 W 63RD PL, Chicago, IL",41.777689,-87.749149,9
116274,116275,2014-10-02,"5100 West 63rd Place, Chicago, IL 60638, USA",CULEX TARSALIS,51,W 63RD PL,T065A,"5100 W 63RD PL, Chicago, IL",41.777689,-87.749149,9
116275,116276,2014-10-02,"5100 West 63rd Place, Chicago, IL 60638, USA",UNSPECIFIED CULEX,51,W 63RD PL,T065A,"5100 W 63RD PL, Chicago, IL",41.777689,-87.749149,9
116276,116277,2014-10-02,"5100 West 63rd Place, Chicago, IL 60638, USA",CULEX ERRATICUS,51,W 63RD PL,T065A,"5100 W 63RD PL, Chicago, IL",41.777689,-87.749149,9
116277,116278,2014-10-02,"9600 South Longwood Drive, Chicago, IL 60643, USA",CULEX PIPIENS/RESTUANS,96,S LONGWOOD DR,T094B,"9600 S LONGWOOD DR, Chicago, IL",41.719140,-87.669539,9
116278,116279,2014-10-02,"9600 South Longwood Drive, Chicago, IL 60643, USA",CULEX RESTUANS,96,S LONGWOOD DR,T094B,"9600 S LONGWOOD DR, Chicago, IL",41.719140,-87.669539,9
116279,116280,2014-10-02,"9600 South Longwood Drive, Chicago, IL 60643, USA",CULEX PIPIENS,96,S LONGWOOD DR,T094B,"9600 S LONGWOOD DR, Chicago, IL",41.719140,-87.669539,9
116280,116281,2014-10-02,"9600 South Longwood Drive, Chicago, IL 60643, USA",CULEX SALINARIUS,96,S LONGWOOD DR,T094B,"9600 S LONGWOOD DR, Chicago, IL",41.719140,-87.669539,9
116281,116282,2014-10-02,"9600 South Longwood Drive, Chicago, IL 60643, USA",CULEX TERRITANS,96,S LONGWOOD DR,T094B,"9600 S LONGWOOD DR, Chicago, IL",41.719140,-87.669539,9
116282,116283,2014-10-02,"9600 South Longwood Drive, Chicago, IL 60643, USA",CULEX TARSALIS,96,S LONGWOOD DR,T094B,"9600 S LONGWOOD DR, Chicago, IL",41.719140,-87.669539,9
116283,116284,2014-10-02,"9600 South Longwood Drive, Chicago, IL 60643, USA",UNSPECIFIED CULEX,96,S LONGWOOD DR,T094B,"9600 S LONGWOOD DR, Chicago, IL",41.719140,-87.669539,9
116284,116285,2014-10-02,"9600 South Longwood Drive, Chicago, IL 60643, USA",CULEX ERRATICUS,96,S LONGWOOD DR,T094B,"9600 S LONGWOOD DR, Chicago, IL",41.719140,-87.669539,9
116285,116286,2014-10-02,"2100 North Cannon Drive, Chicago, IL 60614, USA",CULEX PIPIENS/RESTUANS,21,N CANNON DR,T054C,"2100 N CANNON DR, Chicago, IL",41.925652,-87.633590,8
116286,116287,2014-10-02,"2100 North Cannon Drive, Chicago, IL 60614, USA",CULEX RESTUANS,21,N CANNON DR,T054C,"2100 N CANNON DR, Chicago, IL",41.925652,-87.633590,8
116287,116288,2014-10-02,"2100 North Cannon Drive, Chicago, IL 60614, USA",CULEX PIPIENS,21,N CANNON DR,T054C,"2100 N CANNON DR, Chicago, IL",41.925652,-87.633590,8
116288,116289,2014-10-02,"2100 North Cannon Drive, Chicago, IL 60614, USA",CULEX SALINARIUS,21,N CANNON DR,T054C,"2100 N CANNON DR, Chicago, IL",41.925652,-87.633590,8
116289,116290,2014-10-02,"2100 North Cannon Drive, Chicago, IL 60614, USA",CULEX TERRITANS,21,N CANNON DR,T054C,"2100 N CANNON DR, Chicago, IL",41.925652,-87.633590,8
116290,116291,2014-10-02,"2100 North Cannon Drive, Chicago, IL 60614, USA",CULEX TARSALIS,21,N CANNON DR,T054C,"2100 N CANNON DR, Chicago, IL",41.925652,-87.633590,8
116291,116292,2014-10-02,"2100 North Cannon Drive, Chicago, IL 60614, USA",UNSPECIFIED CULEX,21,N CANNON DR,T054C,"2100 N CANNON DR, Chicago, IL",41.925652,-87.633590,8
116292,116293,2014-10-02,"2100 North Cannon Drive, Chicago, IL 60614, USA",CULEX ERRATICUS,21,N CANNON DR,T054C,"2100 N CANNON DR, Chicago, IL",41.925652,-87.633590,8

In [27]:
weather

,Station,Date,Tmax,Tmin,Tavg,Depart,DewPoint,WetBulb,Heat,Cool,Sunrise,Sunset,CodeSum,Depth,Water1,SnowFall,PrecipTotal,StnPressure,SeaLevel,ResultSpeed,ResultDir,AvgSpeed
0,1,2007-05-01,83,50,67,14,51,56,0,2,0448,1849,,0,M,0.0,0.00,29.10,29.82,1.7,27,9.2
1,2,2007-05-01,84,52,68,M,51,57,0,3,-,-,,M,M,M,0.00,29.18,29.82,2.7,25,9.6
2,1,2007-05-02,59,42,51,-3,42,47,14,0,0447,1850,BR,0,M,0.0,0.00,29.38,30.09,13.0,4,13.4
3,2,2007-05-02,60,43,52,M,42,47,13,0,-,-,BR HZ,M,M,M,0.00,29.44,30.08,13.3,2,13.4
4,1,2007-05-03,66,46,56,2,40,48,9,0,0446,1851,,0,M,0.0,0.00,29.39,30.12,11.7,7,11.9
5,2,2007-05-03,67,48,58,M,40,50,7,0,-,-,HZ,M,M,M,0.00,29.46,30.12,12.9,6,13.2
6,1,2007-05-04,66,49,58,4,41,50,7,0,0444,1852,RA,0,M,0.0,T,29.31,30.05,10.4,8,10.8
7,2,2007-05-04,78,51,M,M,42,50,M,M,-,-,,M,M,M,0.00,29.36,30.04,10.1,7,10.4
8,1,2007-05-05,66,53,60,5,38,49,5,0,0443,1853,,0,M,0.0,T,29.40,30.10,11.7,7,12.0
9,2,2007-05-05,66,54,60,M,39,50,5,0,-,-,,M,M,M,T,29.46,30.09,11.2,7,11.5
10,1,2007-05-06,68,49,59,4,30,46,6,0,0442,1855,,0,M,0.0,0.00,29.57,30.29,14.4,11,15.0
11,2,2007-05-06,68,52,60,M,30,46,5,0,-,-,,M,M,M,0.00,29.62,30.28,13.8,10,14.5
12,1,2007-05-07,83,47,65,10,41,54,0,0,0441,1856,RA,0,M,0.0,T,29.38,30.12,8.6,18,10.5
13,2,2007-05-07,84,50,67,M,39,53,0,2,-,-,,M,M,M,0.00,29.44,30.12,8.5,17,9.9
14,1,2007-05-08,82,54,68,12,58,62,0,3,0439,1857,BR,0,M,0.0,0.00,29.29,30.03,2.7,11,5.8
15,2,2007-05-08,80,60,70,M,57,63,0,5,-,-,HZ,M,M,M,T,29.36,30.02,2.5,8,5.4
16,1,2007-05-09,77,61,69,13,59,63,0,4,0438,1858,BR HZ,0,M,0.0,0.13,29.21,29.94,3.9,9,6.2
17,2,2007-05-09,76,63,70,M,60,63,0,5,-,-,BR HZ,M,M,M,0.02,29.28,29.93,3.9,7,5.9
18,1,2007-05-10,84,56,70,14,52,60,0,5,0437,1859,BR,0,M,0.0,0.00,29.20,29.92,0.7,17,4.1
19,2,2007-05-10,83,59,71,M,52,61,0,6,-,-,BR HZ,M,M,M,0.00,29.26,29.91,2.0,9,3.9
20,1,2007-05-11,70,51,61,4,42,51,4,0,0436,1860,,0,M,0.0,0.00,29.33,30.04,11.3,3,12.9
21,2,2007-05-11,73,49,61,M,44,51,4,0,-,-,,M,M,M,0.00,29.39,30.03,11.7,36,12.8
22,1,2007-05-12,64,46,55,-2,36,46,10,0,0435,1901,,0,M,0.0,0.00,29.49,30.20,12.4,3,12.9
23,2,2007-05-12,65,47,56,M,37,46,9,0,-,-,,M,M,M,0.00,29.54,30.19,12.7,1,13.0
24,1,2007-05-13,69,43,56,-2,33,46,9,0,0434,1902,,0,M,0.0,0.00,29.49,30.24,6.6,14,8.1
25,2,2007-05-13,69,44,57,M,32,46,8,0,-,-,,M,M,M,0.00,29.55,30.24,6.4,11,7.6
26,1,2007-05-14,90,56,73,15,47,59,0,8,0433,1903,,0,M,0.0,0.00,29.23,29.97,16.9,21,17.3
27,2,2007-05-14,90,54,72,M,45,58,0,7,-,-,,M,M,M,0.00,29.31,29.98,14.1,21,14.6
28,1,2007-05-15,80,57,69,11,56,61,0,4,0432,1904,RA BR,0,M,0.0,0.38,29.13,29.84,8.1,27,12.3
29,2,2007-05-15,82,56,69,M,56,61,0,4,-,-,TSRA RA BR,M,M,M,0.60,29.19,29.83,8.1,25,10.8
30,1,2007-05-16,66,44,55,-4,43,48,10,0,0431,1905,RA BR,0,M,0.0,0.14,29.33,30.03,7.8,36,12.2
31,2,2007-05-16,64,45,55,M,42,47,10,0,-,-,RA BR,M,M,M,0.07,29.39,30.03,8.0,36,11.8
32,1,2007-05-17,62,43,53,-6,32,43,12,0,0430,1906,,0,M,0.0,0.00,29.55,30.27,10.5,3,11.3
33,2,2007-05-17,61,44,53,M,32,43,12,0,-,-,,M,M,M,0.00,29.62,30.27,11.7,1,12.2
34,1,2007-05-18,71,42,57,-3,30,46,8,0,0429,1907,,0,M,0.0,0.00,29.53,30.25,5.4,25,7.5
35,2,2007-05-18,70,43,57,M,31,47,8,0,-,-,,M,M,M,0.00,29.60,30.26,3.4,22,5.5
36,1,2007-05-19,80,56,68,8,39,53,0,3,0428,1908,,0,M,0.0,0.00,29.34,30.08,11.1,24,11.4
37,2,2007-05-19,80,56,68,M,37,53,0,3,-,-,,M,M,M,0.00,29.41,30.08,11.1,23,11.4
38,1,2007-05-20,69,43,56,-5,40,44,9,0,0427,1909,RA VCTS,0,M,0.0,0.07,29.38,30.11,10.4,4,10.7
39,2,2007-05-20,69,44,57,M,41,45,8,0,-,-,TSRA RA,M,M,M,0.11,29.44,30.11,8.6,3,9.7
40,1,2007-05-21,80,44,62,1,50,56,3,0,0426,1910,,0,M,0.0,0.00,29.33,30.06,6.3,11,8.2
41,2,2007-05-21,79,46,63,M,50,57,2,0,-,-,,M,M,M,0.00,29.39,30.05,6.3,10,7.8
42,1,2007-05-22,87,55,71,10,46,58,0,6,0425,1911,,0,M,0.0,0.00,29.34,30.06,10.0,18,10.2
43,2,2007-05-22,87,60,74,M,44,58,0,9,-,-,,M,M,M,0.00,29.41,30.05,10.1,16,10.6
44,1,2007-05-23,89,60,75,14,49,61,0,10,0425,1912,,0,M,0.0,0.00,29.39,30.10,11.4,19,11.8
45,2,2007-05-23,89,66,78,M,48,61,0,13,-,-,,M,M,M,0.00,29.47,30.10,10.9,18,11.2
46,1,2007-05-24,88,63,76,14,54,63,0,11,0424,1913,RA HZ,0,M,0.0,0.02,29.41,30.11,14.9,21,17.3
47,2,2007-05-24,88,66,77,M,53,63,0,12,-,-,RA HZ,M,M,M,T,29.47,30.10,13.8,20,15.2
48,1,2007-05-25,70,56,63,1,44,53,2,0,0423,1914,,0,M,0.0,T,29.51,30.24,4.9,5,8.8
49,2,2007-05-25,66,57,62,M,46,53,3,0,-,-,RA BR,M,M,M,0.09,29.57,30.23,4.5,5,8.2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2894,1,2014-10-07,66,48,57,1,43,50,8,0,0555,1724,,0,M,0.0,T,29.00,29.69,9.8,25,11.5
2895,2,2014-10-07,69,49,59,M,45,51,6,0,-,-,,M,M,M,0.00,29.06,29.70,10.3,24,11.7
2896,1,2014-10-08,65,44,55,-1,35,46,10,0,0556,1722,,0,M,0.0,0.00,29.27,29.97,11.0,27,11.3
2897,2,2014-10-08,67,48,58,M,36,48,7,0,-,-,,M,M,M,0.00,29.34,29.97,10.7,27,11.2
2898,1,2014-10-09,62,43,53,-2,34,44,12,0,0557,1720,,0,M,0.0,0.00,29.38,30.09,3.4,36,5.8
2899,2,2014-10-09,64,50,57,M,36,46,8,0,-,-,,M,M,M,0.00,29.44,30.09,3.4,2,6.3
2900,1,2014-10-10,58,39,49,-6,39,44,16,0,0558,1719,,0,M,0.0,0.00,29.43,30.16,7.7,2,8.2
2901,2,2014-10-10,59,44,52,M,40,46,13,0,-,-,,M,M,M,0.00,29.49,30.16,3.8,2,5.2
2902,1,2014-10-11,59,36,48,-6,34,42,17,0,0559,1717,,0,M,0.0,0.00,29.47,30.20,2.8,8,4.5
2903,2,2014-10-11,60,40,50,M,36,44,15,0,-,-,,M,M,M,0.00,29.53,30.20,3.5,8,4.7
2904,1,2014-10-12,63,38,51,-3,42,47,14,0,0600,1715,RA DZ BR,0,M,0.0,0.01,29.24,30.00,7.9,14,9.1
2905,2,2014-10-12,64,45,55,M,44,50,10,0,-,-,RA DZ BR,M,M,M,0.01,29.31,30.00,9.5,14,9.9
2906,1,2014-10-13,67,56,62,9,58,60,3,0,0602,1714,RA DZ BR,0,M,0.0,0.64,28.97,29.73,7.7,14,9.1
2907,2,2014-10-13,71,59,65,M,61,62,0,0,-,-,RA BR HZ,M,M,M,0.44,29.03,29.73,7.5,15,8.9
2908,1,2014-10-14,65,52,59,6,57,58,6,0,0603,1712,RA DZ BR,0,M,0.0,0.65,28.83,29.55,3.5,10,10.2
2909,2,2014-10-14,67,54,61,M,59,60,4,0,-,-,RA DZ BR,M,M,M,1.18,28.89,29.54,1.8,12,8.6
2910,1,2014-10-15,55,50,53,0,51,51,12,0,0604,1711,RA DZ BR,0,M,0.0,0.05,29.05,29.75,9.5,35,9.9
2911,2,2014-10-15,58,53,56,M,53,54,9,0,-,-,RA DZ BR,M,M,M,0.07,29.10,29.74,9.4,35,9.7
2912,1,2014-10-16,56,50,53,1,49,51,12,0,0605,1709,DZ BR,0,M,0.0,T,29.02,29.77,4.1,24,7.4
2913,2,2014-10-16,58,53,56,M,52,53,9,0,-,-,DZ BR,M,M,M,T,29.09,29.77,5.4,25,8.4
2914,1,2014-10-17,62,48,55,3,46,50,10,0,0606,1707,,0,M,0.0,T,28.99,29.69,11.1,29,13.2
2915,2,2014-10-17,63,49,56,M,48,52,9,0,-,-,,M,M,M,0.01,29.05,29.69,10.7,28,12.7
2916,1,2014-10-18,50,36,43,-8,38,42,22,0,0607,1706,RA DZ,0,M,0.0,0.01,29.39,30.08,8.2,34,9.2
2917,2,2014-10-18,52,39,46,M,40,44,19,0,-,-,RA,M,M,M,0.02,29.44,30.08,7.6,34,8.7
2918,1,2014-10-19,54,33,44,-7,38,43,21,0,0608,1704,,0,M,0.0,0.00,29.31,30.07,7.8,21,8.2
2919,2,2014-10-19,57,36,47,M,40,44,18,0,-,-,,M,M,M,0.00,29.39,30.09,8.8,21,9.0
2920,1,2014-10-20,65,46,56,6,44,49,9,0,0610,1703,,0,M,0.0,0.01,29.17,29.90,4.7,32,9.3
2921,2,2014-10-20,66,50,58,M,46,51,7,0,-,-,,M,M,M,0.00,29.23,29.90,4.9,32,9.1
2922,1,2014-10-21,53,45,49,-1,39,44,16,0,0611,1701,,0,M,0.0,0.00,29.46,30.16,10.8,1,11.4
2923,2,2014-10-21,54,49,52,M,41,46,13,0,-,-,,M,M,M,0.00,29.51,30.15,11.0,36,11.6
2924,1,2014-10-22,56,35,46,-4,38,43,19,0,0612,1660,,0,M,0.0,0.00,29.56,30.30,2.9,8,4.8
2925,2,2014-10-22,56,43,50,M,38,44,15,0,-,-,,M,M,M,0.00,29.62,30.30,3.0,11,5.1
2926,1,2014-10-23,59,36,48,-1,40,45,17,0,0613,1658,BR,0,M,0.0,0.00,29.39,30.15,7.5,19,7.8
2927,2,2014-10-23,62,41,52,M,41,47,13,0,-,-,BR,M,M,M,T,29.46,30.16,7.9,19,8.4
2928,1,2014-10-24,67,52,60,11,46,52,5,0,0614,1657,,0,M,0.0,0.00,29.25,30.00,4.4,22,5.8
2929,2,2014-10-24,68,54,61,M,48,53,4,0,-,-,,M,M,M,0.00,29.31,30.00,4.9,22,5.8
2930,1,2014-10-25,72,49,61,13,40,51,4,0,0616,1656,BR,0,M,0.0,0.00,29.21,29.93,10.4,29,10.9
2931,2,2014-10-25,75,52,64,M,41,52,1,0,-,-,BR HZ,M,M,M,0.00,29.27,29.92,9.7,28,10.4
2932,1,2014-10-26,64,42,53,5,32,44,12,0,0617,1654,,0,M,0.0,0.00,29.21,29.95,0.9,5,5.8
2933,2,2014-10-26,66,44,55,M,33,45,10,0,-,-,,M,M,M,0.00,29.28,29.95,1.6,11,5.4
2934,1,2014-10-27,77,51,64,16,51,58,1,0,0618,1653,,0,M,0.0,0.00,28.92,29.66,12.0,19,12.9
2935,2,2014-10-27,79,54,67,M,52,59,0,2,-,-,RA,M,M,M,0.02,29.00,29.67,12.7,19,13.6
2936,1,2014-10-28,68,45,57,10,38,47,8,0,0619,1651,,0,M,0.0,T,29.15,29.85,14.8,26,15.6
2937,2,2014-10-28,66,48,57,M,40,48,8,0,-,-,RA,M,M,M,0.03,29.23,29.85,14.0,26,14.6
2938,1,2014-10-29,49,36,43,-4,32,40,22,0,0620,1650,,0,M,0.0,0.00,29.36,30.06,9.5,29,9.9
2939,2,2014-10-29,49,40,45,M,34,42,20,0,-,-,,M,M,M,0.00,29.42,30.07,8.5,29,9.0
2940,1,2014-10-30,51,32,42,-4,34,40,23,0,0622,1649,,0,M,0.0,0.00,29.34,30.09,5.1,24,5.5
2941,2,2014-10-30,53,37,45,M,35,42,20,0,-,-,RA,M,M,M,T,29.41,30.10,5.9,23,6.5
2942,1,2014-10-31,47,33,40,-6,25,33,25,0,0623,1647,RA SN,0,M,0.1,0.03,29.49,30.20,22.6,34,22.9
2943,2,2014-10-31,49,34,42,M,29,36,23,0,-,-,RA SN BR,M,M,M,0.04,29.54,30.20,21.7,34,22.6

## Cleaning and Formatting

### Formatting the Weather DF

In [28]:
# Setting the index to date in order to average the values between duplicates 
weather.set_index("Date", inplace=True)

# Dropping Station and CodeSum because of lack of either unique values or quantity of values
weather.drop(['Station', 'CodeSum'], axis=1, inplace=True)

# Converting values to numeric in order to average
weather = weather.apply(pd.to_numeric, errors='coerce')

# Combining 'Sunrise' and 'Sunset' into a new column called 'Daylight' in hours (Feature Engineering)
# Divided by 100 to get the amount of hours
weather['Daylight'] = ((weather['Sunset'] - weather['Sunrise']) / 100)

# Dropping the columns used in the calculation
weather.drop(['Sunset', 'Sunrise'], axis=1, inplace=True)

# Averaging the values between the stations but excluding the NaNs
weather = weather.groupby(level=0).mean()

# Resetting the index for concatenation
weather.reset_index(inplace=True)

# Viewing the final DF
weather

,Date,Tmax,Tmin,Tavg,Depart,DewPoint,WetBulb,Heat,Cool,Depth,Water1,SnowFall,PrecipTotal,StnPressure,SeaLevel,ResultSpeed,ResultDir,AvgSpeed,Daylight
0,2007-05-01,83.5,51.0,67.5,14.0,51.0,56.5,0.0,2.5,0.0,NaN,0.0,0.000,29.140,29.820,2.20,26.0,9.40,14.01
1,2007-05-02,59.5,42.5,51.5,-3.0,42.0,47.0,13.5,0.0,0.0,NaN,0.0,0.000,29.410,30.085,13.15,3.0,13.40,14.03
2,2007-05-03,66.5,47.0,57.0,2.0,40.0,49.0,8.0,0.0,0.0,NaN,0.0,0.000,29.425,30.120,12.30,6.5,12.55,14.05
3,2007-05-04,72.0,50.0,58.0,4.0,41.5,50.0,7.0,0.0,0.0,NaN,0.0,0.000,29.335,30.045,10.25,7.5,10.60,14.08
4,2007-05-05,66.0,53.5,60.0,5.0,38.5,49.5,5.0,0.0,0.0,NaN,0.0,NaN,29.430,30.095,11.45,7.0,11.75,14.10
5,2007-05-06,68.0,50.5,59.5,4.0,30.0,46.0,5.5,0.0,0.0,NaN,0.0,0.000,29.595,30.285,14.10,10.5,14.75,14.13
6,2007-05-07,83.5,48.5,66.0,10.0,40.0,53.5,0.0,1.0,0.0,NaN,0.0,0.000,29.410,30.120,8.55,17.5,10.20,14.15
7,2007-05-08,81.0,57.0,69.0,12.0,57.5,62.5,0.0,4.0,0.0,NaN,0.0,0.000,29.325,30.025,2.60,9.5,5.60,14.18
8,2007-05-09,76.5,62.0,69.5,13.0,59.5,63.0,0.0,4.5,0.0,NaN,0.0,0.075,29.245,29.935,3.90,8.0,6.05,14.20
9,2007-05-10,83.5,57.5,70.5,14.0,52.0,60.5,0.0,5.5,0.0,NaN,0.0,0.000,29.230,29.915,1.35,13.0,4.00,14.22
10,2007-05-11,71.5,50.0,61.0,4.0,43.0,51.0,4.0,0.0,0.0,NaN,0.0,0.000,29.360,30.035,11.50,19.5,12.85,14.24
11,2007-05-12,64.5,46.5,55.5,-2.0,36.5,46.0,9.5,0.0,0.0,NaN,0.0,0.000,29.515,30.195,12.55,2.0,12.95,14.66
12,2007-05-13,69.0,43.5,56.5,-2.0,32.5,46.0,8.5,0.0,0.0,NaN,0.0,0.000,29.520,30.240,6.50,12.5,7.85,14.68
13,2007-05-14,90.0,55.0,72.5,15.0,46.0,58.5,0.0,7.5,0.0,NaN,0.0,0.000,29.270,29.975,15.50,21.0,15.95,14.70
14,2007-05-15,81.0,56.5,69.0,11.0,56.0,61.0,0.0,4.0,0.0,NaN,0.0,0.490,29.160,29.835,8.10,26.0,11.55,14.72
15,2007-05-16,65.0,44.5,55.0,-4.0,42.5,47.5,10.0,0.0,0.0,NaN,0.0,0.105,29.360,30.030,7.90,36.0,12.00,14.74
16,2007-05-17,61.5,43.5,53.0,-6.0,32.0,43.0,12.0,0.0,0.0,NaN,0.0,0.000,29.585,30.270,11.10,2.0,11.75,14.76
17,2007-05-18,70.5,42.5,57.0,-3.0,30.5,46.5,8.0,0.0,0.0,NaN,0.0,0.000,29.565,30.255,4.40,23.5,6.50,14.78
18,2007-05-19,80.0,56.0,68.0,8.0,38.0,53.0,0.0,3.0,0.0,NaN,0.0,0.000,29.375,30.080,11.10,23.5,11.40,14.80
19,2007-05-20,69.0,43.5,56.5,-5.0,40.5,44.5,8.5,0.0,0.0,NaN,0.0,0.090,29.410,30.110,9.50,3.5,10.20,14.82
20,2007-05-21,79.5,45.0,62.5,1.0,50.0,56.5,2.5,0.0,0.0,NaN,0.0,0.000,29.360,30.055,6.30,10.5,8.00,14.84
21,2007-05-22,87.0,57.5,72.5,10.0,45.0,58.0,0.0,7.5,0.0,NaN,0.0,0.000,29.375,30.055,10.05,17.0,10.40,14.86
22,2007-05-23,89.0,63.0,76.5,14.0,48.5,61.0,0.0,11.5,0.0,NaN,0.0,0.000,29.430,30.100,11.15,18.5,11.50,14.87
23,2007-05-24,88.0,64.5,76.5,14.0,53.5,63.0,0.0,11.5,0.0,NaN,0.0,0.020,29.440,30.105,14.35,20.5,16.25,14.89
24,2007-05-25,68.0,56.5,62.5,1.0,45.0,53.0,2.5,0.0,0.0,NaN,0.0,0.090,29.540,30.235,4.70,5.0,8.50,14.91
25,2007-05-26,67.5,49.5,58.5,-5.0,55.0,56.5,6.5,0.0,0.0,NaN,0.0,0.645,29.390,30.105,2.65,16.0,7.50,14.93
26,2007-05-27,75.0,58.0,66.5,4.0,48.0,56.5,0.0,1.5,0.0,NaN,0.0,0.060,29.375,30.055,8.55,25.0,9.35,14.94
27,2007-05-28,77.5,52.0,65.0,2.0,48.0,56.5,0.0,0.0,0.0,NaN,0.0,0.000,29.460,30.145,4.75,9.0,5.25,14.95
28,2007-05-29,88.0,62.5,75.5,10.0,58.5,65.5,0.0,10.5,0.0,NaN,0.0,0.000,29.415,30.100,5.80,17.0,6.95,14.96
29,2007-05-30,88.0,68.0,78.5,13.0,57.5,65.5,0.0,13.5,0.0,NaN,0.0,0.000,29.345,30.035,10.00,18.0,10.35,14.98
30,2007-05-31,79.0,66.5,73.0,8.0,61.0,65.5,0.0,8.0,0.0,NaN,0.0,0.270,29.310,29.995,9.10,18.5,9.55,14.99
31,2007-06-01,85.5,64.5,75.5,10.0,63.0,66.5,0.0,10.5,0.0,NaN,0.0,0.200,29.220,29.905,4.45,16.5,6.10,15.01
32,2007-06-02,81.0,66.5,74.0,9.0,62.5,67.0,0.0,9.0,0.0,NaN,0.0,0.040,29.065,29.765,7.00,21.5,7.80,15.01
33,2007-06-03,77.5,63.0,70.5,6.0,60.0,63.5,0.0,5.5,0.0,NaN,0.0,0.165,28.845,29.550,5.05,24.5,6.95,15.03
34,2007-06-04,71.5,57.0,64.5,1.0,57.5,60.0,0.5,0.0,0.0,NaN,0.0,0.350,28.850,29.515,7.85,30.5,9.90,15.04
35,2007-06-05,63.5,49.0,56.5,-9.0,47.5,51.5,8.5,0.0,0.0,NaN,0.0,0.345,29.130,29.785,5.70,4.0,7.85,15.06
36,2007-06-06,72.0,46.0,59.5,-8.0,47.5,55.0,5.5,0.0,0.0,NaN,0.0,0.010,29.100,29.815,10.20,16.0,11.00,15.06
37,2007-06-07,91.5,71.0,81.5,15.0,61.5,68.5,0.0,16.5,0.0,NaN,0.0,0.000,28.875,29.550,21.50,19.5,21.90,15.07
38,2007-06-08,81.0,60.0,70.5,3.0,53.5,61.5,0.0,5.5,0.0,NaN,0.0,0.000,29.210,29.840,10.10,27.0,13.10,15.08
39,2007-06-09,79.0,54.5,67.0,0.0,48.0,57.5,0.0,2.0,0.0,NaN,0.0,0.000,29.390,30.060,1.35,26.0,4.85,15.09
40,2007-06-10,81.0,58.0,69.5,1.0,50.5,59.5,0.0,4.5,0.0,NaN,0.0,0.000,29.365,30.045,4.70,16.5,5.70,15.10
41,2007-06-11,85.5,61.5,73.5,5.0,51.5,61.0,0.0,8.5,0.0,NaN,0.0,0.000,29.440,30.100,5.75,10.0,7.65,15.10
42,2007-06-12,82.5,64.0,73.5,5.0,50.5,60.5,0.0,8.5,0.0,NaN,0.0,0.000,29.465,30.150,8.85,5.0,9.40,15.11
43,2007-06-13,86.5,64.0,75.5,6.0,53.0,62.0,0.0,10.5,0.0,NaN,0.0,0.000,29.360,30.090,7.10,5.0,8.60,15.11
44,2007-06-14,89.0,66.0,78.0,9.0,54.5,63.5,0.0,13.0,0.0,NaN,0.0,0.000,29.330,30.010,5.75,6.0,6.60,15.12
45,2007-06-15,90.0,65.0,77.5,9.0,56.0,64.5,0.0,12.5,0.0,NaN,0.0,0.000,29.310,29.980,3.95,7.5,4.50,15.12
46,2007-06-16,92.5,67.0,80.0,11.0,60.5,67.5,0.0,15.0,0.0,NaN,0.0,NaN,29.295,29.965,3.45,25.0,5.95,15.13
47,2007-06-17,91.0,70.5,81.0,12.0,64.5,70.0,0.0,16.0,0.0,NaN,0.0,0.080,29.255,29.940,3.40,11.0,6.20,15.13
48,2007-06-18,89.0,71.0,80.0,9.0,65.0,70.0,0.0,15.0,0.0,NaN,0.0,0.150,29.155,29.835,13.10,20.0,13.85,15.13
49,2007-06-19,80.5,65.0,73.0,3.0,55.0,63.0,0.0,8.0,0.0,NaN,0.0,0.755,29.285,29.940,10.40,28.5,11.35,15.14
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1422,2014-09-12,56.0,45.0,51.0,-15.0,45.5,48.0,14.0,0.0,0.0,NaN,0.0,0.115,29.575,30.265,11.35,34.5,12.15,12.81
1423,2014-09-13,59.5,41.5,50.5,-15.0,41.0,45.5,14.5,0.0,0.0,NaN,0.0,0.005,29.625,30.330,3.15,33.0,7.30,12.78
1424,2014-09-14,66.0,44.0,55.5,-10.0,43.5,50.0,9.5,0.0,0.0,NaN,0.0,0.000,29.530,30.250,4.35,22.0,4.75,12.75
1425,2014-09-15,62.0,52.5,57.5,-7.0,49.0,53.0,7.5,0.0,0.0,NaN,0.0,NaN,29.435,30.135,2.55,29.5,5.65,12.72
1426,2014-09-16,68.5,45.5,57.0,-8.0,44.5,51.0,8.0,0.0,0.0,NaN,0.0,0.000,29.440,30.150,2.25,32.0,4.55,12.28
1427,2014-09-17,71.0,48.5,60.0,-5.0,46.5,53.0,5.0,0.0,0.0,NaN,0.0,0.000,29.325,30.020,0.95,16.5,3.40,12.25
1428,2014-09-18,71.0,53.0,62.5,-2.0,53.0,56.5,2.5,0.0,0.0,NaN,0.0,0.000,29.430,30.115,5.15,3.5,6.10,12.21
1429,2014-09-19,77.0,55.0,66.5,3.0,48.5,56.5,0.0,1.5,0.0,NaN,0.0,0.000,29.345,30.055,10.35,18.0,11.00,12.19
1430,2014-09-20,78.5,63.0,71.0,8.0,61.5,64.5,0.0,6.0,0.0,NaN,0.0,0.120,29.135,29.830,10.65,22.5,11.10,12.16
1431,2014-09-21,69.5,51.5,60.5,-2.0,50.5,55.5,4.5,0.0,0.0,NaN,0.0,NaN,29.285,29.935,9.95,31.0,12.80,12.13
1432,2014-09-22,68.0,47.0,58.0,-5.0,44.0,50.5,7.0,0.0,0.0,NaN,0.0,0.000,29.555,30.220,1.50,32.0,5.85,12.10
1433,2014-09-23,75.0,50.5,63.0,2.0,47.0,54.0,2.0,0.0,0.0,NaN,0.0,0.000,29.605,30.300,2.60,18.5,5.25,12.08
1434,2014-09-24,77.0,54.0,66.0,5.0,49.5,56.5,0.0,1.0,0.0,NaN,0.0,0.000,29.600,30.295,4.20,13.0,5.50,12.05
1435,2014-09-25,76.0,57.0,66.5,4.0,53.0,58.5,0.0,1.5,0.0,NaN,0.0,0.000,29.550,30.245,1.25,12.0,2.80,12.02
1436,2014-09-26,80.0,55.0,67.5,5.0,54.0,59.5,0.0,2.5,0.0,NaN,0.0,0.000,29.540,30.225,4.20,7.5,4.85,11.99
1437,2014-09-27,79.0,57.5,68.5,7.0,55.5,60.5,0.0,3.5,0.0,NaN,0.0,0.000,29.505,30.200,3.55,7.5,4.25,11.97
1438,2014-09-28,78.5,55.5,67.5,7.0,56.0,60.5,0.0,2.5,0.0,NaN,0.0,0.000,29.410,30.110,2.45,7.0,3.25,11.94
1439,2014-09-29,83.5,55.0,69.5,9.0,55.5,59.5,0.0,4.5,0.0,NaN,0.0,0.010,29.305,29.995,4.75,35.0,9.00,11.91
1440,2014-09-30,59.5,49.0,54.5,-6.0,48.0,51.0,10.5,0.0,0.0,NaN,0.0,NaN,29.325,30.025,8.95,2.0,10.20,11.88
1441,2014-10-01,71.5,50.5,61.5,2.0,50.5,56.0,3.5,0.0,0.0,NaN,0.0,0.000,29.250,29.950,9.15,13.0,9.50,11.86
1442,2014-10-02,73.5,64.5,69.5,10.0,62.0,64.0,0.0,4.5,0.0,NaN,0.0,0.520,29.065,29.780,7.20,17.0,7.90,11.83
1443,2014-10-03,66.5,44.5,55.5,-3.0,46.0,50.5,9.5,0.0,0.0,NaN,0.0,0.865,28.985,29.665,14.55,28.0,16.00,11.80
1444,2014-10-04,48.0,36.0,42.0,-16.0,34.5,40.0,23.0,0.0,0.0,NaN,NaN,0.055,29.035,29.730,13.55,25.5,13.65,11.77
1445,2014-10-05,55.5,39.5,47.5,-11.0,35.5,43.0,17.5,0.0,0.0,NaN,0.0,0.010,28.985,29.690,9.30,23.0,9.85,11.74
1446,2014-10-06,62.0,45.0,54.0,-4.0,39.0,46.0,11.0,0.0,0.0,NaN,0.0,0.010,28.920,29.615,8.70,24.0,9.65,11.71
1447,2014-10-07,67.5,48.5,58.0,1.0,44.0,50.5,7.0,0.0,0.0,NaN,0.0,0.000,29.030,29.695,10.05,24.5,11.60,11.69
1448,2014-10-08,66.0,46.0,56.5,-1.0,35.5,47.0,8.5,0.0,0.0,NaN,0.0,0.000,29.305,29.970,10.85,27.0,11.25,11.66
1449,2014-10-09,63.0,46.5,55.0,-2.0,35.0,45.0,10.0,0.0,0.0,NaN,0.0,0.000,29.410,30.090,3.40,19.0,6.05,11.63
1450,2014-10-10,58.5,41.5,50.5,-6.0,39.5,45.0,14.5,0.0,0.0,NaN,0.0,0.000,29.460,30.160,5.75,2.0,6.70,11.61
1451,2014-10-11,59.5,38.0,49.0,-6.0,35.0,43.0,16.0,0.0,0.0,NaN,0.0,0.000,29.500,30.200,3.15,8.0,4.60,11.58
1452,2014-10-12,63.5,41.5,53.0,-3.0,43.0,48.5,12.0,0.0,0.0,NaN,0.0,0.010,29.275,30.000,8.70,14.0,9.50,11.15
1453,2014-10-13,69.0,57.5,63.5,9.0,59.5,61.0,1.5,0.0,0.0,NaN,0.0,0.540,29.000,29.730,7.60,14.5,9.00,11.12
1454,2014-10-14,66.0,53.0,60.0,6.0,58.0,59.0,5.0,0.0,0.0,NaN,0.0,0.915,28.860,29.545,2.65,11.0,9.40,11.09
1455,2014-10-15,56.5,51.5,54.5,0.0,52.0,52.5,10.5,0.0,0.0,NaN,0.0,0.060,29.075,29.745,9.45,35.0,9.80,11.07
1456,2014-10-16,57.0,51.5,54.5,1.0,50.5,52.0,10.5,0.0,0.0,NaN,0.0,NaN,29.055,29.770,4.75,24.5,7.90,11.04
1457,2014-10-17,62.5,48.5,55.5,3.0,47.0,51.0,9.5,0.0,0.0,NaN,0.0,0.010,29.020,29.690,10.90,28.5,12.95,11.01
1458,2014-10-18,51.0,37.5,44.5,-8.0,39.0,43.0,20.5,0.0,0.0,NaN,0.0,0.015,29.415,30.080,7.90,34.0,8.95,10.99
1459,2014-10-19,55.5,34.5,45.5,-7.0,39.0,43.5,19.5,0.0,0.0,NaN,0.0,0.000,29.350,30.080,8.30,21.0,8.60,10.96
1460,2014-10-20,65.5,48.0,57.0,6.0,45.0,50.0,8.0,0.0,0.0,NaN,0.0,0.005,29.200,29.900,4.80,32.0,9.20,10.93
1461,2014-10-21,53.5,47.0,50.5,-1.0,40.0,45.0,14.5,0.0,0.0,NaN,0.0,0.000,29.485,30.155,10.90,18.5,11.50,10.90
1462,2014-10-22,56.0,39.0,48.0,-4.0,38.0,43.5,17.0,0.0,0.0,NaN,0.0,0.000,29.590,30.300,2.95,9.5,4.95,10.48
1463,2014-10-23,60.5,38.5,50.0,-1.0,40.5,46.0,15.0,0.0,0.0,NaN,0.0,0.000,29.425,30.155,7.70,19.0,8.10,10.45
1464,2014-10-24,67.5,53.0,60.5,11.0,47.0,52.5,4.5,0.0,0.0,NaN,0.0,0.000,29.280,30.000,4.65,22.0,5.80,10.43
1465,2014-10-25,73.5,50.5,62.5,13.0,40.5,51.5,2.5,0.0,0.0,NaN,0.0,0.000,29.240,29.925,10.05,28.5,10.65,10.40
1466,2014-10-26,65.0,43.0,54.0,5.0,32.5,44.5,11.0,0.0,0.0,NaN,0.0,0.000,29.245,29.950,1.25,8.0,5.60,10.37
1467,2014-10-27,78.0,52.5,65.5,16.0,51.5,58.5,0.5,1.0,0.0,NaN,0.0,0.010,28.960,29.665,12.35,19.0,13.25,10.35
1468,2014-10-28,67.0,46.5,57.0,10.0,39.0,47.5,8.0,0.0,0.0,NaN,0.0,0.030,29.190,29.850,14.40,26.0,15.10,10.32
1469,2014-10-29,49.0,38.0,44.0,-4.0,33.0,41.0,21.0,0.0,0.0,NaN,0.0,0.000,29.390,30.065,9.00,29.0,9.45,10.30
1470,2014-10-30,52.0,34.5,43.5,-4.0,34.5,41.0,21.5,0.0,0.0,NaN,0.0,0.000,29.375,30.095,5.50,23.5,6.00,10.27
1471,2014-10-31,48.0,33.5,41.0,-6.0,27.0,34.5,24.0,0.0,0.0,NaN,0.1,0.035,29.515,30.200,22.15,34.0,22.75,10.24

### Combining the DFs
Combining the __Weather__ and __Train__ on 'Date' column

In [29]:
# Setting the index for concatenation
test.set_index('Date', inplace=True)
weather.set_index('Date', inplace=True)

In [30]:
df = pd.concat([test, weather], axis=1, join='inner')
df

,Id,Address,Species,Block,Street,Trap,AddressNumberAndStreet,Latitude,Longitude,AddressAccuracy,Tmax,Tmin,Tavg,Depart,DewPoint,WetBulb,Heat,Cool,Depth,Water1,SnowFall,PrecipTotal,StnPressure,SeaLevel,ResultSpeed,ResultDir,AvgSpeed,Daylight
Date,,,,,,,,,,,,,,,,,,,,,,,,,,,,
2008-06-11,1,"4100 North Oak Park Avenue, Chicago, IL 60634,...",CULEX PIPIENS/RESTUANS,41,N OAK PARK AVE,T002,"4100 N OAK PARK AVE, Chicago, IL",41.954690,-87.800991,9,86.0,63.5,75.0,7.0,55.5,64.0,0.0,10.0,0.0,NaN,0.0,0.00,29.310,29.98,9.15,18.0,10.2,15.10
2008-06-11,2,"4100 North Oak Park Avenue, Chicago, IL 60634,...",CULEX RESTUANS,41,N OAK PARK AVE,T002,"4100 N OAK PARK AVE, Chicago, IL",41.954690,-87.800991,9,86.0,63.5,75.0,7.0,55.5,64.0,0.0,10.0,0.0,NaN,0.0,0.00,29.310,29.98,9.15,18.0,10.2,15.10
2008-06-11,3,"4100 North Oak Park Avenue, Chicago, IL 60634,...",CULEX PIPIENS,41,N OAK PARK AVE,T002,"4100 N OAK PARK AVE, Chicago, IL",41.954690,-87.800991,9,86.0,63.5,75.0,7.0,55.5,64.0,0.0,10.0,0.0,NaN,0.0,0.00,29.310,29.98,9.15,18.0,10.2,15.10
2008-06-11,4,"4100 North Oak Park Avenue, Chicago, IL 60634,...",CULEX SALINARIUS,41,N OAK PARK AVE,T002,"4100 N OAK PARK AVE, Chicago, IL",41.954690,-87.800991,9,86.0,63.5,75.0,7.0,55.5,64.0,0.0,10.0,0.0,NaN,0.0,0.00,29.310,29.98,9.15,18.0,10.2,15.10
2008-06-11,5,"4100 North Oak Park Avenue, Chicago, IL 60634,...",CULEX TERRITANS,41,N OAK PARK AVE,T002,"4100 N OAK PARK AVE, Chicago, IL",41.954690,-87.800991,9,86.0,63.5,75.0,7.0,55.5,64.0,0.0,10.0,0.0,NaN,0.0,0.00,29.310,29.98,9.15,18.0,10.2,15.10
2008-06-11,6,"4100 North Oak Park Avenue, Chicago, IL 60634,...",CULEX TARSALIS,41,N OAK PARK AVE,T002,"4100 N OAK PARK AVE, Chicago, IL",41.954690,-87.800991,9,86.0,63.5,75.0,7.0,55.5,64.0,0.0,10.0,0.0,NaN,0.0,0.00,29.310,29.98,9.15,18.0,10.2,15.10
2008-06-11,7,"4100 North Oak Park Avenue, Chicago, IL 60634,...",UNSPECIFIED CULEX,41,N OAK PARK AVE,T002,"4100 N OAK PARK AVE, Chicago, IL",41.954690,-87.800991,9,86.0,63.5,75.0,7.0,55.5,64.0,0.0,10.0,0.0,NaN,0.0,0.00,29.310,29.98,9.15,18.0,10.2,15.10
2008-06-11,8,"4100 North Oak Park Avenue, Chicago, IL 60634,...",CULEX ERRATICUS,41,N OAK PARK AVE,T002,"4100 N OAK PARK AVE, Chicago, IL",41.954690,-87.800991,9,86.0,63.5,75.0,7.0,55.5,64.0,0.0,10.0,0.0,NaN,0.0,0.00,29.310,29.98,9.15,18.0,10.2,15.10
2008-06-11,9,"6200 North Mandell Avenue, Chicago, IL 60646, USA",CULEX PIPIENS/RESTUANS,62,N MANDELL AVE,T007,"6200 N MANDELL AVE, Chicago, IL",41.994991,-87.769279,9,86.0,63.5,75.0,7.0,55.5,64.0,0.0,10.0,0.0,NaN,0.0,0.00,29.310,29.98,9.15,18.0,10.2,15.10
2008-06-11,10,"6200 North Mandell Avenue, Chicago, IL 60646, USA",CULEX RESTUANS,62,N MANDELL AVE,T007,"6200 N MANDELL AVE, Chicago, IL",41.994991,-87.769279,9,86.0,63.5,75.0,7.0,55.5,64.0,0.0,10.0,0.0,NaN,0.0,0.00,29.310,29.98,9.15,18.0,10.2,15.10
2008-06-11,11,"6200 North Mandell Avenue, Chicago, IL 60646, USA",CULEX PIPIENS,62,N MANDELL AVE,T007,"6200 N MANDELL AVE, Chicago, IL",41.994991,-87.769279,9,86.0,63.5,75.0,7.0,55.5,64.0,0.0,10.0,0.0,NaN,0.0,0.00,29.310,29.98,9.15,18.0,10.2,15.10
2008-06-11,12,"6200 North Mandell Avenue, Chicago, IL 60646, USA",CULEX SALINARIUS,62,N MANDELL AVE,T007,"6200 N MANDELL AVE, Chicago, IL",41.994991,-87.769279,9,86.0,63.5,75.0,7.0,55.5,64.0,0.0,10.0,0.0,NaN,0.0,0.00,29.310,29.98,9.15,18.0,10.2,15.10
2008-06-11,13,"6200 North Mandell Avenue, Chicago, IL 60646, USA",CULEX TERRITANS,62,N MANDELL AVE,T007,"6200 N MANDELL AVE, Chicago, IL",41.994991,-87.769279,9,86.0,63.5,75.0,7.0,55.5,64.0,0.0,10.0,0.0,NaN,0.0,0.00,29.310,29.98,9.15,18.0,10.2,15.10
2008-06-11,14,"6200 North Mandell Avenue, Chicago, IL 60646, USA",CULEX TARSALIS,62,N MANDELL AVE,T007,"6200 N MANDELL AVE, Chicago, IL",41.994991,-87.769279,9,86.0,63.5,75.0,7.0,55.5,64.0,0.0,10.0,0.0,NaN,0.0,0.00,29.310,29.98,9.15,18.0,10.2,15.10
2008-06-11,15,"6200 North Mandell Avenue, Chicago, IL 60646, USA",UNSPECIFIED CULEX,62,N MANDELL AVE,T007,"6200 N MANDELL AVE, Chicago, IL",41.994991,-87.769279,9,86.0,63.5,75.0,7.0,55.5,64.0,0.0,10.0,0.0,NaN,0.0,0.00,29.310,29.98,9.15,18.0,10.2,15.10
2008-06-11,16,"6200 North Mandell Avenue, Chicago, IL 60646, USA",CULEX ERRATICUS,62,N MANDELL AVE,T007,"6200 N MANDELL AVE, Chicago, IL",41.994991,-87.769279,9,86.0,63.5,75.0,7.0,55.5,64.0,0.0,10.0,0.0,NaN,0.0,0.00,29.310,29.98,9.15,18.0,10.2,15.10
2008-06-11,17,"7900 West Foster Avenue, Chicago, IL 60656, USA",CULEX PIPIENS/RESTUANS,79,W FOSTER AVE,T015,"7900 W FOSTER AVE, Chicago, IL",41.974089,-87.824812,8,86.0,63.5,75.0,7.0,55.5,64.0,0.0,10.0,0.0,NaN,0.0,0.00,29.310,29.98,9.15,18.0,10.2,15.10
2008-06-11,18,"7900 West Foster Avenue, Chicago, IL 60656, USA",CULEX RESTUANS,79,W FOSTER AVE,T015,"7900 W FOSTER AVE, Chicago, IL",41.974089,-87.824812,8,86.0,63.5,75.0,7.0,55.5,64.0,0.0,10.0,0.0,NaN,0.0,0.00,29.310,29.98,9.15,18.0,10.2,15.10
2008-06-11,19,"7900 West Foster Avenue, Chicago, IL 60656, USA",CULEX PIPIENS,79,W FOSTER AVE,T015,"7900 W FOSTER AVE, Chicago, IL",41.974089,-87.824812,8,86.0,63.5,75.0,7.0,55.5,64.0,0.0,10.0,0.0,NaN,0.0,0.00,29.310,29.98,9.15,18.0,10.2,15.10
2008-06-11,20,"7900 West Foster Avenue, Chicago, IL 60656, USA",CULEX SALINARIUS,79,W FOSTER AVE,T015,"7900 W FOSTER AVE, Chicago, IL",41.974089,-87.824812,8,86.0,63.5,75.0,7.0,55.5,64.0,0.0,10.0,0.0,NaN,0.0,0.00,29.310,29.98,9.15,18.0,10.2,15.10
2008-06-11,21,"7900 West Foster Avenue, Chicago, IL 60656, USA",CULEX TERRITANS,79,W FOSTER AVE,T015,"7900 W FOSTER AVE, Chicago, IL",41.974089,-87.824812,8,86.0,63.5,75.0,7.0,55.5,64.0,0.0,10.0,0.0,NaN,0.0,0.00,29.310,29.98,9.15,18.0,10.2,15.10
2008-06-11,22,"7900 West Foster Avenue, Chicago, IL 60656, USA",CULEX TARSALIS,79,W FOSTER AVE,T015,"7900 W FOSTER AVE, Chicago, IL",41.974089,-87.824812,8,86.0,63.5,75.0,7.0,55.5,64.0,0.0,10.0,0.0,NaN,0.0,0.00,29.310,29.98,9.15,18.0,10.2,15.10
2008-06-11,23,"7900 West Foster Avenue, Chicago, IL 60656, USA",UNSPECIFIED CULEX,79,W FOSTER AVE,T015,"7900 W FOSTER AVE, Chicago, IL",41.974089,-87.824812,8,86.0,63.5,75.0,7.0,55.5,64.0,0.0,10.0,0.0,NaN,0.0,0.00,29.310,29.98,9.15,18.0,10.2,15.10
2008-06-11,24,"7900 West Foster Avenue, Chicago, IL 60656, USA",CULEX ERRATICUS,79,W FOSTER AVE,T015,"7900 W FOSTER AVE, Chicago, IL",41.974089,-87.824812,8,86.0,63.5,75.0,7.0,55.5,64.0,0.0,10.0,0.0,NaN,0.0,0.00,29.310,29.98,9.15,18.0,10.2,15.10
2008-06-11,25,"1500 West Webster Avenue, Chicago, IL 60614, USA",CULEX PIPIENS/RESTUANS,15,W WEBSTER AVE,T045,"1500 W WEBSTER AVE, Chicago, IL",41.921600,-87.666455,8,86.0,63.5,75.0,7.0,55.5,64.0,0.0,10.0,0.0,NaN,0.0,0.00,29.310,29.98,9.15,18.0,10.2,15.10
2008-06-11,26,"1500 West Webster Avenue, Chicago, IL 60614, USA",CULEX RESTUANS,15,W WEBSTER AVE,T045,"1500 W WEBSTER AVE, Chicago, IL",41.921600,-87.666455,8,86.0,63.5,75.0,7.0,55.5,64.0,0.0,10.0,0.0,NaN,0.0,0.00,29.310,29.98,9.15,18.0,10.2,15.10
2008-06-11,27,"1500 West Webster Avenue, Chicago, IL 60614, USA",CULEX PIPIENS,15,W WEBSTER AVE,T045,"1500 W WEBSTER AVE, Chicago, IL",41.921600,-87.666455,8,86.0,63.5,75.0,7.0,55.5,64.0,0.0,10.0,0.0,NaN,0.0,0.00,29.310,29.98,9.15,18.0,10.2,15.10
2008-06-11,28,"1500 West Webster Avenue, Chicago, IL 60614, USA",CULEX SALINARIUS,15,W WEBSTER AVE,T045,"1500 W WEBSTER AVE, Chicago, IL",41.921600,-87.666455,8,86.0,63.5,75.0,7.0,55.5,64.0,0.0,10.0,0.0,NaN,0.0,0.00,29.310,29.98,9.15,18.0,10.2,15.10
2008-06-11,29,"1500 West Webster Avenue, Chicago, IL 60614, USA",CULEX TERRITANS,15,W WEBSTER AVE,T045,"1500 W WEBSTER AVE, Chicago, IL",41.921600,-87.666455,8,86.0,63.5,75.0,7.0,55.5,64.0,0.0,10.0,0.0,NaN,0.0,0.00,29.310,29.98,9.15,18.0,10.2,15.10
2008-06-11,30,"1500 West Webster Avenue, Chicago, IL 60614, USA",CULEX TARSALIS,15,W WEBSTER AVE,T045,"1500 W WEBSTER AVE, Chicago, IL",41.921600,-87.666455,8,86.0,63.5,75.0,7.0,55.5,64.0,0.0,10.0,0.0,NaN,0.0,0.00,29.310,29.98,9.15,18.0,10.2,15.10
2008-06-11,31,"1500 West Webster Avenue, Chicago, IL 60614, USA",UNSPECIFIED CULEX,15,W WEBSTER AVE,T045,"1500 W WEBSTER AVE, Chicago, IL",41.921600,-87.666455,8,86.0,63.5,75.0,7.0,55.5,64.0,0.0,10.0,0.0,NaN,0.0,0.00,29.310,29.98,9.15,18.0,10.2,15.10
2008-06-11,32,"1500 West Webster Avenue, Chicago, IL 60614, USA",CULEX ERRATICUS,15,W WEBSTER AVE,T045,"1500 W WEBSTER AVE, Chicago, IL",41.921600,-87.666455,8,86.0,63.5,75.0,7.0,55.5,64.0,0.0,10.0,0.0,NaN,0.0,0.00,29.310,29.98,9.15,18.0,10.2,15.10
2008-06-11,33,"2500 West Grand Avenue, Chicago, IL 60654, USA",CULEX PIPIENS/RESTUANS,25,W GRAND AVE,T046,"2500 W GRAND AVE, Chicago, IL",41.891118,-87.654491,8,86.0,63.5,75.0,7.0,55.5,64.0,0.0,10.0,0.0,NaN,0.0,0.00,29.310,29.98,9.15,18.0,10.2,15.10
2008-06-11,34,"2500 West Grand Avenue, Chicago, IL 60654, USA",CULEX RESTUANS,25,W GRAND AVE,T046,"2500 W GRAND AVE, Chicago, IL",41.891118,-87.654491,8,86.0,63.5,75.0,7.0,55.5,64.0,0.0,10.0,0.0,NaN,0.0,0.00,29.310,29.98,9.15,18.0,10.2,15.10
2008-06-11,35,"2500 West Grand Avenue, Chicago, IL 60654, USA",CULEX PIPIENS,25,W GRAND AVE,T046,"2500 W GRAND AVE, Chicago, IL",41.891118,-87.654491,8,86.0,63.5,75.0,7.0,55.5,64.0,0.0,10.0,0.0,NaN,0.0,0.00,29.310,29.98,9.15,18.0,10.2,15.10
2008-06-11,36,"2500 West Grand Avenue, Chicago, IL 60654, USA",CULEX SALINARIUS,25,W GRAND AVE,T046,"2500 W GRAND AVE, Chicago, IL",41.891118,-87.654491,8,86.0,63.5,75.0,7.0,55.5,64.0,0.0,10.0,0.0,NaN,0.0,0.00,29.310,29.98,9.15,18.0,10.2,15.10
2008-06-11,37,"2500 West Grand Avenue, Chicago, IL 60654, USA",CULEX TERRITANS,25,W GRAND AVE,T046,"2500 W GRAND AVE, Chicago, IL",41.891118,-87.654491,8,86.0,63.5,75.0,7.0,55.5,64.0,0.0,10.0,0.0,NaN,0.0,0.00,29.310,29.98,9.15,18.0,10.2,15.10
2008-06-11,38,"2500 West Grand Avenue, Chicago, IL 60654, USA",CULEX TARSALIS,25,W GRAND AVE,T046,"2500 W GRAND AVE, Chicago, IL",41.891118,-87.654491,8,86.0,63.5,75.0,7.0,55.5,64.0,0.0,10.0,0.0,NaN,0.0,0.00,29.310,29.98,9.15,18.0,10.2,15.10
2008-06-11,39,"2500 West Grand Avenue, Chicago, IL 60654, USA",UNSPECIFIED CULEX,25,W GRAND AVE,T046,"2500 W GRAND AVE, Chicago, IL",41.891118,-87.654491,8,86.0,63.5,75.0,7.0,55.5,64.0,0.0,10.0,0.0,NaN,0.0,0.00,29.310,29.98,9.15,18.0,10.2,15.10
2008-06-11,40,"2500 West Grand Avenue, Chicago, IL 60654, USA",CULEX ERRATICUS,25,W GRAND AVE,T046,"2500 W GRAND AVE, Chicago, IL",41.891118,-87.654491,8,86.0,63.5,75.0,7.0,55.5,64.0,0.0,10.0,0.0,NaN,0.0,0.00,29.310,29.98,9.15,18.0,10.2,15.10
2008-06-11,41,"1100 Roosevelt Road, Chicago, IL 60608, USA",CULEX PIPIENS/RESTUANS,11,W ROOSEVELT,T048,"1100 W ROOSEVELT, Chicago, IL",41.867108,-87.654224,8,86.0,63.5,75.0,7.0,55.5,64.0,0.0,10.0,0.0,NaN,0.0,0.00,29.310,29.98,9.15,18.0,10.2,15.10
2008-06-11,42,"1100 Roosevelt Road, Chicago, IL 60608, USA",CULEX RESTUANS,11,W ROOSEVELT,T048,"1100 W ROOSEVELT, Chicago, IL",41.867108,-87.654224,8,86.0,63.5,75.0,7.0,55.5,64.0,0.0,10.0,0.0,NaN,0.0,0.00,29.310,29.98,9.15,18.0,10.2,15.10
2008-06-11,43,"1100 Roosevelt Road, Chicago, IL 60608, USA",CULEX PIPIENS,11,W ROOSEVELT,T048,"1100 W ROOSEVELT, Chicago, IL",41.867108,-87.654224,8,86.0,63.5,75.0,7.0,55.5,64.0,0.0,10.0,0.0,NaN,0.0,0.00,29.310,29.98,9.15,18.0,10.2,15.10
2008-06-11,44,"1100 Roosevelt Road, Chicago, IL 60608, USA",CULEX SALINARIUS,11,W ROOSEVELT,T048,"1100 W ROOSEVELT, Chicago, IL",41.867108,-87.654224,8,86.0,63.5,75.0,7.0,55.5,64.0,0.0,10.0,0.0,NaN,0.0,0.00,29.310,29.98,9.15,18.0,10.2,15.10
2008-06-11,45,"1100 Roosevelt Road, Chicago, IL 60608, USA",CULEX TERRITANS,11,W ROOSEVELT,T048,"1100 W ROOSEVELT, Chicago, IL",41.867108,-87.654224,8,86.0,63.5,75.0,7.0,55.5,64.0,0.0,10.0,0.0,NaN,0.0,0.00,29.310,29.98,9.15,18.0,10.2,15.10
2008-06-11,46,"1100 Roosevelt Road, Chicago, IL 60608, USA",CULEX TARSALIS,11,W ROOSEVELT,T048,"1100 W ROOSEVELT, Chicago, IL",41.867108,-87.654224,8,86.0,63.5,75.0,7.0,55.5,64.0,0.0,10.0,0.0,NaN,0.0,0.00,29.310,29.98,9.15,18.0,10.2,15.10
2008-06-11,47,"1100 Roosevelt Road, Chicago, IL 60608, USA",UNSPECIFIED CULEX,11,W ROOSEVELT,T048,"1100 W ROOSEVELT, Chicago, IL",41.867108,-87.654224,8,86.0,63.5,75.0,7.0,55.5,64.0,0.0,10.0,0.0,NaN,0.0,0.00,29.310,29.98,9.15,18.0,10.2,15.10
2008-06-11,48,"1100 Roosevelt Road, Chicago, IL 60608, USA",CULEX ERRATICUS,11,W ROOSEVELT,T048,"1100 W ROOSEVELT, Chicago, IL",41.867108,-87.654224,8,86.0,63.5,75.0,7.0,55.5,64.0,0.0,10.0,0.0,NaN,0.0,0.00,29.310,29.98,9.15,18.0,10.2,15.10
2008-06-11,49,"1100 West Chicago Avenue, Chicago, IL 60642, USA",CULEX PIPIENS/RESTUANS,11,W CHICAGO,T049,"1100 W CHICAGO, Chicago, IL",41.896282,-87.655232,8,86.0,63.5,75.0,7.0,55.5,64.0,0.0,10.0,0.0,NaN,0.0,0.00,29.310,29.98,9.15,18.0,10.2,15.10
2008-06-11,50,"1100 West Chicago Avenue, Chicago, IL 60642, USA",CULEX RESTUANS,11,W CHICAGO,T049,"1100 W CHICAGO, Chicago, IL",41.896282,-87.655232,8,86.0,63.5,75.0,7.0,55.5,64.0,0.0,10.0,0.0,NaN,0.0,0.00,29.310,29.98,9.15,18.0,10.2,15.10
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2014-10-02,116244,"4200 West 65th Street, Chicago, IL 60621, USA",UNSPECIFIED CULEX,42,W 65TH ST,T235,"4200 W 65TH ST, Chicago, IL",41.776428,-87.627096,8,73.5,64.5,69.5,10.0,62.0,64.0,0.0,4.5,0.0,NaN,0.0,0.52,29.065,29.78,7.20,17.0,7.9,11.83
2014-10-02,116245,"4200 West 65th Street, Chicago, IL 60621, USA",CULEX ERRATICUS,42,W 65TH ST,T235,"4200 W 65TH ST, Chicago, IL",41.776428,-87.627096,8,73.5,64.5,69.5,10.0,62.0,64.0,0.0,4.5,0.0,NaN,0.0,0.52,29.065,29.78,7.20,17.0,7.9,11.83
2014-10-02,116246,"6200 North Mcclellan Avenue, Chicago, IL 60646...",CULEX PIPIENS/RESTUANS,62,N MCCLELLAN AVE,T236,"6200 N MCCLELLAN AVE, Chicago, IL",41.994679,-87.770899,8,73.5,64.5,69.5,10.0,62.0,64.0,0.0,4.5,0.0,NaN,0.0,0.52,29.065,29.78,7.20,17.0,7.9,11.83
2014-10-02,116247,"6200 North Mcclellan Avenue, Chicago, IL 60646...",CULEX RESTUANS,62,N MCCLELLAN AVE,T236,"6200 N MCCLELLAN AVE, Chicago, IL",41.994679,-87.770899,8,73.5,64.5,69.5,10.0,62.0,64.0,0.0,4.5,0.0,NaN,0.0,0.52,29.065,29.78,7.20,17.0,7.9,11.83
2014-10-02,116248,"6200 North Mcclellan Avenue, Chicago, IL 60646...",CULEX PIPIENS,62,N MCCLELLAN AVE,T236,"6200 N MCCLELLAN AVE, Chicago, IL",41.994679,-87.770899,8,73.5,64.5,69.5,10.0,62.0,64.0,0.0,4.5,0.0,NaN,0.0,0.52,29.065,29.78,7.20,17.0,7.9,11.83
2014-10-02,116249,"6200 North Mcclellan Avenue, Chicago, IL 60646...",CULEX SALINARIUS,62,N MCCLELLAN AVE,T236,"6200 N MCCLELLAN AVE, Chicago, IL",41.994679,-87.770899,8,73.5,64.5,69.5,10.0,62.0,64.0,0.0,4.5,0.0,NaN,0.0,0.52,29.065,29.78,7.20,17.0,7.9,11.83
2014-10-02,116250,"6200 North Mcclellan Avenue, Chicago, IL 60646...",CULEX TERRITANS,62,N MCCLELLAN AVE,T236,"6200 N MCCLELLAN AVE, Chicago, IL",41.994679,-87.770899,8,73.5,64.5,69.5,10.0,62.0,64.0,0.0,4.5,0.0,NaN,0.0,0.52,29.065,29.78,7.20,17.0,7.9,11.83
2014-10-02,116251,"6200 North Mcclellan Avenue, Chicago, IL 60646...",CULEX TARSALIS,62,N MCCLELLAN AVE,T236,"6200 N MCCLELLAN AVE, Chicago, IL",41.994679,-87.770899,8,73.5,64.5,69.5,10.0,62.0,64.0,0.0,4.5,0.0,NaN,0.0,0.52,29.065,29.78,7.20,17.0,7.9,11.83
2014-10-02,116252,"6200 North Mcclellan Avenue, Chicago, IL 60646...",UNSPECIFIED CULEX,62,N MCCLELLAN AVE,T236,"6200 N MCCLELLAN AVE, Chicago, IL",41.994679,-87.770899,8,73.5,64.5,69.5,10.0,62.0,64.0,0.0,4.5,0.0,NaN,0.0,0.52,29.065,29.78,7.20,17.0,7.9,11.83
2014-10-02,116253,"6200 North Mcclellan Avenue, Chicago, IL 60646...",CULEX ERRATICUS,62,N MCCLELLAN AVE,T236,"6200 N MCCLELLAN AVE, Chicago, IL",41.994679,-87.770899,8,73.5,64.5,69.5,10.0,62.0,64.0,0.0,4.5,0.0,NaN,0.0,0.52,29.065,29.78,7.20,17.0,7.9,11.83
2014-10-02,116254,"2900 West 85th Street, Chicago, IL 60652, USA",CULEX PIPIENS/RESTUANS,29,W 85TH ST,T237,"2900 W 85TH ST, Chicago, IL",41.738903,-87.695443,8,73.5,64.5,69.5,10.0,62.0,64.0,0.0,4.5,0.0,NaN,0.0,0.52,29.065,29.78,7.20,17.0,7.9,11.83
2014-10-02,116255,"2900 West 85th Street, Chicago, IL 60652, USA",CULEX RESTUANS,29,W 85TH ST,T237,"2900 W 85TH ST, Chicago, IL",41.738903,-87.695443,8,73.5,64.5,69.5,10.0,62.0,64.0,0.0,4.5,0.0,NaN,0.0,0.52,29.065,29.78,7.20,17.0,7.9,11.83
2014-10-02,116256,"2900 West 85th Street, Chicago, IL 60652, USA",CULEX PIPIENS,29,W 85TH ST,T237,"2900 W 85TH ST, Chicago, IL",41.738903,-87.695443,8,73.5,64.5,69.5,10.0,62.0,64.0,0.0,4.5,0.0,NaN,0.0,0.52,29.065,29.78,7.20,17.0,7.9,11.83
2014-10-02,116257,"2900 West 85th Street, Chicago, IL 60652, USA",CULEX SALINARIUS,29,W 85TH ST,T237,"2900 W 85TH ST, Chicago, IL",41.738903,-87.695443,8,73.5,64.5,69.5,10.0,62.0,64.0,0.0,4.5,0.0,NaN,0.0,0.52,29.065,29.78,7.20,17.0,7.9,11.83
2014-10-02,116258,"2900 West 85th Street, Chicago, IL 60652, USA",CULEX TERRITANS,29,W 85TH ST,T237,"2900 W 85TH ST, Chicago, IL",41.738903,-87.695443,8,73.5,64.5,69.5,10.0,62.0,64.0,0.0,4.5,0.0,NaN,0.0,0.52,29.065,29.78,7.20,17.0,7.9,11.83
2014-10-02,116259,"2900 West 85th Street, Chicago, IL 60652, USA",CULEX TARSALIS,29,W 85TH ST,T237,"2900 W 85TH ST, Chicago, IL",41.738903,-87.695443,8,73.5,64.5,69.5,10.0,62.0,64.0,0.0,4.5,0.0,NaN,0.0,0.52,29.065,29.78,7.20,17.0,7.9,11.83
2014-10-02,116260,"2900 West 85th Street, Chicago, IL 60652, USA",UNSPECIFIED CULEX,29,W 85TH ST,T237,"2900 W 85TH ST, Chicago, IL",41.738903,-87.695443,8,73.5,64.5,69.5,10.0,62.0,64.0,0.0,4.5,0.0,NaN,0.0,0.52,29.065,29.78,7.20,17.0,7.9,11.83
2014-10-02,116261,"2900 West 85th Street, Chicago, IL 60652, USA",CULEX ERRATICUS,29,W 85TH ST,T237,"2900 W 85TH ST, Chicago, IL",41.738903,-87.695443,8,73.5,64.5,69.5,10.0,62.0,64.0,0.0,4.5,0.0,NaN,0.0,0.52,29.065,29.78,7.20,17.0,7.9,11.83
2014-10-02,116262,"3400 West 77th Street, Chicago, IL 60652, USA",CULEX PIPIENS/RESTUANS,34,W 77TH ST,T238,"3400 W 77TH ST, Chicago, IL",41.753391,-87.707394,8,73.5,64.5,69.5,10.0,62.0,64.0,0.0,4.5,0.0,NaN,0.0,0.52,29.065,29.78,7.20,17.0,7.9,11.83
2014-10-02,116263,"3400 West 77th Street, Chicago, IL 60652, USA",CULEX RESTUANS,34,W 77TH ST,T238,"3400 W 77TH ST, Chicago, IL",41.753391,-87.707394,8,73.5,64.5,69.5,10.0,62.0,64.0,0.0,4.5,0.0,NaN,0.0,0.52,29.065,29.78,7.20,17.0,7.9,11.83
2014-10-02,116264,"3400 West 77th Street, Chicago, IL 60652, USA",CULEX PIPIENS,34,W 77TH ST,T238,"3400 W 77TH ST, Chicago, IL",41.753391,-87.707394,8,73.5,64.5,69.5,10.0,62.0,64.0,0.0,4.5,0.0,NaN,0.0,0.52,29.065,29.78,7.20,17.0,7.9,11.83
2014-10-02,116265,"3400 West 77th Street, Chicago, IL 60652, USA",CULEX SALINARIUS,34,W 77TH ST,T238,"3400 W 77TH ST, Chicago, IL",41.753391,-87.707394,8,73.5,64.5,69.5,10.0,62.0,64.0,0.0,4.5,0.0,NaN,0.0,0.52,29.065,29.78,7.20,17.0,7.9,11.83
2014-10-02,116266,"3400 West 77th Street, Chicago, IL 60652, USA",CULEX TERRITANS,34,W 77TH ST,T238,"3400 W 77TH ST, Chicago, IL",41.753391,-87.707394,8,73.5,64.5,69.5,10.0,62.0,64.0,0.0,4.5,0.0,NaN,0.0,0.52,29.065,29.78,7.20,17.0,7.9,11.83
2014-10-02,116267,"3400 West 77th Street, Chicago, IL 60652, USA",CULEX TARSALIS,34,W 77TH ST,T238,"3400 W 77TH ST, Chicago, IL",41.753391,-87.707394,8,73.5,64.5,69.5,10.0,62.0,64.0,0.0,4.5,0.0,NaN,0.0,0.52,29.065,29.78,7.20,17.0,7.9,11.83
2014-10-02,116268,"3400 West 77th Street, Chicago, IL 60652, USA",UNSPECIFIED CULEX,34,W 77TH ST,T238,"3400 W 77TH ST, Chicago, IL",41.753391,-87.707394,8,73.5,64.5,69.5,10.0,62.0,64.0,0.0,4.5,0.0,NaN,0.0,0.52,29.065,29.78,7.20,17.0,7.9,11.83
2014-10-02,116269,"3400 West 77th Street, Chicago, IL 60652, USA",CULEX ERRATICUS,34,W 77TH ST,T238,"3400 W 77TH ST, Chicago, IL",41.753391,-87.707394,8,73.5,64.5,69.5,10.0,62.0,64.0,0.0,4.5,0.0,NaN,0.0,0.52,29.065,29.78,7.20,17.0,7.9,11.83
2014-10-02,116270,"5100 West 63rd Place, Chicago, IL 60638, USA",CULEX PIPIENS/RESTUANS,51,W 63RD PL,T065A,"5100 W 63RD PL, Chicago, IL",41.777689,-87.749149,9,73.5,64.5,69.5,10.0,62.0,64.0,0.0,4.5,0.0,NaN,0.0,0.52,29.065,29.78,7.20,17.0,7.9,11.83
2014-10-02,116271,"5100 West 63rd Place, Chicago, IL 60638, USA",CULEX RESTUANS,51,W 63RD PL,T065A,"5100 W 63RD PL, Chicago, IL",41.777689,-87.749149,9,73.5,64.5,69.5,10.0,62.0,64.0,0.0,4.5,0.0,NaN,0.0,0.52,29.065,29.78,7.20,17.0,7.9,11.83
2014-10-02,116272,"5100 West 63rd Place, Chicago, IL 60638, USA",CULEX PIPIENS,51,W 63RD PL,T065A,"5100 W 63RD PL, Chicago, IL",41.777689,-87.749149,9,73.5,64.5,69.5,10.0,62.0,64.0,0.0,4.5,0.0,NaN,0.0,0.52,29.065,29.78,7.20,17.0,7.9,11.83

### Dropping Unnecessary Columns
Since we are given the latitude and longitude, addresses and related columns are not needed.

In [31]:
df.drop(['Address', 'Block', 'Street', 'AddressNumberAndStreet', 'AddressAccuracy'], axis = 1, inplace=True)
df

,Id,Species,Trap,Latitude,Longitude,Tmax,Tmin,Tavg,Depart,DewPoint,WetBulb,Heat,Cool,Depth,Water1,SnowFall,PrecipTotal,StnPressure,SeaLevel,ResultSpeed,ResultDir,AvgSpeed,Daylight
Date,,,,,,,,,,,,,,,,,,,,,,,
2008-06-11,1,CULEX PIPIENS/RESTUANS,T002,41.954690,-87.800991,86.0,63.5,75.0,7.0,55.5,64.0,0.0,10.0,0.0,NaN,0.0,0.00,29.310,29.98,9.15,18.0,10.2,15.10
2008-06-11,2,CULEX RESTUANS,T002,41.954690,-87.800991,86.0,63.5,75.0,7.0,55.5,64.0,0.0,10.0,0.0,NaN,0.0,0.00,29.310,29.98,9.15,18.0,10.2,15.10
2008-06-11,3,CULEX PIPIENS,T002,41.954690,-87.800991,86.0,63.5,75.0,7.0,55.5,64.0,0.0,10.0,0.0,NaN,0.0,0.00,29.310,29.98,9.15,18.0,10.2,15.10
2008-06-11,4,CULEX SALINARIUS,T002,41.954690,-87.800991,86.0,63.5,75.0,7.0,55.5,64.0,0.0,10.0,0.0,NaN,0.0,0.00,29.310,29.98,9.15,18.0,10.2,15.10
2008-06-11,5,CULEX TERRITANS,T002,41.954690,-87.800991,86.0,63.5,75.0,7.0,55.5,64.0,0.0,10.0,0.0,NaN,0.0,0.00,29.310,29.98,9.15,18.0,10.2,15.10
2008-06-11,6,CULEX TARSALIS,T002,41.954690,-87.800991,86.0,63.5,75.0,7.0,55.5,64.0,0.0,10.0,0.0,NaN,0.0,0.00,29.310,29.98,9.15,18.0,10.2,15.10
2008-06-11,7,UNSPECIFIED CULEX,T002,41.954690,-87.800991,86.0,63.5,75.0,7.0,55.5,64.0,0.0,10.0,0.0,NaN,0.0,0.00,29.310,29.98,9.15,18.0,10.2,15.10
2008-06-11,8,CULEX ERRATICUS,T002,41.954690,-87.800991,86.0,63.5,75.0,7.0,55.5,64.0,0.0,10.0,0.0,NaN,0.0,0.00,29.310,29.98,9.15,18.0,10.2,15.10
2008-06-11,9,CULEX PIPIENS/RESTUANS,T007,41.994991,-87.769279,86.0,63.5,75.0,7.0,55.5,64.0,0.0,10.0,0.0,NaN,0.0,0.00,29.310,29.98,9.15,18.0,10.2,15.10
2008-06-11,10,CULEX RESTUANS,T007,41.994991,-87.769279,86.0,63.5,75.0,7.0,55.5,64.0,0.0,10.0,0.0,NaN,0.0,0.00,29.310,29.98,9.15,18.0,10.2,15.10
2008-06-11,11,CULEX PIPIENS,T007,41.994991,-87.769279,86.0,63.5,75.0,7.0,55.5,64.0,0.0,10.0,0.0,NaN,0.0,0.00,29.310,29.98,9.15,18.0,10.2,15.10
2008-06-11,12,CULEX SALINARIUS,T007,41.994991,-87.769279,86.0,63.5,75.0,7.0,55.5,64.0,0.0,10.0,0.0,NaN,0.0,0.00,29.310,29.98,9.15,18.0,10.2,15.10
2008-06-11,13,CULEX TERRITANS,T007,41.994991,-87.769279,86.0,63.5,75.0,7.0,55.5,64.0,0.0,10.0,0.0,NaN,0.0,0.00,29.310,29.98,9.15,18.0,10.2,15.10
2008-06-11,14,CULEX TARSALIS,T007,41.994991,-87.769279,86.0,63.5,75.0,7.0,55.5,64.0,0.0,10.0,0.0,NaN,0.0,0.00,29.310,29.98,9.15,18.0,10.2,15.10
2008-06-11,15,UNSPECIFIED CULEX,T007,41.994991,-87.769279,86.0,63.5,75.0,7.0,55.5,64.0,0.0,10.0,0.0,NaN,0.0,0.00,29.310,29.98,9.15,18.0,10.2,15.10
2008-06-11,16,CULEX ERRATICUS,T007,41.994991,-87.769279,86.0,63.5,75.0,7.0,55.5,64.0,0.0,10.0,0.0,NaN,0.0,0.00,29.310,29.98,9.15,18.0,10.2,15.10
2008-06-11,17,CULEX PIPIENS/RESTUANS,T015,41.974089,-87.824812,86.0,63.5,75.0,7.0,55.5,64.0,0.0,10.0,0.0,NaN,0.0,0.00,29.310,29.98,9.15,18.0,10.2,15.10
2008-06-11,18,CULEX RESTUANS,T015,41.974089,-87.824812,86.0,63.5,75.0,7.0,55.5,64.0,0.0,10.0,0.0,NaN,0.0,0.00,29.310,29.98,9.15,18.0,10.2,15.10
2008-06-11,19,CULEX PIPIENS,T015,41.974089,-87.824812,86.0,63.5,75.0,7.0,55.5,64.0,0.0,10.0,0.0,NaN,0.0,0.00,29.310,29.98,9.15,18.0,10.2,15.10
2008-06-11,20,CULEX SALINARIUS,T015,41.974089,-87.824812,86.0,63.5,75.0,7.0,55.5,64.0,0.0,10.0,0.0,NaN,0.0,0.00,29.310,29.98,9.15,18.0,10.2,15.10
2008-06-11,21,CULEX TERRITANS,T015,41.974089,-87.824812,86.0,63.5,75.0,7.0,55.5,64.0,0.0,10.0,0.0,NaN,0.0,0.00,29.310,29.98,9.15,18.0,10.2,15.10
2008-06-11,22,CULEX TARSALIS,T015,41.974089,-87.824812,86.0,63.5,75.0,7.0,55.5,64.0,0.0,10.0,0.0,NaN,0.0,0.00,29.310,29.98,9.15,18.0,10.2,15.10
2008-06-11,23,UNSPECIFIED CULEX,T015,41.974089,-87.824812,86.0,63.5,75.0,7.0,55.5,64.0,0.0,10.0,0.0,NaN,0.0,0.00,29.310,29.98,9.15,18.0,10.2,15.10
2008-06-11,24,CULEX ERRATICUS,T015,41.974089,-87.824812,86.0,63.5,75.0,7.0,55.5,64.0,0.0,10.0,0.0,NaN,0.0,0.00,29.310,29.98,9.15,18.0,10.2,15.10
2008-06-11,25,CULEX PIPIENS/RESTUANS,T045,41.921600,-87.666455,86.0,63.5,75.0,7.0,55.5,64.0,0.0,10.0,0.0,NaN,0.0,0.00,29.310,29.98,9.15,18.0,10.2,15.10
2008-06-11,26,CULEX RESTUANS,T045,41.921600,-87.666455,86.0,63.5,75.0,7.0,55.5,64.0,0.0,10.0,0.0,NaN,0.0,0.00,29.310,29.98,9.15,18.0,10.2,15.10
2008-06-11,27,CULEX PIPIENS,T045,41.921600,-87.666455,86.0,63.5,75.0,7.0,55.5,64.0,0.0,10.0,0.0,NaN,0.0,0.00,29.310,29.98,9.15,18.0,10.2,15.10
2008-06-11,28,CULEX SALINARIUS,T045,41.921600,-87.666455,86.0,63.5,75.0,7.0,55.5,64.0,0.0,10.0,0.0,NaN,0.0,0.00,29.310,29.98,9.15,18.0,10.2,15.10
2008-06-11,29,CULEX TERRITANS,T045,41.921600,-87.666455,86.0,63.5,75.0,7.0,55.5,64.0,0.0,10.0,0.0,NaN,0.0,0.00,29.310,29.98,9.15,18.0,10.2,15.10
2008-06-11,30,CULEX TARSALIS,T045,41.921600,-87.666455,86.0,63.5,75.0,7.0,55.5,64.0,0.0,10.0,0.0,NaN,0.0,0.00,29.310,29.98,9.15,18.0,10.2,15.10
2008-06-11,31,UNSPECIFIED CULEX,T045,41.921600,-87.666455,86.0,63.5,75.0,7.0,55.5,64.0,0.0,10.0,0.0,NaN,0.0,0.00,29.310,29.98,9.15,18.0,10.2,15.10
2008-06-11,32,CULEX ERRATICUS,T045,41.921600,-87.666455,86.0,63.5,75.0,7.0,55.5,64.0,0.0,10.0,0.0,NaN,0.0,0.00,29.310,29.98,9.15,18.0,10.2,15.10
2008-06-11,33,CULEX PIPIENS/RESTUANS,T046,41.891118,-87.654491,86.0,63.5,75.0,7.0,55.5,64.0,0.0,10.0,0.0,NaN,0.0,0.00,29.310,29.98,9.15,18.0,10.2,15.10
2008-06-11,34,CULEX RESTUANS,T046,41.891118,-87.654491,86.0,63.5,75.0,7.0,55.5,64.0,0.0,10.0,0.0,NaN,0.0,0.00,29.310,29.98,9.15,18.0,10.2,15.10
2008-06-11,35,CULEX PIPIENS,T046,41.891118,-87.654491,86.0,63.5,75.0,7.0,55.5,64.0,0.0,10.0,0.0,NaN,0.0,0.00,29.310,29.98,9.15,18.0,10.2,15.10
2008-06-11,36,CULEX SALINARIUS,T046,41.891118,-87.654491,86.0,63.5,75.0,7.0,55.5,64.0,0.0,10.0,0.0,NaN,0.0,0.00,29.310,29.98,9.15,18.0,10.2,15.10
2008-06-11,37,CULEX TERRITANS,T046,41.891118,-87.654491,86.0,63.5,75.0,7.0,55.5,64.0,0.0,10.0,0.0,NaN,0.0,0.00,29.310,29.98,9.15,18.0,10.2,15.10
2008-06-11,38,CULEX TARSALIS,T046,41.891118,-87.654491,86.0,63.5,75.0,7.0,55.5,64.0,0.0,10.0,0.0,NaN,0.0,0.00,29.310,29.98,9.15,18.0,10.2,15.10
2008-06-11,39,UNSPECIFIED CULEX,T046,41.891118,-87.654491,86.0,63.5,75.0,7.0,55.5,64.0,0.0,10.0,0.0,NaN,0.0,0.00,29.310,29.98,9.15,18.0,10.2,15.10
2008-06-11,40,CULEX ERRATICUS,T046,41.891118,-87.654491,86.0,63.5,75.0,7.0,55.5,64.0,0.0,10.0,0.0,NaN,0.0,0.00,29.310,29.98,9.15,18.0,10.2,15.10
2008-06-11,41,CULEX PIPIENS/RESTUANS,T048,41.867108,-87.654224,86.0,63.5,75.0,7.0,55.5,64.0,0.0,10.0,0.0,NaN,0.0,0.00,29.310,29.98,9.15,18.0,10.2,15.10
2008-06-11,42,CULEX RESTUANS,T048,41.867108,-87.654224,86.0,63.5,75.0,7.0,55.5,64.0,0.0,10.0,0.0,NaN,0.0,0.00,29.310,29.98,9.15,18.0,10.2,15.10
2008-06-11,43,CULEX PIPIENS,T048,41.867108,-87.654224,86.0,63.5,75.0,7.0,55.5,64.0,0.0,10.0,0.0,NaN,0.0,0.00,29.310,29.98,9.15,18.0,10.2,15.10
2008-06-11,44,CULEX SALINARIUS,T048,41.867108,-87.654224,86.0,63.5,75.0,7.0,55.5,64.0,0.0,10.0,0.0,NaN,0.0,0.00,29.310,29.98,9.15,18.0,10.2,15.10
2008-06-11,45,CULEX TERRITANS,T048,41.867108,-87.654224,86.0,63.5,75.0,7.0,55.5,64.0,0.0,10.0,0.0,NaN,0.0,0.00,29.310,29.98,9.15,18.0,10.2,15.10
2008-06-11,46,CULEX TARSALIS,T048,41.867108,-87.654224,86.0,63.5,75.0,7.0,55.5,64.0,0.0,10.0,0.0,NaN,0.0,0.00,29.310,29.98,9.15,18.0,10.2,15.10
2008-06-11,47,UNSPECIFIED CULEX,T048,41.867108,-87.654224,86.0,63.5,75.0,7.0,55.5,64.0,0.0,10.0,0.0,NaN,0.0,0.00,29.310,29.98,9.15,18.0,10.2,15.10
2008-06-11,48,CULEX ERRATICUS,T048,41.867108,-87.654224,86.0,63.5,75.0,7.0,55.5,64.0,0.0,10.0,0.0,NaN,0.0,0.00,29.310,29.98,9.15,18.0,10.2,15.10
2008-06-11,49,CULEX PIPIENS/RESTUANS,T049,41.896282,-87.655232,86.0,63.5,75.0,7.0,55.5,64.0,0.0,10.0,0.0,NaN,0.0,0.00,29.310,29.98,9.15,18.0,10.2,15.10
2008-06-11,50,CULEX RESTUANS,T049,41.896282,-87.655232,86.0,63.5,75.0,7.0,55.5,64.0,0.0,10.0,0.0,NaN,0.0,0.00,29.310,29.98,9.15,18.0,10.2,15.10
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2014-10-02,116244,UNSPECIFIED CULEX,T235,41.776428,-87.627096,73.5,64.5,69.5,10.0,62.0,64.0,0.0,4.5,0.0,NaN,0.0,0.52,29.065,29.78,7.20,17.0,7.9,11.83
2014-10-02,116245,CULEX ERRATICUS,T235,41.776428,-87.627096,73.5,64.5,69.5,10.0,62.0,64.0,0.0,4.5,0.0,NaN,0.0,0.52,29.065,29.78,7.20,17.0,7.9,11.83
2014-10-02,116246,CULEX PIPIENS/RESTUANS,T236,41.994679,-87.770899,73.5,64.5,69.5,10.0,62.0,64.0,0.0,4.5,0.0,NaN,0.0,0.52,29.065,29.78,7.20,17.0,7.9,11.83
2014-10-02,116247,CULEX RESTUANS,T236,41.994679,-87.770899,73.5,64.5,69.5,10.0,62.0,64.0,0.0,4.5,0.0,NaN,0.0,0.52,29.065,29.78,7.20,17.0,7.9,11.83
2014-10-02,116248,CULEX PIPIENS,T236,41.994679,-87.770899,73.5,64.5,69.5,10.0,62.0,64.0,0.0,4.5,0.0,NaN,0.0,0.52,29.065,29.78,7.20,17.0,7.9,11.83
2014-10-02,116249,CULEX SALINARIUS,T236,41.994679,-87.770899,73.5,64.5,69.5,10.0,62.0,64.0,0.0,4.5,0.0,NaN,0.0,0.52,29.065,29.78,7.20,17.0,7.9,11.83
2014-10-02,116250,CULEX TERRITANS,T236,41.994679,-87.770899,73.5,64.5,69.5,10.0,62.0,64.0,0.0,4.5,0.0,NaN,0.0,0.52,29.065,29.78,7.20,17.0,7.9,11.83
2014-10-02,116251,CULEX TARSALIS,T236,41.994679,-87.770899,73.5,64.5,69.5,10.0,62.0,64.0,0.0,4.5,0.0,NaN,0.0,0.52,29.065,29.78,7.20,17.0,7.9,11.83
2014-10-02,116252,UNSPECIFIED CULEX,T236,41.994679,-87.770899,73.5,64.5,69.5,10.0,62.0,64.0,0.0,4.5,0.0,NaN,0.0,0.52,29.065,29.78,7.20,17.0,7.9,11.83
2014-10-02,116253,CULEX ERRATICUS,T236,41.994679,-87.770899,73.5,64.5,69.5,10.0,62.0,64.0,0.0,4.5,0.0,NaN,0.0,0.52,29.065,29.78,7.20,17.0,7.9,11.83
2014-10-02,116254,CULEX PIPIENS/RESTUANS,T237,41.738903,-87.695443,73.5,64.5,69.5,10.0,62.0,64.0,0.0,4.5,0.0,NaN,0.0,0.52,29.065,29.78,7.20,17.0,7.9,11.83
2014-10-02,116255,CULEX RESTUANS,T237,41.738903,-87.695443,73.5,64.5,69.5,10.0,62.0,64.0,0.0,4.5,0.0,NaN,0.0,0.52,29.065,29.78,7.20,17.0,7.9,11.83
2014-10-02,116256,CULEX PIPIENS,T237,41.738903,-87.695443,73.5,64.5,69.5,10.0,62.0,64.0,0.0,4.5,0.0,NaN,0.0,0.52,29.065,29.78,7.20,17.0,7.9,11.83
2014-10-02,116257,CULEX SALINARIUS,T237,41.738903,-87.695443,73.5,64.5,69.5,10.0,62.0,64.0,0.0,4.5,0.0,NaN,0.0,0.52,29.065,29.78,7.20,17.0,7.9,11.83
2014-10-02,116258,CULEX TERRITANS,T237,41.738903,-87.695443,73.5,64.5,69.5,10.0,62.0,64.0,0.0,4.5,0.0,NaN,0.0,0.52,29.065,29.78,7.20,17.0,7.9,11.83
2014-10-02,116259,CULEX TARSALIS,T237,41.738903,-87.695443,73.5,64.5,69.5,10.0,62.0,64.0,0.0,4.5,0.0,NaN,0.0,0.52,29.065,29.78,7.20,17.0,7.9,11.83
2014-10-02,116260,UNSPECIFIED CULEX,T237,41.738903,-87.695443,73.5,64.5,69.5,10.0,62.0,64.0,0.0,4.5,0.0,NaN,0.0,0.52,29.065,29.78,7.20,17.0,7.9,11.83
2014-10-02,116261,CULEX ERRATICUS,T237,41.738903,-87.695443,73.5,64.5,69.5,10.0,62.0,64.0,0.0,4.5,0.0,NaN,0.0,0.52,29.065,29.78,7.20,17.0,7.9,11.83
2014-10-02,116262,CULEX PIPIENS/RESTUANS,T238,41.753391,-87.707394,73.5,64.5,69.5,10.0,62.0,64.0,0.0,4.5,0.0,NaN,0.0,0.52,29.065,29.78,7.20,17.0,7.9,11.83
2014-10-02,116263,CULEX RESTUANS,T238,41.753391,-87.707394,73.5,64.5,69.5,10.0,62.0,64.0,0.0,4.5,0.0,NaN,0.0,0.52,29.065,29.78,7.20,17.0,7.9,11.83
2014-10-02,116264,CULEX PIPIENS,T238,41.753391,-87.707394,73.5,64.5,69.5,10.0,62.0,64.0,0.0,4.5,0.0,NaN,0.0,0.52,29.065,29.78,7.20,17.0,7.9,11.83
2014-10-02,116265,CULEX SALINARIUS,T238,41.753391,-87.707394,73.5,64.5,69.5,10.0,62.0,64.0,0.0,4.5,0.0,NaN,0.0,0.52,29.065,29.78,7.20,17.0,7.9,11.83
2014-10-02,116266,CULEX TERRITANS,T238,41.753391,-87.707394,73.5,64.5,69.5,10.0,62.0,64.0,0.0,4.5,0.0,NaN,0.0,0.52,29.065,29.78,7.20,17.0,7.9,11.83
2014-10-02,116267,CULEX TARSALIS,T238,41.753391,-87.707394,73.5,64.5,69.5,10.0,62.0,64.0,0.0,4.5,0.0,NaN,0.0,0.52,29.065,29.78,7.20,17.0,7.9,11.83
2014-10-02,116268,UNSPECIFIED CULEX,T238,41.753391,-87.707394,73.5,64.5,69.5,10.0,62.0,64.0,0.0,4.5,0.0,NaN,0.0,0.52,29.065,29.78,7.20,17.0,7.9,11.83
2014-10-02,116269,CULEX ERRATICUS,T238,41.753391,-87.707394,73.5,64.5,69.5,10.0,62.0,64.0,0.0,4.5,0.0,NaN,0.0,0.52,29.065,29.78,7.20,17.0,7.9,11.83
2014-10-02,116270,CULEX PIPIENS/RESTUANS,T065A,41.777689,-87.749149,73.5,64.5,69.5,10.0,62.0,64.0,0.0,4.5,0.0,NaN,0.0,0.52,29.065,29.78,7.20,17.0,7.9,11.83
2014-10-02,116271,CULEX RESTUANS,T065A,41.777689,-87.749149,73.5,64.5,69.5,10.0,62.0,64.0,0.0,4.5,0.0,NaN,0.0,0.52,29.065,29.78,7.20,17.0,7.9,11.83
2014-10-02,116272,CULEX PIPIENS,T065A,41.777689,-87.749149,73.5,64.5,69.5,10.0,62.0,64.0,0.0,4.5,0.0,NaN,0.0,0.52,29.065,29.78,7.20,17.0,7.9,11.83
2014-10-02,116273,CULEX SALINARIUS,T065A,41.777689,-87.749149,73.5,64.5,69.5,10.0,62.0,64.0,0.0,4.5,0.0,NaN,0.0,0.52,29.065,29.78,7.20,17.0,7.9,11.83
2014-10-02,116274,CULEX TERRITANS,T065A,41.777689,-87.749149,73.5,64.5,69.5,10.0,62.0,64.0,0.0,4.5,0.0,NaN,0.0,0.52,29.065,29.78,7.20,17.0,7.9,11.83
2014-10-02,116275,CULEX TARSALIS,T065A,41.777689,-87.749149,73.5,64.5,69.5,10.0,62.0,64.0,0.0,4.5,0.0,NaN,0.0,0.52,29.065,29.78,7.20,17.0,7.9,11.83
2014-10-02,116276,UNSPECIFIED CULEX,T065A,41.777689,-87.749149,73.5,64.5,69.5,10.0,62.0,64.0,0.0,4.5,0.0,NaN,0.0,0.52,29.065,29.78,7.20,17.0,7.9,11.83
2014-10-02,116277,CULEX ERRATICUS,T065A,41.777689,-87.749149,73.5,64.5,69.5,10.0,62.0,64.0,0.0,4.5,0.0,NaN,0.0,0.52,29.065,29.78,7.20,17.0,7.9,11.83
2014-10-02,116278,CULEX PIPIENS/RESTUANS,T094B,41.719140,-87.669539,73.5,64.5,69.5,10.0,62.0,64.0,0.0,4.5,0.0,NaN,0.0,0.52,29.065,29.78,7.20,17.0,7.9,11.83
2014-10-02,116279,CULEX RESTUANS,T094B,41.719140,-87.669539,73.5,64.5,69.5,10.0,62.0,64.0,0.0,4.5,0.0,NaN,0.0,0.52,29.065,29.78,7.20,17.0,7.9,11.83
2014-10-02,116280,CULEX PIPIENS,T094B,41.719140,-87.669539,73.5,64.5,69.5,10.0,62.0,64.0,0.0,4.5,0.0,NaN,0.0,0.52,29.065,29.78,7.20,17.0,7.9,11.83
2014-10-02,116281,CULEX SALINARIUS,T094B,41.719140,-87.669539,73.5,64.5,69.5,10.0,62.0,64.0,0.0,4.5,0.0,NaN,0.0,0.52,29.065,29.78,7.20,17.0,7.9,11.83
2014-10-02,116282,CULEX TERRITANS,T094B,41.719140,-87.669539,73.5,64.5,69.5,10.0,62.0,64.0,0.0,4.5,0.0,NaN,0.0,0.52,29.065,29.78,7.20,17.0,7.9,11.83
2014-10-02,116283,CULEX TARSALIS,T094B,41.719140,-87.669539,73.5,64.5,69.5,10.0,62.0,64.0,0.0,4.5,0.0,NaN,0.0,0.52,29.065,29.78,7.20,17.0,7.9,11.83
2014-10-02,116284,UNSPECIFIED CULEX,T094B,41.719140,-87.669539,73.5,64.5,69.5,10.0,62.0,64.0,0.0,4.5,0.0,NaN,0.0,0.52,29.065,29.78,7.20,17.0,7.9,11.83
2014-10-02,116285,CULEX ERRATICUS,T094B,41.719140,-87.669539,73.5,64.5,69.5,10.0,62.0,64.0,0.0,4.5,0.0,NaN,0.0,0.52,29.065,29.78,7.20,17.0,7.9,11.83
2014-10-02,116286,CULEX PIPIENS/RESTUANS,T054C,41.925652,-87.633590,73.5,64.5,69.5,10.0,62.0,64.0,0.0,4.5,0.0,NaN,0.0,0.52,29.065,29.78,7.20,17.0,7.9,11.83
2014-10-02,116287,CULEX RESTUANS,T054C,41.925652,-87.633590,73.5,64.5,69.5,10.0,62.0,64.0,0.0,4.5,0.0,NaN,0.0,0.52,29.065,29.78,7.20,17.0,7.9,11.83
2014-10-02,116288,CULEX PIPIENS,T054C,41.925652,-87.633590,73.5,64.5,69.5,10.0,62.0,64.0,0.0,4.5,0.0,NaN,0.0,0.52,29.065,29.78,7.20,17.0,7.9,11.83
2014-10-02,116289,CULEX SALINARIUS,T054C,41.925652,-87.633590,73.5,64.5,69.5,10.0,62.0,64.0,0.0,4.5,0.0,NaN,0.0,0.52,29.065,29.78,7.20,17.0,7.9,11.83
2014-10-02,116290,CULEX TERRITANS,T054C,41.925652,-87.633590,73.5,64.5,69.5,10.0,62.0,64.0,0.0,4.5,0.0,NaN,0.0,0.52,29.065,29.78,7.20,17.0,7.9,11.83
2014-10-02,116291,CULEX TARSALIS,T054C,41.925652,-87.633590,73.5,64.5,69.5,10.0,62.0,64.0,0.0,4.5,0.0,NaN,0.0,0.52,29.065,29.78,7.20,17.0,7.9,11.83
2014-10-02,116292,UNSPECIFIED CULEX,T054C,41.925652,-87.633590,73.5,64.5,69.5,10.0,62.0,64.0,0.0,4.5,0.0,NaN,0.0,0.52,29.065,29.78,7.20,17.0,7.9,11.83
2014-10-02,116293,CULEX ERRATICUS,T054C,41.925652,-87.633590,73.5,64.5,69.5,10.0,62.0,64.0,0.0,4.5,0.0,NaN,0.0,0.52,29.065,29.78,7.20,17.0,7.9,11.83

### Resetting the Index
For a new feature detailing the month

In [32]:
df.reset_index(inplace=True)
df

,Date,Id,Species,Trap,Latitude,Longitude,Tmax,Tmin,Tavg,Depart,DewPoint,WetBulb,Heat,Cool,Depth,Water1,SnowFall,PrecipTotal,StnPressure,SeaLevel,ResultSpeed,ResultDir,AvgSpeed,Daylight
0,2008-06-11,1,CULEX PIPIENS/RESTUANS,T002,41.954690,-87.800991,86.0,63.5,75.0,7.0,55.5,64.0,0.0,10.0,0.0,NaN,0.0,0.00,29.310,29.98,9.15,18.0,10.2,15.10
1,2008-06-11,2,CULEX RESTUANS,T002,41.954690,-87.800991,86.0,63.5,75.0,7.0,55.5,64.0,0.0,10.0,0.0,NaN,0.0,0.00,29.310,29.98,9.15,18.0,10.2,15.10
2,2008-06-11,3,CULEX PIPIENS,T002,41.954690,-87.800991,86.0,63.5,75.0,7.0,55.5,64.0,0.0,10.0,0.0,NaN,0.0,0.00,29.310,29.98,9.15,18.0,10.2,15.10
3,2008-06-11,4,CULEX SALINARIUS,T002,41.954690,-87.800991,86.0,63.5,75.0,7.0,55.5,64.0,0.0,10.0,0.0,NaN,0.0,0.00,29.310,29.98,9.15,18.0,10.2,15.10
4,2008-06-11,5,CULEX TERRITANS,T002,41.954690,-87.800991,86.0,63.5,75.0,7.0,55.5,64.0,0.0,10.0,0.0,NaN,0.0,0.00,29.310,29.98,9.15,18.0,10.2,15.10
5,2008-06-11,6,CULEX TARSALIS,T002,41.954690,-87.800991,86.0,63.5,75.0,7.0,55.5,64.0,0.0,10.0,0.0,NaN,0.0,0.00,29.310,29.98,9.15,18.0,10.2,15.10
6,2008-06-11,7,UNSPECIFIED CULEX,T002,41.954690,-87.800991,86.0,63.5,75.0,7.0,55.5,64.0,0.0,10.0,0.0,NaN,0.0,0.00,29.310,29.98,9.15,18.0,10.2,15.10
7,2008-06-11,8,CULEX ERRATICUS,T002,41.954690,-87.800991,86.0,63.5,75.0,7.0,55.5,64.0,0.0,10.0,0.0,NaN,0.0,0.00,29.310,29.98,9.15,18.0,10.2,15.10
8,2008-06-11,9,CULEX PIPIENS/RESTUANS,T007,41.994991,-87.769279,86.0,63.5,75.0,7.0,55.5,64.0,0.0,10.0,0.0,NaN,0.0,0.00,29.310,29.98,9.15,18.0,10.2,15.10
9,2008-06-11,10,CULEX RESTUANS,T007,41.994991,-87.769279,86.0,63.5,75.0,7.0,55.5,64.0,0.0,10.0,0.0,NaN,0.0,0.00,29.310,29.98,9.15,18.0,10.2,15.10
10,2008-06-11,11,CULEX PIPIENS,T007,41.994991,-87.769279,86.0,63.5,75.0,7.0,55.5,64.0,0.0,10.0,0.0,NaN,0.0,0.00,29.310,29.98,9.15,18.0,10.2,15.10
11,2008-06-11,12,CULEX SALINARIUS,T007,41.994991,-87.769279,86.0,63.5,75.0,7.0,55.5,64.0,0.0,10.0,0.0,NaN,0.0,0.00,29.310,29.98,9.15,18.0,10.2,15.10
12,2008-06-11,13,CULEX TERRITANS,T007,41.994991,-87.769279,86.0,63.5,75.0,7.0,55.5,64.0,0.0,10.0,0.0,NaN,0.0,0.00,29.310,29.98,9.15,18.0,10.2,15.10
13,2008-06-11,14,CULEX TARSALIS,T007,41.994991,-87.769279,86.0,63.5,75.0,7.0,55.5,64.0,0.0,10.0,0.0,NaN,0.0,0.00,29.310,29.98,9.15,18.0,10.2,15.10
14,2008-06-11,15,UNSPECIFIED CULEX,T007,41.994991,-87.769279,86.0,63.5,75.0,7.0,55.5,64.0,0.0,10.0,0.0,NaN,0.0,0.00,29.310,29.98,9.15,18.0,10.2,15.10
15,2008-06-11,16,CULEX ERRATICUS,T007,41.994991,-87.769279,86.0,63.5,75.0,7.0,55.5,64.0,0.0,10.0,0.0,NaN,0.0,0.00,29.310,29.98,9.15,18.0,10.2,15.10
16,2008-06-11,17,CULEX PIPIENS/RESTUANS,T015,41.974089,-87.824812,86.0,63.5,75.0,7.0,55.5,64.0,0.0,10.0,0.0,NaN,0.0,0.00,29.310,29.98,9.15,18.0,10.2,15.10
17,2008-06-11,18,CULEX RESTUANS,T015,41.974089,-87.824812,86.0,63.5,75.0,7.0,55.5,64.0,0.0,10.0,0.0,NaN,0.0,0.00,29.310,29.98,9.15,18.0,10.2,15.10
18,2008-06-11,19,CULEX PIPIENS,T015,41.974089,-87.824812,86.0,63.5,75.0,7.0,55.5,64.0,0.0,10.0,0.0,NaN,0.0,0.00,29.310,29.98,9.15,18.0,10.2,15.10
19,2008-06-11,20,CULEX SALINARIUS,T015,41.974089,-87.824812,86.0,63.5,75.0,7.0,55.5,64.0,0.0,10.0,0.0,NaN,0.0,0.00,29.310,29.98,9.15,18.0,10.2,15.10
20,2008-06-11,21,CULEX TERRITANS,T015,41.974089,-87.824812,86.0,63.5,75.0,7.0,55.5,64.0,0.0,10.0,0.0,NaN,0.0,0.00,29.310,29.98,9.15,18.0,10.2,15.10
21,2008-06-11,22,CULEX TARSALIS,T015,41.974089,-87.824812,86.0,63.5,75.0,7.0,55.5,64.0,0.0,10.0,0.0,NaN,0.0,0.00,29.310,29.98,9.15,18.0,10.2,15.10
22,2008-06-11,23,UNSPECIFIED CULEX,T015,41.974089,-87.824812,86.0,63.5,75.0,7.0,55.5,64.0,0.0,10.0,0.0,NaN,0.0,0.00,29.310,29.98,9.15,18.0,10.2,15.10
23,2008-06-11,24,CULEX ERRATICUS,T015,41.974089,-87.824812,86.0,63.5,75.0,7.0,55.5,64.0,0.0,10.0,0.0,NaN,0.0,0.00,29.310,29.98,9.15,18.0,10.2,15.10
24,2008-06-11,25,CULEX PIPIENS/RESTUANS,T045,41.921600,-87.666455,86.0,63.5,75.0,7.0,55.5,64.0,0.0,10.0,0.0,NaN,0.0,0.00,29.310,29.98,9.15,18.0,10.2,15.10
25,2008-06-11,26,CULEX RESTUANS,T045,41.921600,-87.666455,86.0,63.5,75.0,7.0,55.5,64.0,0.0,10.0,0.0,NaN,0.0,0.00,29.310,29.98,9.15,18.0,10.2,15.10
26,2008-06-11,27,CULEX PIPIENS,T045,41.921600,-87.666455,86.0,63.5,75.0,7.0,55.5,64.0,0.0,10.0,0.0,NaN,0.0,0.00,29.310,29.98,9.15,18.0,10.2,15.10
27,2008-06-11,28,CULEX SALINARIUS,T045,41.921600,-87.666455,86.0,63.5,75.0,7.0,55.5,64.0,0.0,10.0,0.0,NaN,0.0,0.00,29.310,29.98,9.15,18.0,10.2,15.10
28,2008-06-11,29,CULEX TERRITANS,T045,41.921600,-87.666455,86.0,63.5,75.0,7.0,55.5,64.0,0.0,10.0,0.0,NaN,0.0,0.00,29.310,29.98,9.15,18.0,10.2,15.10
29,2008-06-11,30,CULEX TARSALIS,T045,41.921600,-87.666455,86.0,63.5,75.0,7.0,55.5,64.0,0.0,10.0,0.0,NaN,0.0,0.00,29.310,29.98,9.15,18.0,10.2,15.10
30,2008-06-11,31,UNSPECIFIED CULEX,T045,41.921600,-87.666455,86.0,63.5,75.0,7.0,55.5,64.0,0.0,10.0,0.0,NaN,0.0,0.00,29.310,29.98,9.15,18.0,10.2,15.10
31,2008-06-11,32,CULEX ERRATICUS,T045,41.921600,-87.666455,86.0,63.5,75.0,7.0,55.5,64.0,0.0,10.0,0.0,NaN,0.0,0.00,29.310,29.98,9.15,18.0,10.2,15.10
32,2008-06-11,33,CULEX PIPIENS/RESTUANS,T046,41.891118,-87.654491,86.0,63.5,75.0,7.0,55.5,64.0,0.0,10.0,0.0,NaN,0.0,0.00,29.310,29.98,9.15,18.0,10.2,15.10
33,2008-06-11,34,CULEX RESTUANS,T046,41.891118,-87.654491,86.0,63.5,75.0,7.0,55.5,64.0,0.0,10.0,0.0,NaN,0.0,0.00,29.310,29.98,9.15,18.0,10.2,15.10
34,2008-06-11,35,CULEX PIPIENS,T046,41.891118,-87.654491,86.0,63.5,75.0,7.0,55.5,64.0,0.0,10.0,0.0,NaN,0.0,0.00,29.310,29.98,9.15,18.0,10.2,15.10
35,2008-06-11,36,CULEX SALINARIUS,T046,41.891118,-87.654491,86.0,63.5,75.0,7.0,55.5,64.0,0.0,10.0,0.0,NaN,0.0,0.00,29.310,29.98,9.15,18.0,10.2,15.10
36,2008-06-11,37,CULEX TERRITANS,T046,41.891118,-87.654491,86.0,63.5,75.0,7.0,55.5,64.0,0.0,10.0,0.0,NaN,0.0,0.00,29.310,29.98,9.15,18.0,10.2,15.10
37,2008-06-11,38,CULEX TARSALIS,T046,41.891118,-87.654491,86.0,63.5,75.0,7.0,55.5,64.0,0.0,10.0,0.0,NaN,0.0,0.00,29.310,29.98,9.15,18.0,10.2,15.10
38,2008-06-11,39,UNSPECIFIED CULEX,T046,41.891118,-87.654491,86.0,63.5,75.0,7.0,55.5,64.0,0.0,10.0,0.0,NaN,0.0,0.00,29.310,29.98,9.15,18.0,10.2,15.10
39,2008-06-11,40,CULEX ERRATICUS,T046,41.891118,-87.654491,86.0,63.5,75.0,7.0,55.5,64.0,0.0,10.0,0.0,NaN,0.0,0.00,29.310,29.98,9.15,18.0,10.2,15.10
40,2008-06-11,41,CULEX PIPIENS/RESTUANS,T048,41.867108,-87.654224,86.0,63.5,75.0,7.0,55.5,64.0,0.0,10.0,0.0,NaN,0.0,0.00,29.310,29.98,9.15,18.0,10.2,15.10
41,2008-06-11,42,CULEX RESTUANS,T048,41.867108,-87.654224,86.0,63.5,75.0,7.0,55.5,64.0,0.0,10.0,0.0,NaN,0.0,0.00,29.310,29.98,9.15,18.0,10.2,15.10
42,2008-06-11,43,CULEX PIPIENS,T048,41.867108,-87.654224,86.0,63.5,75.0,7.0,55.5,64.0,0.0,10.0,0.0,NaN,0.0,0.00,29.310,29.98,9.15,18.0,10.2,15.10
43,2008-06-11,44,CULEX SALINARIUS,T048,41.867108,-87.654224,86.0,63.5,75.0,7.0,55.5,64.0,0.0,10.0,0.0,NaN,0.0,0.00,29.310,29.98,9.15,18.0,10.2,15.10
44,2008-06-11,45,CULEX TERRITANS,T048,41.867108,-87.654224,86.0,63.5,75.0,7.0,55.5,64.0,0.0,10.0,0.0,NaN,0.0,0.00,29.310,29.98,9.15,18.0,10.2,15.10
45,2008-06-11,46,CULEX TARSALIS,T048,41.867108,-87.654224,86.0,63.5,75.0,7.0,55.5,64.0,0.0,10.0,0.0,NaN,0.0,0.00,29.310,29.98,9.15,18.0,10.2,15.10
46,2008-06-11,47,UNSPECIFIED CULEX,T048,41.867108,-87.654224,86.0,63.5,75.0,7.0,55.5,64.0,0.0,10.0,0.0,NaN,0.0,0.00,29.310,29.98,9.15,18.0,10.2,15.10
47,2008-06-11,48,CULEX ERRATICUS,T048,41.867108,-87.654224,86.0,63.5,75.0,7.0,55.5,64.0,0.0,10.0,0.0,NaN,0.0,0.00,29.310,29.98,9.15,18.0,10.2,15.10
48,2008-06-11,49,CULEX PIPIENS/RESTUANS,T049,41.896282,-87.655232,86.0,63.5,75.0,7.0,55.5,64.0,0.0,10.0,0.0,NaN,0.0,0.00,29.310,29.98,9.15,18.0,10.2,15.10
49,2008-06-11,50,CULEX RESTUANS,T049,41.896282,-87.655232,86.0,63.5,75.0,7.0,55.5,64.0,0.0,10.0,0.0,NaN,0.0,0.00,29.310,29.98,9.15,18.0,10.2,15.10
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
116243,2014-10-02,116244,UNSPECIFIED CULEX,T235,41.776428,-87.627096,73.5,64.5,69.5,10.0,62.0,64.0,0.0,4.5,0.0,NaN,0.0,0.52,29.065,29.78,7.20,17.0,7.9,11.83
116244,2014-10-02,116245,CULEX ERRATICUS,T235,41.776428,-87.627096,73.5,64.5,69.5,10.0,62.0,64.0,0.0,4.5,0.0,NaN,0.0,0.52,29.065,29.78,7.20,17.0,7.9,11.83
116245,2014-10-02,116246,CULEX PIPIENS/RESTUANS,T236,41.994679,-87.770899,73.5,64.5,69.5,10.0,62.0,64.0,0.0,4.5,0.0,NaN,0.0,0.52,29.065,29.78,7.20,17.0,7.9,11.83
116246,2014-10-02,116247,CULEX RESTUANS,T236,41.994679,-87.770899,73.5,64.5,69.5,10.0,62.0,64.0,0.0,4.5,0.0,NaN,0.0,0.52,29.065,29.78,7.20,17.0,7.9,11.83
116247,2014-10-02,116248,CULEX PIPIENS,T236,41.994679,-87.770899,73.5,64.5,69.5,10.0,62.0,64.0,0.0,4.5,0.0,NaN,0.0,0.52,29.065,29.78,7.20,17.0,7.9,11.83
116248,2014-10-02,116249,CULEX SALINARIUS,T236,41.994679,-87.770899,73.5,64.5,69.5,10.0,62.0,64.0,0.0,4.5,0.0,NaN,0.0,0.52,29.065,29.78,7.20,17.0,7.9,11.83
116249,2014-10-02,116250,CULEX TERRITANS,T236,41.994679,-87.770899,73.5,64.5,69.5,10.0,62.0,64.0,0.0,4.5,0.0,NaN,0.0,0.52,29.065,29.78,7.20,17.0,7.9,11.83
116250,2014-10-02,116251,CULEX TARSALIS,T236,41.994679,-87.770899,73.5,64.5,69.5,10.0,62.0,64.0,0.0,4.5,0.0,NaN,0.0,0.52,29.065,29.78,7.20,17.0,7.9,11.83
116251,2014-10-02,116252,UNSPECIFIED CULEX,T236,41.994679,-87.770899,73.5,64.5,69.5,10.0,62.0,64.0,0.0,4.5,0.0,NaN,0.0,0.52,29.065,29.78,7.20,17.0,7.9,11.83
116252,2014-10-02,116253,CULEX ERRATICUS,T236,41.994679,-87.770899,73.5,64.5,69.5,10.0,62.0,64.0,0.0,4.5,0.0,NaN,0.0,0.52,29.065,29.78,7.20,17.0,7.9,11.83
116253,2014-10-02,116254,CULEX PIPIENS/RESTUANS,T237,41.738903,-87.695443,73.5,64.5,69.5,10.0,62.0,64.0,0.0,4.5,0.0,NaN,0.0,0.52,29.065,29.78,7.20,17.0,7.9,11.83
116254,2014-10-02,116255,CULEX RESTUANS,T237,41.738903,-87.695443,73.5,64.5,69.5,10.0,62.0,64.0,0.0,4.5,0.0,NaN,0.0,0.52,29.065,29.78,7.20,17.0,7.9,11.83
116255,2014-10-02,116256,CULEX PIPIENS,T237,41.738903,-87.695443,73.5,64.5,69.5,10.0,62.0,64.0,0.0,4.5,0.0,NaN,0.0,0.52,29.065,29.78,7.20,17.0,7.9,11.83
116256,2014-10-02,116257,CULEX SALINARIUS,T237,41.738903,-87.695443,73.5,64.5,69.5,10.0,62.0,64.0,0.0,4.5,0.0,NaN,0.0,0.52,29.065,29.78,7.20,17.0,7.9,11.83
116257,2014-10-02,116258,CULEX TERRITANS,T237,41.738903,-87.695443,73.5,64.5,69.5,10.0,62.0,64.0,0.0,4.5,0.0,NaN,0.0,0.52,29.065,29.78,7.20,17.0,7.9,11.83
116258,2014-10-02,116259,CULEX TARSALIS,T237,41.738903,-87.695443,73.5,64.5,69.5,10.0,62.0,64.0,0.0,4.5,0.0,NaN,0.0,0.52,29.065,29.78,7.20,17.0,7.9,11.83
116259,2014-10-02,116260,UNSPECIFIED CULEX,T237,41.738903,-87.695443,73.5,64.5,69.5,10.0,62.0,64.0,0.0,4.5,0.0,NaN,0.0,0.52,29.065,29.78,7.20,17.0,7.9,11.83
116260,2014-10-02,116261,CULEX ERRATICUS,T237,41.738903,-87.695443,73.5,64.5,69.5,10.0,62.0,64.0,0.0,4.5,0.0,NaN,0.0,0.52,29.065,29.78,7.20,17.0,7.9,11.83
116261,2014-10-02,116262,CULEX PIPIENS/RESTUANS,T238,41.753391,-87.707394,73.5,64.5,69.5,10.0,62.0,64.0,0.0,4.5,0.0,NaN,0.0,0.52,29.065,29.78,7.20,17.0,7.9,11.83
116262,2014-10-02,116263,CULEX RESTUANS,T238,41.753391,-87.707394,73.5,64.5,69.5,10.0,62.0,64.0,0.0,4.5,0.0,NaN,0.0,0.52,29.065,29.78,7.20,17.0,7.9,11.83
116263,2014-10-02,116264,CULEX PIPIENS,T238,41.753391,-87.707394,73.5,64.5,69.5,10.0,62.0,64.0,0.0,4.5,0.0,NaN,0.0,0.52,29.065,29.78,7.20,17.0,7.9,11.83
116264,2014-10-02,116265,CULEX SALINARIUS,T238,41.753391,-87.707394,73.5,64.5,69.5,10.0,62.0,64.0,0.0,4.5,0.0,NaN,0.0,0.52,29.065,29.78,7.20,17.0,7.9,11.83
116265,2014-10-02,116266,CULEX TERRITANS,T238,41.753391,-87.707394,73.5,64.5,69.5,10.0,62.0,64.0,0.0,4.5,0.0,NaN,0.0,0.52,29.065,29.78,7.20,17.0,7.9,11.83
116266,2014-10-02,116267,CULEX TARSALIS,T238,41.753391,-87.707394,73.5,64.5,69.5,10.0,62.0,64.0,0.0,4.5,0.0,NaN,0.0,0.52,29.065,29.78,7.20,17.0,7.9,11.83
116267,2014-10-02,116268,UNSPECIFIED CULEX,T238,41.753391,-87.707394,73.5,64.5,69.5,10.0,62.0,64.0,0.0,4.5,0.0,NaN,0.0,0.52,29.065,29.78,7.20,17.0,7.9,11.83
116268,2014-10-02,116269,CULEX ERRATICUS,T238,41.753391,-87.707394,73.5,64.5,69.5,10.0,62.0,64.0,0.0,4.5,0.0,NaN,0.0,0.52,29.065,29.78,7.20,17.0,7.9,11.83
116269,2014-10-02,116270,CULEX PIPIENS/RESTUANS,T065A,41.777689,-87.749149,73.5,64.5,69.5,10.0,62.0,64.0,0.0,4.5,0.0,NaN,0.0,0.52,29.065,29.78,7.20,17.0,7.9,11.83
116270,2014-10-02,116271,CULEX RESTUANS,T065A,41.777689,-87.749149,73.5,64.5,69.5,10.0,62.0,64.0,0.0,4.5,0.0,NaN,0.0,0.52,29.065,29.78,7.20,17.0,7.9,11.83
116271,2014-10-02,116272,CULEX PIPIENS,T065A,41.777689,-87.749149,73.5,64.5,69.5,10.0,62.0,64.0,0.0,4.5,0.0,NaN,0.0,0.52,29.065,29.78,7.20,17.0,7.9,11.83
116272,2014-10-02,116273,CULEX SALINARIUS,T065A,41.777689,-87.749149,73.5,64.5,69.5,10.0,62.0,64.0,0.0,4.5,0.0,NaN,0.0,0.52,29.065,29.78,7.20,17.0,7.9,11.83
116273,2014-10-02,116274,CULEX TERRITANS,T065A,41.777689,-87.749149,73.5,64.5,69.5,10.0,62.0,64.0,0.0,4.5,0.0,NaN,0.0,0.52,29.065,29.78,7.20,17.0,7.9,11.83
116274,2014-10-02,116275,CULEX TARSALIS,T065A,41.777689,-87.749149,73.5,64.5,69.5,10.0,62.0,64.0,0.0,4.5,0.0,NaN,0.0,0.52,29.065,29.78,7.20,17.0,7.9,11.83
116275,2014-10-02,116276,UNSPECIFIED CULEX,T065A,41.777689,-87.749149,73.5,64.5,69.5,10.0,62.0,64.0,0.0,4.5,0.0,NaN,0.0,0.52,29.065,29.78,7.20,17.0,7.9,11.83
116276,2014-10-02,116277,CULEX ERRATICUS,T065A,41.777689,-87.749149,73.5,64.5,69.5,10.0,62.0,64.0,0.0,4.5,0.0,NaN,0.0,0.52,29.065,29.78,7.20,17.0,7.9,11.83
116277,2014-10-02,116278,CULEX PIPIENS/RESTUANS,T094B,41.719140,-87.669539,73.5,64.5,69.5,10.0,62.0,64.0,0.0,4.5,0.0,NaN,0.0,0.52,29.065,29.78,7.20,17.0,7.9,11.83
116278,2014-10-02,116279,CULEX RESTUANS,T094B,41.719140,-87.669539,73.5,64.5,69.5,10.0,62.0,64.0,0.0,4.5,0.0,NaN,0.0,0.52,29.065,29.78,7.20,17.0,7.9,11.83
116279,2014-10-02,116280,CULEX PIPIENS,T094B,41.719140,-87.669539,73.5,64.5,69.5,10.0,62.0,64.0,0.0,4.5,0.0,NaN,0.0,0.52,29.065,29.78,7.20,17.0,7.9,11.83
116280,2014-10-02,116281,CULEX SALINARIUS,T094B,41.719140,-87.669539,73.5,64.5,69.5,10.0,62.0,64.0,0.0,4.5,0.0,NaN,0.0,0.52,29.065,29.78,7.20,17.0,7.9,11.83
116281,2014-10-02,116282,CULEX TERRITANS,T094B,41.719140,-87.669539,73.5,64.5,69.5,10.0,62.0,64.0,0.0,4.5,0.0,NaN,0.0,0.52,29.065,29.78,7.20,17.0,7.9,11.83
116282,2014-10-02,116283,CULEX TARSALIS,T094B,41.719140,-87.669539,73.5,64.5,69.5,10.0,62.0,64.0,0.0,4.5,0.0,NaN,0.0,0.52,29.065,29.78,7.20,17.0,7.9,11.83
116283,2014-10-02,116284,UNSPECIFIED CULEX,T094B,41.719140,-87.669539,73.5,64.5,69.5,10.0,62.0,64.0,0.0,4.5,0.0,NaN,0.0,0.52,29.065,29.78,7.20,17.0,7.9,11.83
116284,2014-10-02,116285,CULEX ERRATICUS,T094B,41.719140,-87.669539,73.5,64.5,69.5,10.0,62.0,64.0,0.0,4.5,0.0,NaN,0.0,0.52,29.065,29.78,7.20,17.0,7.9,11.83
116285,2014-10-02,116286,CULEX PIPIENS/RESTUANS,T054C,41.925652,-87.633590,73.5,64.5,69.5,10.0,62.0,64.0,0.0,4.5,0.0,NaN,0.0,0.52,29.065,29.78,7.20,17.0,7.9,11.83
116286,2014-10-02,116287,CULEX RESTUANS,T054C,41.925652,-87.633590,73.5,64.5,69.5,10.0,62.0,64.0,0.0,4.5,0.0,NaN,0.0,0.52,29.065,29.78,7.20,17.0,7.9,11.83
116287,2014-10-02,116288,CULEX PIPIENS,T054C,41.925652,-87.633590,73.5,64.5,69.5,10.0,62.0,64.0,0.0,4.5,0.0,NaN,0.0,0.52,29.065,29.78,7.20,17.0,7.9,11.83
116288,2014-10-02,116289,CULEX SALINARIUS,T054C,41.925652,-87.633590,73.5,64.5,69.5,10.0,62.0,64.0,0.0,4.5,0.0,NaN,0.0,0.52,29.065,29.78,7.20,17.0,7.9,11.83
116289,2014-10-02,116290,CULEX TERRITANS,T054C,41.925652,-87.633590,73.5,64.5,69.5,10.0,62.0,64.0,0.0,4.5,0.0,NaN,0.0,0.52,29.065,29.78,7.20,17.0,7.9,11.83
116290,2014-10-02,116291,CULEX TARSALIS,T054C,41.925652,-87.633590,73.5,64.5,69.5,10.0,62.0,64.0,0.0,4.5,0.0,NaN,0.0,0.52,29.065,29.78,7.20,17.0,7.9,11.83
116291,2014-10-02,116292,UNSPECIFIED CULEX,T054C,41.925652,-87.633590,73.5,64.5,69.5,10.0,62.0,64.0,0.0,4.5,0.0,NaN,0.0,0.52,29.065,29.78,7.20,17.0,7.9,11.83
116292,2014-10-02,116293,CULEX ERRATICUS,T054C,41.925652,-87.633590,73.5,64.5,69.5,10.0,62.0,64.0,0.0,4.5,0.0,NaN,0.0,0.52,29.065,29.78,7.20,17.0,7.9,11.83

### Creating a month column to replace 'Date'

In [33]:
df['Month'] = df['Date'].astype(str).str.slice(5,7).astype(float)

# Dropping the Date column
df.drop('Date', axis=1, inplace=True)

# Renaming the months from numbers
df['Month'] = df['Month'].replace({5:'May', 
                                   6:'June', 
                                   7:'July', 
                                   8:'Aug', 
                                   9:'Sept', 
                                   10:'Oct'})

# Viewing the new DF
df

,Id,Species,Trap,Latitude,Longitude,Tmax,Tmin,Tavg,Depart,DewPoint,WetBulb,Heat,Cool,Depth,Water1,SnowFall,PrecipTotal,StnPressure,SeaLevel,ResultSpeed,ResultDir,AvgSpeed,Daylight,Month
0,1,CULEX PIPIENS/RESTUANS,T002,41.954690,-87.800991,86.0,63.5,75.0,7.0,55.5,64.0,0.0,10.0,0.0,NaN,0.0,0.00,29.310,29.98,9.15,18.0,10.2,15.10,June
1,2,CULEX RESTUANS,T002,41.954690,-87.800991,86.0,63.5,75.0,7.0,55.5,64.0,0.0,10.0,0.0,NaN,0.0,0.00,29.310,29.98,9.15,18.0,10.2,15.10,June
2,3,CULEX PIPIENS,T002,41.954690,-87.800991,86.0,63.5,75.0,7.0,55.5,64.0,0.0,10.0,0.0,NaN,0.0,0.00,29.310,29.98,9.15,18.0,10.2,15.10,June
3,4,CULEX SALINARIUS,T002,41.954690,-87.800991,86.0,63.5,75.0,7.0,55.5,64.0,0.0,10.0,0.0,NaN,0.0,0.00,29.310,29.98,9.15,18.0,10.2,15.10,June
4,5,CULEX TERRITANS,T002,41.954690,-87.800991,86.0,63.5,75.0,7.0,55.5,64.0,0.0,10.0,0.0,NaN,0.0,0.00,29.310,29.98,9.15,18.0,10.2,15.10,June
5,6,CULEX TARSALIS,T002,41.954690,-87.800991,86.0,63.5,75.0,7.0,55.5,64.0,0.0,10.0,0.0,NaN,0.0,0.00,29.310,29.98,9.15,18.0,10.2,15.10,June
6,7,UNSPECIFIED CULEX,T002,41.954690,-87.800991,86.0,63.5,75.0,7.0,55.5,64.0,0.0,10.0,0.0,NaN,0.0,0.00,29.310,29.98,9.15,18.0,10.2,15.10,June
7,8,CULEX ERRATICUS,T002,41.954690,-87.800991,86.0,63.5,75.0,7.0,55.5,64.0,0.0,10.0,0.0,NaN,0.0,0.00,29.310,29.98,9.15,18.0,10.2,15.10,June
8,9,CULEX PIPIENS/RESTUANS,T007,41.994991,-87.769279,86.0,63.5,75.0,7.0,55.5,64.0,0.0,10.0,0.0,NaN,0.0,0.00,29.310,29.98,9.15,18.0,10.2,15.10,June
9,10,CULEX RESTUANS,T007,41.994991,-87.769279,86.0,63.5,75.0,7.0,55.5,64.0,0.0,10.0,0.0,NaN,0.0,0.00,29.310,29.98,9.15,18.0,10.2,15.10,June
10,11,CULEX PIPIENS,T007,41.994991,-87.769279,86.0,63.5,75.0,7.0,55.5,64.0,0.0,10.0,0.0,NaN,0.0,0.00,29.310,29.98,9.15,18.0,10.2,15.10,June
11,12,CULEX SALINARIUS,T007,41.994991,-87.769279,86.0,63.5,75.0,7.0,55.5,64.0,0.0,10.0,0.0,NaN,0.0,0.00,29.310,29.98,9.15,18.0,10.2,15.10,June
12,13,CULEX TERRITANS,T007,41.994991,-87.769279,86.0,63.5,75.0,7.0,55.5,64.0,0.0,10.0,0.0,NaN,0.0,0.00,29.310,29.98,9.15,18.0,10.2,15.10,June
13,14,CULEX TARSALIS,T007,41.994991,-87.769279,86.0,63.5,75.0,7.0,55.5,64.0,0.0,10.0,0.0,NaN,0.0,0.00,29.310,29.98,9.15,18.0,10.2,15.10,June
14,15,UNSPECIFIED CULEX,T007,41.994991,-87.769279,86.0,63.5,75.0,7.0,55.5,64.0,0.0,10.0,0.0,NaN,0.0,0.00,29.310,29.98,9.15,18.0,10.2,15.10,June
15,16,CULEX ERRATICUS,T007,41.994991,-87.769279,86.0,63.5,75.0,7.0,55.5,64.0,0.0,10.0,0.0,NaN,0.0,0.00,29.310,29.98,9.15,18.0,10.2,15.10,June
16,17,CULEX PIPIENS/RESTUANS,T015,41.974089,-87.824812,86.0,63.5,75.0,7.0,55.5,64.0,0.0,10.0,0.0,NaN,0.0,0.00,29.310,29.98,9.15,18.0,10.2,15.10,June
17,18,CULEX RESTUANS,T015,41.974089,-87.824812,86.0,63.5,75.0,7.0,55.5,64.0,0.0,10.0,0.0,NaN,0.0,0.00,29.310,29.98,9.15,18.0,10.2,15.10,June
18,19,CULEX PIPIENS,T015,41.974089,-87.824812,86.0,63.5,75.0,7.0,55.5,64.0,0.0,10.0,0.0,NaN,0.0,0.00,29.310,29.98,9.15,18.0,10.2,15.10,June
19,20,CULEX SALINARIUS,T015,41.974089,-87.824812,86.0,63.5,75.0,7.0,55.5,64.0,0.0,10.0,0.0,NaN,0.0,0.00,29.310,29.98,9.15,18.0,10.2,15.10,June
20,21,CULEX TERRITANS,T015,41.974089,-87.824812,86.0,63.5,75.0,7.0,55.5,64.0,0.0,10.0,0.0,NaN,0.0,0.00,29.310,29.98,9.15,18.0,10.2,15.10,June
21,22,CULEX TARSALIS,T015,41.974089,-87.824812,86.0,63.5,75.0,7.0,55.5,64.0,0.0,10.0,0.0,NaN,0.0,0.00,29.310,29.98,9.15,18.0,10.2,15.10,June
22,23,UNSPECIFIED CULEX,T015,41.974089,-87.824812,86.0,63.5,75.0,7.0,55.5,64.0,0.0,10.0,0.0,NaN,0.0,0.00,29.310,29.98,9.15,18.0,10.2,15.10,June
23,24,CULEX ERRATICUS,T015,41.974089,-87.824812,86.0,63.5,75.0,7.0,55.5,64.0,0.0,10.0,0.0,NaN,0.0,0.00,29.310,29.98,9.15,18.0,10.2,15.10,June
24,25,CULEX PIPIENS/RESTUANS,T045,41.921600,-87.666455,86.0,63.5,75.0,7.0,55.5,64.0,0.0,10.0,0.0,NaN,0.0,0.00,29.310,29.98,9.15,18.0,10.2,15.10,June
25,26,CULEX RESTUANS,T045,41.921600,-87.666455,86.0,63.5,75.0,7.0,55.5,64.0,0.0,10.0,0.0,NaN,0.0,0.00,29.310,29.98,9.15,18.0,10.2,15.10,June
26,27,CULEX PIPIENS,T045,41.921600,-87.666455,86.0,63.5,75.0,7.0,55.5,64.0,0.0,10.0,0.0,NaN,0.0,0.00,29.310,29.98,9.15,18.0,10.2,15.10,June
27,28,CULEX SALINARIUS,T045,41.921600,-87.666455,86.0,63.5,75.0,7.0,55.5,64.0,0.0,10.0,0.0,NaN,0.0,0.00,29.310,29.98,9.15,18.0,10.2,15.10,June
28,29,CULEX TERRITANS,T045,41.921600,-87.666455,86.0,63.5,75.0,7.0,55.5,64.0,0.0,10.0,0.0,NaN,0.0,0.00,29.310,29.98,9.15,18.0,10.2,15.10,June
29,30,CULEX TARSALIS,T045,41.921600,-87.666455,86.0,63.5,75.0,7.0,55.5,64.0,0.0,10.0,0.0,NaN,0.0,0.00,29.310,29.98,9.15,18.0,10.2,15.10,June
30,31,UNSPECIFIED CULEX,T045,41.921600,-87.666455,86.0,63.5,75.0,7.0,55.5,64.0,0.0,10.0,0.0,NaN,0.0,0.00,29.310,29.98,9.15,18.0,10.2,15.10,June
31,32,CULEX ERRATICUS,T045,41.921600,-87.666455,86.0,63.5,75.0,7.0,55.5,64.0,0.0,10.0,0.0,NaN,0.0,0.00,29.310,29.98,9.15,18.0,10.2,15.10,June
32,33,CULEX PIPIENS/RESTUANS,T046,41.891118,-87.654491,86.0,63.5,75.0,7.0,55.5,64.0,0.0,10.0,0.0,NaN,0.0,0.00,29.310,29.98,9.15,18.0,10.2,15.10,June
33,34,CULEX RESTUANS,T046,41.891118,-87.654491,86.0,63.5,75.0,7.0,55.5,64.0,0.0,10.0,0.0,NaN,0.0,0.00,29.310,29.98,9.15,18.0,10.2,15.10,June
34,35,CULEX PIPIENS,T046,41.891118,-87.654491,86.0,63.5,75.0,7.0,55.5,64.0,0.0,10.0,0.0,NaN,0.0,0.00,29.310,29.98,9.15,18.0,10.2,15.10,June
35,36,CULEX SALINARIUS,T046,41.891118,-87.654491,86.0,63.5,75.0,7.0,55.5,64.0,0.0,10.0,0.0,NaN,0.0,0.00,29.310,29.98,9.15,18.0,10.2,15.10,June
36,37,CULEX TERRITANS,T046,41.891118,-87.654491,86.0,63.5,75.0,7.0,55.5,64.0,0.0,10.0,0.0,NaN,0.0,0.00,29.310,29.98,9.15,18.0,10.2,15.10,June
37,38,CULEX TARSALIS,T046,41.891118,-87.654491,86.0,63.5,75.0,7.0,55.5,64.0,0.0,10.0,0.0,NaN,0.0,0.00,29.310,29.98,9.15,18.0,10.2,15.10,June
38,39,UNSPECIFIED CULEX,T046,41.891118,-87.654491,86.0,63.5,75.0,7.0,55.5,64.0,0.0,10.0,0.0,NaN,0.0,0.00,29.310,29.98,9.15,18.0,10.2,15.10,June
39,40,CULEX ERRATICUS,T046,41.891118,-87.654491,86.0,63.5,75.0,7.0,55.5,64.0,0.0,10.0,0.0,NaN,0.0,0.00,29.310,29.98,9.15,18.0,10.2,15.10,June
40,41,CULEX PIPIENS/RESTUANS,T048,41.867108,-87.654224,86.0,63.5,75.0,7.0,55.5,64.0,0.0,10.0,0.0,NaN,0.0,0.00,29.310,29.98,9.15,18.0,10.2,15.10,June
41,42,CULEX RESTUANS,T048,41.867108,-87.654224,86.0,63.5,75.0,7.0,55.5,64.0,0.0,10.0,0.0,NaN,0.0,0.00,29.310,29.98,9.15,18.0,10.2,15.10,June
42,43,CULEX PIPIENS,T048,41.867108,-87.654224,86.0,63.5,75.0,7.0,55.5,64.0,0.0,10.0,0.0,NaN,0.0,0.00,29.310,29.98,9.15,18.0,10.2,15.10,June
43,44,CULEX SALINARIUS,T048,41.867108,-87.654224,86.0,63.5,75.0,7.0,55.5,64.0,0.0,10.0,0.0,NaN,0.0,0.00,29.310,29.98,9.15,18.0,10.2,15.10,June
44,45,CULEX TERRITANS,T048,41.867108,-87.654224,86.0,63.5,75.0,7.0,55.5,64.0,0.0,10.0,0.0,NaN,0.0,0.00,29.310,29.98,9.15,18.0,10.2,15.10,June
45,46,CULEX TARSALIS,T048,41.867108,-87.654224,86.0,63.5,75.0,7.0,55.5,64.0,0.0,10.0,0.0,NaN,0.0,0.00,29.310,29.98,9.15,18.0,10.2,15.10,June
46,47,UNSPECIFIED CULEX,T048,41.867108,-87.654224,86.0,63.5,75.0,7.0,55.5,64.0,0.0,10.0,0.0,NaN,0.0,0.00,29.310,29.98,9.15,18.0,10.2,15.10,June
47,48,CULEX ERRATICUS,T048,41.867108,-87.654224,86.0,63.5,75.0,7.0,55.5,64.0,0.0,10.0,0.0,NaN,0.0,0.00,29.310,29.98,9.15,18.0,10.2,15.10,June
48,49,CULEX PIPIENS/RESTUANS,T049,41.896282,-87.655232,86.0,63.5,75.0,7.0,55.5,64.0,0.0,10.0,0.0,NaN,0.0,0.00,29.310,29.98,9.15,18.0,10.2,15.10,June
49,50,CULEX RESTUANS,T049,41.896282,-87.655232,86.0,63.5,75.0,7.0,55.5,64.0,0.0,10.0,0.0,NaN,0.0,0.00,29.310,29.98,9.15,18.0,10.2,15.10,June
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
116243,116244,UNSPECIFIED CULEX,T235,41.776428,-87.627096,73.5,64.5,69.5,10.0,62.0,64.0,0.0,4.5,0.0,NaN,0.0,0.52,29.065,29.78,7.20,17.0,7.9,11.83,Oct
116244,116245,CULEX ERRATICUS,T235,41.776428,-87.627096,73.5,64.5,69.5,10.0,62.0,64.0,0.0,4.5,0.0,NaN,0.0,0.52,29.065,29.78,7.20,17.0,7.9,11.83,Oct
116245,116246,CULEX PIPIENS/RESTUANS,T236,41.994679,-87.770899,73.5,64.5,69.5,10.0,62.0,64.0,0.0,4.5,0.0,NaN,0.0,0.52,29.065,29.78,7.20,17.0,7.9,11.83,Oct
116246,116247,CULEX RESTUANS,T236,41.994679,-87.770899,73.5,64.5,69.5,10.0,62.0,64.0,0.0,4.5,0.0,NaN,0.0,0.52,29.065,29.78,7.20,17.0,7.9,11.83,Oct
116247,116248,CULEX PIPIENS,T236,41.994679,-87.770899,73.5,64.5,69.5,10.0,62.0,64.0,0.0,4.5,0.0,NaN,0.0,0.52,29.065,29.78,7.20,17.0,7.9,11.83,Oct
116248,116249,CULEX SALINARIUS,T236,41.994679,-87.770899,73.5,64.5,69.5,10.0,62.0,64.0,0.0,4.5,0.0,NaN,0.0,0.52,29.065,29.78,7.20,17.0,7.9,11.83,Oct
116249,116250,CULEX TERRITANS,T236,41.994679,-87.770899,73.5,64.5,69.5,10.0,62.0,64.0,0.0,4.5,0.0,NaN,0.0,0.52,29.065,29.78,7.20,17.0,7.9,11.83,Oct
116250,116251,CULEX TARSALIS,T236,41.994679,-87.770899,73.5,64.5,69.5,10.0,62.0,64.0,0.0,4.5,0.0,NaN,0.0,0.52,29.065,29.78,7.20,17.0,7.9,11.83,Oct
116251,116252,UNSPECIFIED CULEX,T236,41.994679,-87.770899,73.5,64.5,69.5,10.0,62.0,64.0,0.0,4.5,0.0,NaN,0.0,0.52,29.065,29.78,7.20,17.0,7.9,11.83,Oct
116252,116253,CULEX ERRATICUS,T236,41.994679,-87.770899,73.5,64.5,69.5,10.0,62.0,64.0,0.0,4.5,0.0,NaN,0.0,0.52,29.065,29.78,7.20,17.0,7.9,11.83,Oct
116253,116254,CULEX PIPIENS/RESTUANS,T237,41.738903,-87.695443,73.5,64.5,69.5,10.0,62.0,64.0,0.0,4.5,0.0,NaN,0.0,0.52,29.065,29.78,7.20,17.0,7.9,11.83,Oct
116254,116255,CULEX RESTUANS,T237,41.738903,-87.695443,73.5,64.5,69.5,10.0,62.0,64.0,0.0,4.5,0.0,NaN,0.0,0.52,29.065,29.78,7.20,17.0,7.9,11.83,Oct
116255,116256,CULEX PIPIENS,T237,41.738903,-87.695443,73.5,64.5,69.5,10.0,62.0,64.0,0.0,4.5,0.0,NaN,0.0,0.52,29.065,29.78,7.20,17.0,7.9,11.83,Oct
116256,116257,CULEX SALINARIUS,T237,41.738903,-87.695443,73.5,64.5,69.5,10.0,62.0,64.0,0.0,4.5,0.0,NaN,0.0,0.52,29.065,29.78,7.20,17.0,7.9,11.83,Oct
116257,116258,CULEX TERRITANS,T237,41.738903,-87.695443,73.5,64.5,69.5,10.0,62.0,64.0,0.0,4.5,0.0,NaN,0.0,0.52,29.065,29.78,7.20,17.0,7.9,11.83,Oct
116258,116259,CULEX TARSALIS,T237,41.738903,-87.695443,73.5,64.5,69.5,10.0,62.0,64.0,0.0,4.5,0.0,NaN,0.0,0.52,29.065,29.78,7.20,17.0,7.9,11.83,Oct
116259,116260,UNSPECIFIED CULEX,T237,41.738903,-87.695443,73.5,64.5,69.5,10.0,62.0,64.0,0.0,4.5,0.0,NaN,0.0,0.52,29.065,29.78,7.20,17.0,7.9,11.83,Oct
116260,116261,CULEX ERRATICUS,T237,41.738903,-87.695443,73.5,64.5,69.5,10.0,62.0,64.0,0.0,4.5,0.0,NaN,0.0,0.52,29.065,29.78,7.20,17.0,7.9,11.83,Oct
116261,116262,CULEX PIPIENS/RESTUANS,T238,41.753391,-87.707394,73.5,64.5,69.5,10.0,62.0,64.0,0.0,4.5,0.0,NaN,0.0,0.52,29.065,29.78,7.20,17.0,7.9,11.83,Oct
116262,116263,CULEX RESTUANS,T238,41.753391,-87.707394,73.5,64.5,69.5,10.0,62.0,64.0,0.0,4.5,0.0,NaN,0.0,0.52,29.065,29.78,7.20,17.0,7.9,11.83,Oct
116263,116264,CULEX PIPIENS,T238,41.753391,-87.707394,73.5,64.5,69.5,10.0,62.0,64.0,0.0,4.5,0.0,NaN,0.0,0.52,29.065,29.78,7.20,17.0,7.9,11.83,Oct
116264,116265,CULEX SALINARIUS,T238,41.753391,-87.707394,73.5,64.5,69.5,10.0,62.0,64.0,0.0,4.5,0.0,NaN,0.0,0.52,29.065,29.78,7.20,17.0,7.9,11.83,Oct
116265,116266,CULEX TERRITANS,T238,41.753391,-87.707394,73.5,64.5,69.5,10.0,62.0,64.0,0.0,4.5,0.0,NaN,0.0,0.52,29.065,29.78,7.20,17.0,7.9,11.83,Oct
116266,116267,CULEX TARSALIS,T238,41.753391,-87.707394,73.5,64.5,69.5,10.0,62.0,64.0,0.0,4.5,0.0,NaN,0.0,0.52,29.065,29.78,7.20,17.0,7.9,11.83,Oct
116267,116268,UNSPECIFIED CULEX,T238,41.753391,-87.707394,73.5,64.5,69.5,10.0,62.0,64.0,0.0,4.5,0.0,NaN,0.0,0.52,29.065,29.78,7.20,17.0,7.9,11.83,Oct
116268,116269,CULEX ERRATICUS,T238,41.753391,-87.707394,73.5,64.5,69.5,10.0,62.0,64.0,0.0,4.5,0.0,NaN,0.0,0.52,29.065,29.78,7.20,17.0,7.9,11.83,Oct
116269,116270,CULEX PIPIENS/RESTUANS,T065A,41.777689,-87.749149,73.5,64.5,69.5,10.0,62.0,64.0,0.0,4.5,0.0,NaN,0.0,0.52,29.065,29.78,7.20,17.0,7.9,11.83,Oct
116270,116271,CULEX RESTUANS,T065A,41.777689,-87.749149,73.5,64.5,69.5,10.0,62.0,64.0,0.0,4.5,0.0,NaN,0.0,0.52,29.065,29.78,7.20,17.0,7.9,11.83,Oct
116271,116272,CULEX PIPIENS,T065A,41.777689,-87.749149,73.5,64.5,69.5,10.0,62.0,64.0,0.0,4.5,0.0,NaN,0.0,0.52,29.065,29.78,7.20,17.0,7.9,11.83,Oct
116272,116273,CULEX SALINARIUS,T065A,41.777689,-87.749149,73.5,64.5,69.5,10.0,62.0,64.0,0.0,4.5,0.0,NaN,0.0,0.52,29.065,29.78,7.20,17.0,7.9,11.83,Oct
116273,116274,CULEX TERRITANS,T065A,41.777689,-87.749149,73.5,64.5,69.5,10.0,62.0,64.0,0.0,4.5,0.0,NaN,0.0,0.52,29.065,29.78,7.20,17.0,7.9,11.83,Oct
116274,116275,CULEX TARSALIS,T065A,41.777689,-87.749149,73.5,64.5,69.5,10.0,62.0,64.0,0.0,4.5,0.0,NaN,0.0,0.52,29.065,29.78,7.20,17.0,7.9,11.83,Oct
116275,116276,UNSPECIFIED CULEX,T065A,41.777689,-87.749149,73.5,64.5,69.5,10.0,62.0,64.0,0.0,4.5,0.0,NaN,0.0,0.52,29.065,29.78,7.20,17.0,7.9,11.83,Oct
116276,116277,CULEX ERRATICUS,T065A,41.777689,-87.749149,73.5,64.5,69.5,10.0,62.0,64.0,0.0,4.5,0.0,NaN,0.0,0.52,29.065,29.78,7.20,17.0,7.9,11.83,Oct
116277,116278,CULEX PIPIENS/RESTUANS,T094B,41.719140,-87.669539,73.5,64.5,69.5,10.0,62.0,64.0,0.0,4.5,0.0,NaN,0.0,0.52,29.065,29.78,7.20,17.0,7.9,11.83,Oct
116278,116279,CULEX RESTUANS,T094B,41.719140,-87.669539,73.5,64.5,69.5,10.0,62.0,64.0,0.0,4.5,0.0,NaN,0.0,0.52,29.065,29.78,7.20,17.0,7.9,11.83,Oct
116279,116280,CULEX PIPIENS,T094B,41.719140,-87.669539,73.5,64.5,69.5,10.0,62.0,64.0,0.0,4.5,0.0,NaN,0.0,0.52,29.065,29.78,7.20,17.0,7.9,11.83,Oct
116280,116281,CULEX SALINARIUS,T094B,41.719140,-87.669539,73.5,64.5,69.5,10.0,62.0,64.0,0.0,4.5,0.0,NaN,0.0,0.52,29.065,29.78,7.20,17.0,7.9,11.83,Oct
116281,116282,CULEX TERRITANS,T094B,41.719140,-87.669539,73.5,64.5,69.5,10.0,62.0,64.0,0.0,4.5,0.0,NaN,0.0,0.52,29.065,29.78,7.20,17.0,7.9,11.83,Oct
116282,116283,CULEX TARSALIS,T094B,41.719140,-87.669539,73.5,64.5,69.5,10.0,62.0,64.0,0.0,4.5,0.0,NaN,0.0,0.52,29.065,29.78,7.20,17.0,7.9,11.83,Oct
116283,116284,UNSPECIFIED CULEX,T094B,41.719140,-87.669539,73.5,64.5,69.5,10.0,62.0,64.0,0.0,4.5,0.0,NaN,0.0,0.52,29.065,29.78,7.20,17.0,7.9,11.83,Oct
116284,116285,CULEX ERRATICUS,T094B,41.719140,-87.669539,73.5,64.5,69.5,10.0,62.0,64.0,0.0,4.5,0.0,NaN,0.0,0.52,29.065,29.78,7.20,17.0,7.9,11.83,Oct
116285,116286,CULEX PIPIENS/RESTUANS,T054C,41.925652,-87.633590,73.5,64.5,69.5,10.0,62.0,64.0,0.0,4.5,0.0,NaN,0.0,0.52,29.065,29.78,7.20,17.0,7.9,11.83,Oct
116286,116287,CULEX RESTUANS,T054C,41.925652,-87.633590,73.5,64.5,69.5,10.0,62.0,64.0,0.0,4.5,0.0,NaN,0.0,0.52,29.065,29.78,7.20,17.0,7.9,11.83,Oct
116287,116288,CULEX PIPIENS,T054C,41.925652,-87.633590,73.5,64.5,69.5,10.0,62.0,64.0,0.0,4.5,0.0,NaN,0.0,0.52,29.065,29.78,7.20,17.0,7.9,11.83,Oct
116288,116289,CULEX SALINARIUS,T054C,41.925652,-87.633590,73.5,64.5,69.5,10.0,62.0,64.0,0.0,4.5,0.0,NaN,0.0,0.52,29.065,29.78,7.20,17.0,7.9,11.83,Oct
116289,116290,CULEX TERRITANS,T054C,41.925652,-87.633590,73.5,64.5,69.5,10.0,62.0,64.0,0.0,4.5,0.0,NaN,0.0,0.52,29.065,29.78,7.20,17.0,7.9,11.83,Oct
116290,116291,CULEX TARSALIS,T054C,41.925652,-87.633590,73.5,64.5,69.5,10.0,62.0,64.0,0.0,4.5,0.0,NaN,0.0,0.52,29.065,29.78,7.20,17.0,7.9,11.83,Oct
116291,116292,UNSPECIFIED CULEX,T054C,41.925652,-87.633590,73.5,64.5,69.5,10.0,62.0,64.0,0.0,4.5,0.0,NaN,0.0,0.52,29.065,29.78,7.20,17.0,7.9,11.83,Oct
116292,116293,CULEX ERRATICUS,T054C,41.925652,-87.633590,73.5,64.5,69.5,10.0,62.0,64.0,0.0,4.5,0.0,NaN,0.0,0.52,29.065,29.78,7.20,17.0,7.9,11.83,Oct

### Handling Location Data (Latitude and Longitude)

In [34]:
# New Feature, covers a district area by rounding lat and long to 1 decimal point
df['Lat&Long'] = df.Latitude.round(1).astype(str) + df.Longitude.round(1).astype(str)
df['Lat&Long'].nunique()

14

In [35]:
# Dropping the old features latitude and longitude
df.drop(['Latitude', 'Longitude'], axis=1, inplace=True)

### One-Hot Encoding

Helper function to one hot encode

In [36]:
def onehot(df, col, new_names=None):
    """
    One hot encoding a DF's column, concatenating the new columns with the original DF, and dropping the older columns
    """
    oneh = pd.get_dummies(df[col], columns=new_names)
    
    # Concatenating the one-hot DF with the current DF
    df = pd.concat([df, oneh], axis=1, join='inner')
    
    return df

For the __Species__ column

In [37]:
df = onehot(df, 'Species')
df

,Id,Species,Trap,Tmax,Tmin,Tavg,Depart,DewPoint,WetBulb,Heat,Cool,Depth,Water1,SnowFall,PrecipTotal,StnPressure,SeaLevel,ResultSpeed,ResultDir,AvgSpeed,Daylight,Month,Lat&Long,CULEX ERRATICUS,CULEX PIPIENS,CULEX PIPIENS/RESTUANS,CULEX RESTUANS,CULEX SALINARIUS,CULEX TARSALIS,CULEX TERRITANS,UNSPECIFIED CULEX
0,1,CULEX PIPIENS/RESTUANS,T002,86.0,63.5,75.0,7.0,55.5,64.0,0.0,10.0,0.0,NaN,0.0,0.00,29.310,29.98,9.15,18.0,10.2,15.10,June,42.0-87.8,0,0,1,0,0,0,0,0
1,2,CULEX RESTUANS,T002,86.0,63.5,75.0,7.0,55.5,64.0,0.0,10.0,0.0,NaN,0.0,0.00,29.310,29.98,9.15,18.0,10.2,15.10,June,42.0-87.8,0,0,0,1,0,0,0,0
2,3,CULEX PIPIENS,T002,86.0,63.5,75.0,7.0,55.5,64.0,0.0,10.0,0.0,NaN,0.0,0.00,29.310,29.98,9.15,18.0,10.2,15.10,June,42.0-87.8,0,1,0,0,0,0,0,0
3,4,CULEX SALINARIUS,T002,86.0,63.5,75.0,7.0,55.5,64.0,0.0,10.0,0.0,NaN,0.0,0.00,29.310,29.98,9.15,18.0,10.2,15.10,June,42.0-87.8,0,0,0,0,1,0,0,0
4,5,CULEX TERRITANS,T002,86.0,63.5,75.0,7.0,55.5,64.0,0.0,10.0,0.0,NaN,0.0,0.00,29.310,29.98,9.15,18.0,10.2,15.10,June,42.0-87.8,0,0,0,0,0,0,1,0
5,6,CULEX TARSALIS,T002,86.0,63.5,75.0,7.0,55.5,64.0,0.0,10.0,0.0,NaN,0.0,0.00,29.310,29.98,9.15,18.0,10.2,15.10,June,42.0-87.8,0,0,0,0,0,1,0,0
6,7,UNSPECIFIED CULEX,T002,86.0,63.5,75.0,7.0,55.5,64.0,0.0,10.0,0.0,NaN,0.0,0.00,29.310,29.98,9.15,18.0,10.2,15.10,June,42.0-87.8,0,0,0,0,0,0,0,1
7,8,CULEX ERRATICUS,T002,86.0,63.5,75.0,7.0,55.5,64.0,0.0,10.0,0.0,NaN,0.0,0.00,29.310,29.98,9.15,18.0,10.2,15.10,June,42.0-87.8,1,0,0,0,0,0,0,0
8,9,CULEX PIPIENS/RESTUANS,T007,86.0,63.5,75.0,7.0,55.5,64.0,0.0,10.0,0.0,NaN,0.0,0.00,29.310,29.98,9.15,18.0,10.2,15.10,June,42.0-87.8,0,0,1,0,0,0,0,0
9,10,CULEX RESTUANS,T007,86.0,63.5,75.0,7.0,55.5,64.0,0.0,10.0,0.0,NaN,0.0,0.00,29.310,29.98,9.15,18.0,10.2,15.10,June,42.0-87.8,0,0,0,1,0,0,0,0
10,11,CULEX PIPIENS,T007,86.0,63.5,75.0,7.0,55.5,64.0,0.0,10.0,0.0,NaN,0.0,0.00,29.310,29.98,9.15,18.0,10.2,15.10,June,42.0-87.8,0,1,0,0,0,0,0,0
11,12,CULEX SALINARIUS,T007,86.0,63.5,75.0,7.0,55.5,64.0,0.0,10.0,0.0,NaN,0.0,0.00,29.310,29.98,9.15,18.0,10.2,15.10,June,42.0-87.8,0,0,0,0,1,0,0,0
12,13,CULEX TERRITANS,T007,86.0,63.5,75.0,7.0,55.5,64.0,0.0,10.0,0.0,NaN,0.0,0.00,29.310,29.98,9.15,18.0,10.2,15.10,June,42.0-87.8,0,0,0,0,0,0,1,0
13,14,CULEX TARSALIS,T007,86.0,63.5,75.0,7.0,55.5,64.0,0.0,10.0,0.0,NaN,0.0,0.00,29.310,29.98,9.15,18.0,10.2,15.10,June,42.0-87.8,0,0,0,0,0,1,0,0
14,15,UNSPECIFIED CULEX,T007,86.0,63.5,75.0,7.0,55.5,64.0,0.0,10.0,0.0,NaN,0.0,0.00,29.310,29.98,9.15,18.0,10.2,15.10,June,42.0-87.8,0,0,0,0,0,0,0,1
15,16,CULEX ERRATICUS,T007,86.0,63.5,75.0,7.0,55.5,64.0,0.0,10.0,0.0,NaN,0.0,0.00,29.310,29.98,9.15,18.0,10.2,15.10,June,42.0-87.8,1,0,0,0,0,0,0,0
16,17,CULEX PIPIENS/RESTUANS,T015,86.0,63.5,75.0,7.0,55.5,64.0,0.0,10.0,0.0,NaN,0.0,0.00,29.310,29.98,9.15,18.0,10.2,15.10,June,42.0-87.8,0,0,1,0,0,0,0,0
17,18,CULEX RESTUANS,T015,86.0,63.5,75.0,7.0,55.5,64.0,0.0,10.0,0.0,NaN,0.0,0.00,29.310,29.98,9.15,18.0,10.2,15.10,June,42.0-87.8,0,0,0,1,0,0,0,0
18,19,CULEX PIPIENS,T015,86.0,63.5,75.0,7.0,55.5,64.0,0.0,10.0,0.0,NaN,0.0,0.00,29.310,29.98,9.15,18.0,10.2,15.10,June,42.0-87.8,0,1,0,0,0,0,0,0
19,20,CULEX SALINARIUS,T015,86.0,63.5,75.0,7.0,55.5,64.0,0.0,10.0,0.0,NaN,0.0,0.00,29.310,29.98,9.15,18.0,10.2,15.10,June,42.0-87.8,0,0,0,0,1,0,0,0
20,21,CULEX TERRITANS,T015,86.0,63.5,75.0,7.0,55.5,64.0,0.0,10.0,0.0,NaN,0.0,0.00,29.310,29.98,9.15,18.0,10.2,15.10,June,42.0-87.8,0,0,0,0,0,0,1,0
21,22,CULEX TARSALIS,T015,86.0,63.5,75.0,7.0,55.5,64.0,0.0,10.0,0.0,NaN,0.0,0.00,29.310,29.98,9.15,18.0,10.2,15.10,June,42.0-87.8,0,0,0,0,0,1,0,0
22,23,UNSPECIFIED CULEX,T015,86.0,63.5,75.0,7.0,55.5,64.0,0.0,10.0,0.0,NaN,0.0,0.00,29.310,29.98,9.15,18.0,10.2,15.10,June,42.0-87.8,0,0,0,0,0,0,0,1
23,24,CULEX ERRATICUS,T015,86.0,63.5,75.0,7.0,55.5,64.0,0.0,10.0,0.0,NaN,0.0,0.00,29.310,29.98,9.15,18.0,10.2,15.10,June,42.0-87.8,1,0,0,0,0,0,0,0
24,25,CULEX PIPIENS/RESTUANS,T045,86.0,63.5,75.0,7.0,55.5,64.0,0.0,10.0,0.0,NaN,0.0,0.00,29.310,29.98,9.15,18.0,10.2,15.10,June,41.9-87.7,0,0,1,0,0,0,0,0
25,26,CULEX RESTUANS,T045,86.0,63.5,75.0,7.0,55.5,64.0,0.0,10.0,0.0,NaN,0.0,0.00,29.310,29.98,9.15,18.0,10.2,15.10,June,41.9-87.7,0,0,0,1,0,0,0,0
26,27,CULEX PIPIENS,T045,86.0,63.5,75.0,7.0,55.5,64.0,0.0,10.0,0.0,NaN,0.0,0.00,29.310,29.98,9.15,18.0,10.2,15.10,June,41.9-87.7,0,1,0,0,0,0,0,0
27,28,CULEX SALINARIUS,T045,86.0,63.5,75.0,7.0,55.5,64.0,0.0,10.0,0.0,NaN,0.0,0.00,29.310,29.98,9.15,18.0,10.2,15.10,June,41.9-87.7,0,0,0,0,1,0,0,0
28,29,CULEX TERRITANS,T045,86.0,63.5,75.0,7.0,55.5,64.0,0.0,10.0,0.0,NaN,0.0,0.00,29.310,29.98,9.15,18.0,10.2,15.10,June,41.9-87.7,0,0,0,0,0,0,1,0
29,30,CULEX TARSALIS,T045,86.0,63.5,75.0,7.0,55.5,64.0,0.0,10.0,0.0,NaN,0.0,0.00,29.310,29.98,9.15,18.0,10.2,15.10,June,41.9-87.7,0,0,0,0,0,1,0,0
30,31,UNSPECIFIED CULEX,T045,86.0,63.5,75.0,7.0,55.5,64.0,0.0,10.0,0.0,NaN,0.0,0.00,29.310,29.98,9.15,18.0,10.2,15.10,June,41.9-87.7,0,0,0,0,0,0,0,1
31,32,CULEX ERRATICUS,T045,86.0,63.5,75.0,7.0,55.5,64.0,0.0,10.0,0.0,NaN,0.0,0.00,29.310,29.98,9.15,18.0,10.2,15.10,June,41.9-87.7,1,0,0,0,0,0,0,0
32,33,CULEX PIPIENS/RESTUANS,T046,86.0,63.5,75.0,7.0,55.5,64.0,0.0,10.0,0.0,NaN,0.0,0.00,29.310,29.98,9.15,18.0,10.2,15.10,June,41.9-87.7,0,0,1,0,0,0,0,0
33,34,CULEX RESTUANS,T046,86.0,63.5,75.0,7.0,55.5,64.0,0.0,10.0,0.0,NaN,0.0,0.00,29.310,29.98,9.15,18.0,10.2,15.10,June,41.9-87.7,0,0,0,1,0,0,0,0
34,35,CULEX PIPIENS,T046,86.0,63.5,75.0,7.0,55.5,64.0,0.0,10.0,0.0,NaN,0.0,0.00,29.310,29.98,9.15,18.0,10.2,15.10,June,41.9-87.7,0,1,0,0,0,0,0,0
35,36,CULEX SALINARIUS,T046,86.0,63.5,75.0,7.0,55.5,64.0,0.0,10.0,0.0,NaN,0.0,0.00,29.310,29.98,9.15,18.0,10.2,15.10,June,41.9-87.7,0,0,0,0,1,0,0,0
36,37,CULEX TERRITANS,T046,86.0,63.5,75.0,7.0,55.5,64.0,0.0,10.0,0.0,NaN,0.0,0.00,29.310,29.98,9.15,18.0,10.2,15.10,June,41.9-87.7,0,0,0,0,0,0,1,0
37,38,CULEX TARSALIS,T046,86.0,63.5,75.0,7.0,55.5,64.0,0.0,10.0,0.0,NaN,0.0,0.00,29.310,29.98,9.15,18.0,10.2,15.10,June,41.9-87.7,0,0,0,0,0,1,0,0
38,39,UNSPECIFIED CULEX,T046,86.0,63.5,75.0,7.0,55.5,64.0,0.0,10.0,0.0,NaN,0.0,0.00,29.310,29.98,9.15,18.0,10.2,15.10,June,41.9-87.7,0,0,0,0,0,0,0,1
39,40,CULEX ERRATICUS,T046,86.0,63.5,75.0,7.0,55.5,64.0,0.0,10.0,0.0,NaN,0.0,0.00,29.310,29.98,9.15,18.0,10.2,15.10,June,41.9-87.7,1,0,0,0,0,0,0,0
40,41,CULEX PIPIENS/RESTUANS,T048,86.0,63.5,75.0,7.0,55.5,64.0,0.0,10.0,0.0,NaN,0.0,0.00,29.310,29.98,9.15,18.0,10.2,15.10,June,41.9-87.7,0,0,1,0,0,0,0,0
41,42,CULEX RESTUANS,T048,86.0,63.5,75.0,7.0,55.5,64.0,0.0,10.0,0.0,NaN,0.0,0.00,29.310,29.98,9.15,18.0,10.2,15.10,June,41.9-87.7,0,0,0,1,0,0,0,0
42,43,CULEX PIPIENS,T048,86.0,63.5,75.0,7.0,55.5,64.0,0.0,10.0,0.0,NaN,0.0,0.00,29.310,29.98,9.15,18.0,10.2,15.10,June,41.9-87.7,0,1,0,0,0,0,0,0
43,44,CULEX SALINARIUS,T048,86.0,63.5,75.0,7.0,55.5,64.0,0.0,10.0,0.0,NaN,0.0,0.00,29.310,29.98,9.15,18.0,10.2,15.10,June,41.9-87.7,0,0,0,0,1,0,0,0
44,45,CULEX TERRITANS,T048,86.0,63.5,75.0,7.0,55.5,64.0,0.0,10.0,0.0,NaN,0.0,0.00,29.310,29.98,9.15,18.0,10.2,15.10,June,41.9-87.7,0,0,0,0,0,0,1,0
45,46,CULEX TARSALIS,T048,86.0,63.5,75.0,7.0,55.5,64.0,0.0,10.0,0.0,NaN,0.0,0.00,29.310,29.98,9.15,18.0,10.2,15.10,June,41.9-87.7,0,0,0,0,0,1,0,0
46,47,UNSPECIFIED CULEX,T048,86.0,63.5,75.0,7.0,55.5,64.0,0.0,10.0,0.0,NaN,0.0,0.00,29.310,29.98,9.15,18.0,10.2,15.10,June,41.9-87.7,0,0,0,0,0,0,0,1
47,48,CULEX ERRATICUS,T048,86.0,63.5,75.0,7.0,55.5,64.0,0.0,10.0,0.0,NaN,0.0,0.00,29.310,29.98,9.15,18.0,10.2,15.10,June,41.9-87.7,1,0,0,0,0,0,0,0
48,49,CULEX PIPIENS/RESTUANS,T049,86.0,63.5,75.0,7.0,55.5,64.0,0.0,10.0,0.0,NaN,0.0,0.00,29.310,29.98,9.15,18.0,10.2,15.10,June,41.9-87.7,0,0,1,0,0,0,0,0
49,50,CULEX RESTUANS,T049,86.0,63.5,75.0,7.0,55.5,64.0,0.0,10.0,0.0,NaN,0.0,0.00,29.310,29.98,9.15,18.0,10.2,15.10,June,41.9-87.7,0,0,0,1,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
116243,116244,UNSPECIFIED CULEX,T235,73.5,64.5,69.5,10.0,62.0,64.0,0.0,4.5,0.0,NaN,0.0,0.52,29.065,29.78,7.20,17.0,7.9,11.83,Oct,41.8-87.6,0,0,0,0,0,0,0,1
116244,116245,CULEX ERRATICUS,T235,73.5,64.5,69.5,10.0,62.0,64.0,0.0,4.5,0.0,NaN,0.0,0.52,29.065,29.78,7.20,17.0,7.9,11.83,Oct,41.8-87.6,1,0,0,0,0,0,0,0
116245,116246,CULEX PIPIENS/RESTUANS,T236,73.5,64.5,69.5,10.0,62.0,64.0,0.0,4.5,0.0,NaN,0.0,0.52,29.065,29.78,7.20,17.0,7.9,11.83,Oct,42.0-87.8,0,0,1,0,0,0,0,0
116246,116247,CULEX RESTUANS,T236,73.5,64.5,69.5,10.0,62.0,64.0,0.0,4.5,0.0,NaN,0.0,0.52,29.065,29.78,7.20,17.0,7.9,11.83,Oct,42.0-87.8,0,0,0,1,0,0,0,0
116247,116248,CULEX PIPIENS,T236,73.5,64.5,69.5,10.0,62.0,64.0,0.0,4.5,0.0,NaN,0.0,0.52,29.065,29.78,7.20,17.0,7.9,11.83,Oct,42.0-87.8,0,1,0,0,0,0,0,0
116248,116249,CULEX SALINARIUS,T236,73.5,64.5,69.5,10.0,62.0,64.0,0.0,4.5,0.0,NaN,0.0,0.52,29.065,29.78,7.20,17.0,7.9,11.83,Oct,42.0-87.8,0,0,0,0,1,0,0,0
116249,116250,CULEX TERRITANS,T236,73.5,64.5,69.5,10.0,62.0,64.0,0.0,4.5,0.0,NaN,0.0,0.52,29.065,29.78,7.20,17.0,7.9,11.83,Oct,42.0-87.8,0,0,0,0,0,0,1,0
116250,116251,CULEX TARSALIS,T236,73.5,64.5,69.5,10.0,62.0,64.0,0.0,4.5,0.0,NaN,0.0,0.52,29.065,29.78,7.20,17.0,7.9,11.83,Oct,42.0-87.8,0,0,0,0,0,1,0,0
116251,116252,UNSPECIFIED CULEX,T236,73.5,64.5,69.5,10.0,62.0,64.0,0.0,4.5,0.0,NaN,0.0,0.52,29.065,29.78,7.20,17.0,7.9,11.83,Oct,42.0-87.8,0,0,0,0,0,0,0,1
116252,116253,CULEX ERRATICUS,T236,73.5,64.5,69.5,10.0,62.0,64.0,0.0,4.5,0.0,NaN,0.0,0.52,29.065,29.78,7.20,17.0,7.9,11.83,Oct,42.0-87.8,1,0,0,0,0,0,0,0
116253,116254,CULEX PIPIENS/RESTUANS,T237,73.5,64.5,69.5,10.0,62.0,64.0,0.0,4.5,0.0,NaN,0.0,0.52,29.065,29.78,7.20,17.0,7.9,11.83,Oct,41.7-87.7,0,0,1,0,0,0,0,0
116254,116255,CULEX RESTUANS,T237,73.5,64.5,69.5,10.0,62.0,64.0,0.0,4.5,0.0,NaN,0.0,0.52,29.065,29.78,7.20,17.0,7.9,11.83,Oct,41.7-87.7,0,0,0,1,0,0,0,0
116255,116256,CULEX PIPIENS,T237,73.5,64.5,69.5,10.0,62.0,64.0,0.0,4.5,0.0,NaN,0.0,0.52,29.065,29.78,7.20,17.0,7.9,11.83,Oct,41.7-87.7,0,1,0,0,0,0,0,0
116256,116257,CULEX SALINARIUS,T237,73.5,64.5,69.5,10.0,62.0,64.0,0.0,4.5,0.0,NaN,0.0,0.52,29.065,29.78,7.20,17.0,7.9,11.83,Oct,41.7-87.7,0,0,0,0,1,0,0,0
116257,116258,CULEX TERRITANS,T237,73.5,64.5,69.5,10.0,62.0,64.0,0.0,4.5,0.0,NaN,0.0,0.52,29.065,29.78,7.20,17.0,7.9,11.83,Oct,41.7-87.7,0,0,0,0,0,0,1,0
116258,116259,CULEX TARSALIS,T237,73.5,64.5,69.5,10.0,62.0,64.0,0.0,4.5,0.0,NaN,0.0,0.52,29.065,29.78,7.20,17.0,7.9,11.83,Oct,41.7-87.7,0,0,0,0,0,1,0,0
116259,116260,UNSPECIFIED CULEX,T237,73.5,64.5,69.5,10.0,62.0,64.0,0.0,4.5,0.0,NaN,0.0,0.52,29.065,29.78,7.20,17.0,7.9,11.83,Oct,41.7-87.7,0,0,0,0,0,0,0,1
116260,116261,CULEX ERRATICUS,T237,73.5,64.5,69.5,10.0,62.0,64.0,0.0,4.5,0.0,NaN,0.0,0.52,29.065,29.78,7.20,17.0,7.9,11.83,Oct,41.7-87.7,1,0,0,0,0,0,0,0
116261,116262,CULEX PIPIENS/RESTUANS,T238,73.5,64.5,69.5,10.0,62.0,64.0,0.0,4.5,0.0,NaN,0.0,0.52,29.065,29.78,7.20,17.0,7.9,11.83,Oct,41.8-87.7,0,0,1,0,0,0,0,0
116262,116263,CULEX RESTUANS,T238,73.5,64.5,69.5,10.0,62.0,64.0,0.0,4.5,0.0,NaN,0.0,0.52,29.065,29.78,7.20,17.0,7.9,11.83,Oct,41.8-87.7,0,0,0,1,0,0,0,0
116263,116264,CULEX PIPIENS,T238,73.5,64.5,69.5,10.0,62.0,64.0,0.0,4.5,0.0,NaN,0.0,0.52,29.065,29.78,7.20,17.0,7.9,11.83,Oct,41.8-87.7,0,1,0,0,0,0,0,0
116264,116265,CULEX SALINARIUS,T238,73.5,64.5,69.5,10.0,62.0,64.0,0.0,4.5,0.0,NaN,0.0,0.52,29.065,29.78,7.20,17.0,7.9,11.83,Oct,41.8-87.7,0,0,0,0,1,0,0,0
116265,116266,CULEX TERRITANS,T238,73.5,64.5,69.5,10.0,62.0,64.0,0.0,4.5,0.0,NaN,0.0,0.52,29.065,29.78,7.20,17.0,7.9,11.83,Oct,41.8-87.7,0,0,0,0,0,0,1,0
116266,116267,CULEX TARSALIS,T238,73.5,64.5,69.5,10.0,62.0,64.0,0.0,4.5,0.0,NaN,0.0,0.52,29.065,29.78,7.20,17.0,7.9,11.83,Oct,41.8-87.7,0,0,0,0,0,1,0,0
116267,116268,UNSPECIFIED CULEX,T238,73.5,64.5,69.5,10.0,62.0,64.0,0.0,4.5,0.0,NaN,0.0,0.52,29.065,29.78,7.20,17.0,7.9,11.83,Oct,41.8-87.7,0,0,0,0,0,0,0,1
116268,116269,CULEX ERRATICUS,T238,73.5,64.5,69.5,10.0,62.0,64.0,0.0,4.5,0.0,NaN,0.0,0.52,29.065,29.78,7.20,17.0,7.9,11.83,Oct,41.8-87.7,1,0,0,0,0,0,0,0
116269,116270,CULEX PIPIENS/RESTUANS,T065A,73.5,64.5,69.5,10.0,62.0,64.0,0.0,4.5,0.0,NaN,0.0,0.52,29.065,29.78,7.20,17.0,7.9,11.83,Oct,41.8-87.7,0,0,1,0,0,0,0,0
116270,116271,CULEX RESTUANS,T065A,73.5,64.5,69.5,10.0,62.0,64.0,0.0,4.5,0.0,NaN,0.0,0.52,29.065,29.78,7.20,17.0,7.9,11.83,Oct,41.8-87.7,0,0,0,1,0,0,0,0
116271,116272,CULEX PIPIENS,T065A,73.5,64.5,69.5,10.0,62.0,64.0,0.0,4.5,0.0,NaN,0.0,0.52,29.065,29.78,7.20,17.0,7.9,11.83,Oct,41.8-87.7,0,1,0,0,0,0,0,0
116272,116273,CULEX SALINARIUS,T065A,73.5,64.5,69.5,10.0,62.0,64.0,0.0,4.5,0.0,NaN,0.0,0.52,29.065,29.78,7.20,17.0,7.9,11.83,Oct,41.8-87.7,0,0,0,0,1,0,0,0
116273,116274,CULEX TERRITANS,T065A,73.5,64.5,69.5,10.0,62.0,64.0,0.0,4.5,0.0,NaN,0.0,0.52,29.065,29.78,7.20,17.0,7.9,11.83,Oct,41.8-87.7,0,0,0,0,0,0,1,0
116274,116275,CULEX TARSALIS,T065A,73.5,64.5,69.5,10.0,62.0,64.0,0.0,4.5,0.0,NaN,0.0,0.52,29.065,29.78,7.20,17.0,7.9,11.83,Oct,41.8-87.7,0,0,0,0,0,1,0,0
116275,116276,UNSPECIFIED CULEX,T065A,73.5,64.5,69.5,10.0,62.0,64.0,0.0,4.5,0.0,NaN,0.0,0.52,29.065,29.78,7.20,17.0,7.9,11.83,Oct,41.8-87.7,0,0,0,0,0,0,0,1
116276,116277,CULEX ERRATICUS,T065A,73.5,64.5,69.5,10.0,62.0,64.0,0.0,4.5,0.0,NaN,0.0,0.52,29.065,29.78,7.20,17.0,7.9,11.83,Oct,41.8-87.7,1,0,0,0,0,0,0,0
116277,116278,CULEX PIPIENS/RESTUANS,T094B,73.5,64.5,69.5,10.0,62.0,64.0,0.0,4.5,0.0,NaN,0.0,0.52,29.065,29.78,7.20,17.0,7.9,11.83,Oct,41.7-87.7,0,0,1,0,0,0,0,0
116278,116279,CULEX RESTUANS,T094B,73.5,64.5,69.5,10.0,62.0,64.0,0.0,4.5,0.0,NaN,0.0,0.52,29.065,29.78,7.20,17.0,7.9,11.83,Oct,41.7-87.7,0,0,0,1,0,0,0,0
116279,116280,CULEX PIPIENS,T094B,73.5,64.5,69.5,10.0,62.0,64.0,0.0,4.5,0.0,NaN,0.0,0.52,29.065,29.78,7.20,17.0,7.9,11.83,Oct,41.7-87.7,0,1,0,0,0,0,0,0
116280,116281,CULEX SALINARIUS,T094B,73.5,64.5,69.5,10.0,62.0,64.0,0.0,4.5,0.0,NaN,0.0,0.52,29.065,29.78,7.20,17.0,7.9,11.83,Oct,41.7-87.7,0,0,0,0,1,0,0,0
116281,116282,CULEX TERRITANS,T094B,73.5,64.5,69.5,10.0,62.0,64.0,0.0,4.5,0.0,NaN,0.0,0.52,29.065,29.78,7.20,17.0,7.9,11.83,Oct,41.7-87.7,0,0,0,0,0,0,1,0
116282,116283,CULEX TARSALIS,T094B,73.5,64.5,69.5,10.0,62.0,64.0,0.0,4.5,0.0,NaN,0.0,0.52,29.065,29.78,7.20,17.0,7.9,11.83,Oct,41.7-87.7,0,0,0,0,0,1,0,0
116283,116284,UNSPECIFIED CULEX,T094B,73.5,64.5,69.5,10.0,62.0,64.0,0.0,4.5,0.0,NaN,0.0,0.52,29.065,29.78,7.20,17.0,7.9,11.83,Oct,41.7-87.7,0,0,0,0,0,0,0,1
116284,116285,CULEX ERRATICUS,T094B,73.5,64.5,69.5,10.0,62.0,64.0,0.0,4.5,0.0,NaN,0.0,0.52,29.065,29.78,7.20,17.0,7.9,11.83,Oct,41.7-87.7,1,0,0,0,0,0,0,0
116285,116286,CULEX PIPIENS/RESTUANS,T054C,73.5,64.5,69.5,10.0,62.0,64.0,0.0,4.5,0.0,NaN,0.0,0.52,29.065,29.78,7.20,17.0,7.9,11.83,Oct,41.9-87.6,0,0,1,0,0,0,0,0
116286,116287,CULEX RESTUANS,T054C,73.5,64.5,69.5,10.0,62.0,64.0,0.0,4.5,0.0,NaN,0.0,0.52,29.065,29.78,7.20,17.0,7.9,11.83,Oct,41.9-87.6,0,0,0,1,0,0,0,0
116287,116288,CULEX PIPIENS,T054C,73.5,64.5,69.5,10.0,62.0,64.0,0.0,4.5,0.0,NaN,0.0,0.52,29.065,29.78,7.20,17.0,7.9,11.83,Oct,41.9-87.6,0,1,0,0,0,0,0,0
116288,116289,CULEX SALINARIUS,T054C,73.5,64.5,69.5,10.0,62.0,64.0,0.0,4.5,0.0,NaN,0.0,0.52,29.065,29.78,7.20,17.0,7.9,11.83,Oct,41.9-87.6,0,0,0,0,1,0,0,0
116289,116290,CULEX TERRITANS,T054C,73.5,64.5,69.5,10.0,62.0,64.0,0.0,4.5,0.0,NaN,0.0,0.52,29.065,29.78,7.20,17.0,7.9,11.83,Oct,41.9-87.6,0,0,0,0,0,0,1,0
116290,116291,CULEX TARSALIS,T054C,73.5,64.5,69.5,10.0,62.0,64.0,0.0,4.5,0.0,NaN,0.0,0.52,29.065,29.78,7.20,17.0,7.9,11.83,Oct,41.9-87.6,0,0,0,0,0,1,0,0
116291,116292,UNSPECIFIED CULEX,T054C,73.5,64.5,69.5,10.0,62.0,64.0,0.0,4.5,0.0,NaN,0.0,0.52,29.065,29.78,7.20,17.0,7.9,11.83,Oct,41.9-87.6,0,0,0,0,0,0,0,1
116292,116293,CULEX ERRATICUS,T054C,73.5,64.5,69.5,10.0,62.0,64.0,0.0,4.5,0.0,NaN,0.0,0.52,29.065,29.78,7.20,17.0,7.9,11.83,Oct,41.9-87.6,1,0,0,0,0,0,0,0

For the __Lat&Long__ column

In [38]:
df = onehot(df, 'Lat&Long')
df

,Id,Species,Trap,Tmax,Tmin,Tavg,Depart,DewPoint,WetBulb,Heat,Cool,Depth,Water1,SnowFall,PrecipTotal,StnPressure,SeaLevel,ResultSpeed,ResultDir,AvgSpeed,Daylight,Month,Lat&Long,CULEX ERRATICUS,CULEX PIPIENS,CULEX PIPIENS/RESTUANS,CULEX RESTUANS,CULEX SALINARIUS,CULEX TARSALIS,CULEX TERRITANS,UNSPECIFIED CULEX,41.6-87.5,41.6-87.6,41.7-87.5,41.7-87.6,41.7-87.7,41.8-87.6,41.8-87.7,41.8-87.8,41.9-87.6,41.9-87.7,41.9-87.8,42.0-87.7,42.0-87.8,42.0-87.9
0,1,CULEX PIPIENS/RESTUANS,T002,86.0,63.5,75.0,7.0,55.5,64.0,0.0,10.0,0.0,NaN,0.0,0.00,29.310,29.98,9.15,18.0,10.2,15.10,June,42.0-87.8,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0
1,2,CULEX RESTUANS,T002,86.0,63.5,75.0,7.0,55.5,64.0,0.0,10.0,0.0,NaN,0.0,0.00,29.310,29.98,9.15,18.0,10.2,15.10,June,42.0-87.8,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0
2,3,CULEX PIPIENS,T002,86.0,63.5,75.0,7.0,55.5,64.0,0.0,10.0,0.0,NaN,0.0,0.00,29.310,29.98,9.15,18.0,10.2,15.10,June,42.0-87.8,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0
3,4,CULEX SALINARIUS,T002,86.0,63.5,75.0,7.0,55.5,64.0,0.0,10.0,0.0,NaN,0.0,0.00,29.310,29.98,9.15,18.0,10.2,15.10,June,42.0-87.8,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0
4,5,CULEX TERRITANS,T002,86.0,63.5,75.0,7.0,55.5,64.0,0.0,10.0,0.0,NaN,0.0,0.00,29.310,29.98,9.15,18.0,10.2,15.10,June,42.0-87.8,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0
5,6,CULEX TARSALIS,T002,86.0,63.5,75.0,7.0,55.5,64.0,0.0,10.0,0.0,NaN,0.0,0.00,29.310,29.98,9.15,18.0,10.2,15.10,June,42.0-87.8,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0
6,7,UNSPECIFIED CULEX,T002,86.0,63.5,75.0,7.0,55.5,64.0,0.0,10.0,0.0,NaN,0.0,0.00,29.310,29.98,9.15,18.0,10.2,15.10,June,42.0-87.8,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,1,0
7,8,CULEX ERRATICUS,T002,86.0,63.5,75.0,7.0,55.5,64.0,0.0,10.0,0.0,NaN,0.0,0.00,29.310,29.98,9.15,18.0,10.2,15.10,June,42.0-87.8,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0
8,9,CULEX PIPIENS/RESTUANS,T007,86.0,63.5,75.0,7.0,55.5,64.0,0.0,10.0,0.0,NaN,0.0,0.00,29.310,29.98,9.15,18.0,10.2,15.10,June,42.0-87.8,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0
9,10,CULEX RESTUANS,T007,86.0,63.5,75.0,7.0,55.5,64.0,0.0,10.0,0.0,NaN,0.0,0.00,29.310,29.98,9.15,18.0,10.2,15.10,June,42.0-87.8,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0
10,11,CULEX PIPIENS,T007,86.0,63.5,75.0,7.0,55.5,64.0,0.0,10.0,0.0,NaN,0.0,0.00,29.310,29.98,9.15,18.0,10.2,15.10,June,42.0-87.8,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0
11,12,CULEX SALINARIUS,T007,86.0,63.5,75.0,7.0,55.5,64.0,0.0,10.0,0.0,NaN,0.0,0.00,29.310,29.98,9.15,18.0,10.2,15.10,June,42.0-87.8,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0
12,13,CULEX TERRITANS,T007,86.0,63.5,75.0,7.0,55.5,64.0,0.0,10.0,0.0,NaN,0.0,0.00,29.310,29.98,9.15,18.0,10.2,15.10,June,42.0-87.8,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0
13,14,CULEX TARSALIS,T007,86.0,63.5,75.0,7.0,55.5,64.0,0.0,10.0,0.0,NaN,0.0,0.00,29.310,29.98,9.15,18.0,10.2,15.10,June,42.0-87.8,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0
14,15,UNSPECIFIED CULEX,T007,86.0,63.5,75.0,7.0,55.5,64.0,0.0,10.0,0.0,NaN,0.0,0.00,29.310,29.98,9.15,18.0,10.2,15.10,June,42.0-87.8,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,1,0
15,16,CULEX ERRATICUS,T007,86.0,63.5,75.0,7.0,55.5,64.0,0.0,10.0,0.0,NaN,0.0,0.00,29.310,29.98,9.15,18.0,10.2,15.10,June,42.0-87.8,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0
16,17,CULEX PIPIENS/RESTUANS,T015,86.0,63.5,75.0,7.0,55.5,64.0,0.0,10.0,0.0,NaN,0.0,0.00,29.310,29.98,9.15,18.0,10.2,15.10,June,42.0-87.8,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0
17,18,CULEX RESTUANS,T015,86.0,63.5,75.0,7.0,55.5,64.0,0.0,10.0,0.0,NaN,0.0,0.00,29.310,29.98,9.15,18.0,10.2,15.10,June,42.0-87.8,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0
18,19,CULEX PIPIENS,T015,86.0,63.5,75.0,7.0,55.5,64.0,0.0,10.0,0.0,NaN,0.0,0.00,29.310,29.98,9.15,18.0,10.2,15.10,June,42.0-87.8,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0
19,20,CULEX SALINARIUS,T015,86.0,63.5,75.0,7.0,55.5,64.0,0.0,10.0,0.0,NaN,0.0,0.00,29.310,29.98,9.15,18.0,10.2,15.10,June,42.0-87.8,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0
20,21,CULEX TERRITANS,T015,86.0,63.5,75.0,7.0,55.5,64.0,0.0,10.0,0.0,NaN,0.0,0.00,29.310,29.98,9.15,18.0,10.2,15.10,June,42.0-87.8,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0
21,22,CULEX TARSALIS,T015,86.0,63.5,75.0,7.0,55.5,64.0,0.0,10.0,0.0,NaN,0.0,0.00,29.310,29.98,9.15,18.0,10.2,15.10,June,42.0-87.8,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0
22,23,UNSPECIFIED CULEX,T015,86.0,63.5,75.0,7.0,55.5,64.0,0.0,10.0,0.0,NaN,0.0,0.00,29.310,29.98,9.15,18.0,10.2,15.10,June,42.0-87.8,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,1,0
23,24,CULEX ERRATICUS,T015,86.0,63.5,75.0,7.0,55.5,64.0,0.0,10.0,0.0,NaN,0.0,0.00,29.310,29.98,9.15,18.0,10.2,15.10,June,42.0-87.8,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0
24,25,CULEX PIPIENS/RESTUANS,T045,86.0,63.5,75.0,7.0,55.5,64.0,0.0,10.0,0.0,NaN,0.0,0.00,29.310,29.98,9.15,18.0,10.2,15.10,June,41.9-87.7,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0
25,26,CULEX RESTUANS,T045,86.0,63.5,75.0,7.0,55.5,64.0,0.0,10.0,0.0,NaN,0.0,0.00,29.310,29.98,9.15,18.0,10.2,15.10,June,41.9-87.7,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0
26,27,CULEX PIPIENS,T045,86.0,63.5,75.0,7.0,55.5,64.0,0.0,10.0,0.0,NaN,0.0,0.00,29.310,29.98,9.15,18.0,10.2,15.10,June,41.9-87.7,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0
27,28,CULEX SALINARIUS,T045,86.0,63.5,75.0,7.0,55.5,64.0,0.0,10.0,0.0,NaN,0.0,0.00,29.310,29.98,9.15,18.0,10.2,15.10,June,41.9-87.7,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0
28,29,CULEX TERRITANS,T045,86.0,63.5,75.0,7.0,55.5,64.0,0.0,10.0,0.0,NaN,0.0,0.00,29.310,29.98,9.15,18.0,10.2,15.10,June,41.9-87.7,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0
29,30,CULEX TARSALIS,T045,86.0,63.5,75.0,7.0,55.5,64.0,0.0,10.0,0.0,NaN,0.0,0.00,29.310,29.98,9.15,18.0,10.2,15.10,June,41.9-87.7,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0
30,31,UNSPECIFIED CULEX,T045,86.0,63.5,75.0,7.0,55.5,64.0,0.0,10.0,0.0,NaN,0.0,0.00,29.310,29.98,9.15,18.0,10.2,15.10,June,41.9-87.7,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,1,0,0,0,0
31,32,CULEX ERRATICUS,T045,86.0,63.5,75.0,7.0,55.5,64.0,0.0,10.0,0.0,NaN,0.0,0.00,29.310,29.98,9.15,18.0,10.2,15.10,June,41.9-87.7,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0
32,33,CULEX PIPIENS/RESTUANS,T046,86.0,63.5,75.0,7.0,55.5,64.0,0.0,10.0,0.0,NaN,0.0,0.00,29.310,29.98,9.15,18.0,10.2,15.10,June,41.9-87.7,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0
33,34,CULEX RESTUANS,T046,86.0,63.5,75.0,7.0,55.5,64.0,0.0,10.0,0.0,NaN,0.0,0.00,29.310,29.98,9.15,18.0,10.2,15.10,June,41.9-87.7,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0
34,35,CULEX PIPIENS,T046,86.0,63.5,75.0,7.0,55.5,64.0,0.0,10.0,0.0,NaN,0.0,0.00,29.310,29.98,9.15,18.0,10.2,15.10,June,41.9-87.7,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0
35,36,CULEX SALINARIUS,T046,86.0,63.5,75.0,7.0,55.5,64.0,0.0,10.0,0.0,NaN,0.0,0.00,29.310,29.98,9.15,18.0,10.2,15.10,June,41.9-87.7,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0
36,37,CULEX TERRITANS,T046,86.0,63.5,75.0,7.0,55.5,64.0,0.0,10.0,0.0,NaN,0.0,0.00,29.310,29.98,9.15,18.0,10.2,15.10,June,41.9-87.7,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0
37,38,CULEX TARSALIS,T046,86.0,63.5,75.0,7.0,55.5,64.0,0.0,10.0,0.0,NaN,0.0,0.00,29.310,29.98,9.15,18.0,10.2,15.10,June,41.9-87.7,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0
38,39,UNSPECIFIED CULEX,T046,86.0,63.5,75.0,7.0,55.5,64.0,0.0,10.0,0.0,NaN,0.0,0.00,29.310,29.98,9.15,18.0,10.2,15.10,June,41.9-87.7,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,1,0,0,0,0
39,40,CULEX ERRATICUS,T046,86.0,63.5,75.0,7.0,55.5,64.0,0.0,10.0,0.0,NaN,0.0,0.00,29.310,29.98,9.15,18.0,10.2,15.10,June,41.9-87.7,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0
40,41,CULEX PIPIENS/RESTUANS,T048,86.0,63.5,75.0,7.0,55.5,64.0,0.0,10.0,0.0,NaN,0.0,0.00,29.310,29.98,9.15,18.0,10.2,15.10,June,41.9-87.7,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0
41,42,CULEX RESTUANS,T048,86.0,63.5,75.0,7.0,55.5,64.0,0.0,10.0,0.0,NaN,0.0,0.00,29.310,29.98,9.15,18.0,10.2,15.10,June,41.9-87.7,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0
42,43,CULEX PIPIENS,T048,86.0,63.5,75.0,7.0,55.5,64.0,0.0,10.0,0.0,NaN,0.0,0.00,29.310,29.98,9.15,18.0,10.2,15.10,June,41.9-87.7,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0
43,44,CULEX SALINARIUS,T048,86.0,63.5,75.0,7.0,55.5,64.0,0.0,10.0,0.0,NaN,0.0,0.00,29.310,29.98,9.15,18.0,10.2,15.10,June,41.9-87.7,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0
44,45,CULEX TERRITANS,T048,86.0,63.5,75.0,7.0,55.5,64.0,0.0,10.0,0.0,NaN,0.0,0.00,29.310,29.98,9.15,18.0,10.2,15.10,June,41.9-87.7,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0
45,46,CULEX TARSALIS,T048,86.0,63.5,75.0,7.0,55.5,64.0,0.0,10.0,0.0,NaN,0.0,0.00,29.310,29.98,9.15,18.0,10.2,15.10,June,41.9-87.7,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0
46,47,UNSPECIFIED CULEX,T048,86.0,63.5,75.0,7.0,55.5,64.0,0.0,10.0,0.0,NaN,0.0,0.00,29.310,29.98,9.15,18.0,10.2,15.10,June,41.9-87.7,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,1,0,0,0,0
47,48,CULEX ERRATICUS,T048,86.0,63.5,75.0,7.0,55.5,64.0,0.0,10.0,0.0,NaN,0.0,0.00,29.310,29.98,9.15,18.0,10.2,15.10,June,41.9-87.7,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0
48,49,CULEX PIPIENS/RESTUANS,T049,86.0,63.5,75.0,7.0,55.5,64.0,0.0,10.0,0.0,NaN,0.0,0.00,29.310,29.98,9.15,18.0,10.2,15.10,June,41.9-87.7,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0
49,50,CULEX RESTUANS,T049,86.0,63.5,75.0,7.0,55.5,64.0,0.0,10.0,0.0,NaN,0.0,0.00,29.310,29.98,9.15,18.0,10.2,15.10,June,41.9-87.7,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
116243,116244,UNSPECIFIED CULEX,T235,73.5,64.5,69.5,10.0,62.0,64.0,0.0,4.5,0.0,NaN,0.0,0.52,29.065,29.78,7.20,17.0,7.9,11.83,Oct,41.8-87.6,0,0,0,0,0,0,0,1,0,0,0,0,0,1,0,0,0,0,0,0,0,0
116244,116245,CULEX ERRATICUS,T235,73.5,64.5,69.5,10.0,62.0,64.0,0.0,4.5,0.0,NaN,0.0,0.52,29.065,29.78,7.20,17.0,7.9,11.83,Oct,41.8-87.6,1,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0
116245,116246,CULEX PIPIENS/RESTUANS,T236,73.5,64.5,69.5,10.0,62.0,64.0,0.0,4.5,0.0,NaN,0.0,0.52,29.065,29.78,7.20,17.0,7.9,11.83,Oct,42.0-87.8,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0
116246,116247,CULEX RESTUANS,T236,73.5,64.5,69.5,10.0,62.0,64.0,0.0,4.5,0.0,NaN,0.0,0.52,29.065,29.78,7.20,17.0,7.9,11.83,Oct,42.0-87.8,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0
116247,116248,CULEX PIPIENS,T236,73.5,64.5,69.5,10.0,62.0,64.0,0.0,4.5,0.0,NaN,0.0,0.52,29.065,29.78,7.20,17.0,7.9,11.83,Oct,42.0-87.8,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0
116248,116249,CULEX SALINARIUS,T236,73.5,64.5,69.5,10.0,62.0,64.0,0.0,4.5,0.0,NaN,0.0,0.52,29.065,29.78,7.20,17.0,7.9,11.83,Oct,42.0-87.8,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0
116249,116250,CULEX TERRITANS,T236,73.5,64.5,69.5,10.0,62.0,64.0,0.0,4.5,0.0,NaN,0.0,0.52,29.065,29.78,7.20,17.0,7.9,11.83,Oct,42.0-87.8,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0
116250,116251,CULEX TARSALIS,T236,73.5,64.5,69.5,10.0,62.0,64.0,0.0,4.5,0.0,NaN,0.0,0.52,29.065,29.78,7.20,17.0,7.9,11.83,Oct,42.0-87.8,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0
116251,116252,UNSPECIFIED CULEX,T236,73.5,64.5,69.5,10.0,62.0,64.0,0.0,4.5,0.0,NaN,0.0,0.52,29.065,29.78,7.20,17.0,7.9,11.83,Oct,42.0-87.8,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,1,0
116252,116253,CULEX ERRATICUS,T236,73.5,64.5,69.5,10.0,62.0,64.0,0.0,4.5,0.0,NaN,0.0,0.52,29.065,29.78,7.20,17.0,7.9,11.83,Oct,42.0-87.8,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0
116253,116254,CULEX PIPIENS/RESTUANS,T237,73.5,64.5,69.5,10.0,62.0,64.0,0.0,4.5,0.0,NaN,0.0,0.52,29.065,29.78,7.20,17.0,7.9,11.83,Oct,41.7-87.7,0,0,1,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0
116254,116255,CULEX RESTUANS,T237,73.5,64.5,69.5,10.0,62.0,64.0,0.0,4.5,0.0,NaN,0.0,0.52,29.065,29.78,7.20,17.0,7.9,11.83,Oct,41.7-87.7,0,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0
116255,116256,CULEX PIPIENS,T237,73.5,64.5,69.5,10.0,62.0,64.0,0.0,4.5,0.0,NaN,0.0,0.52,29.065,29.78,7.20,17.0,7.9,11.83,Oct,41.7-87.7,0,1,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0
116256,116257,CULEX SALINARIUS,T237,73.5,64.5,69.5,10.0,62.0,64.0,0.0,4.5,0.0,NaN,0.0,0.52,29.065,29.78,7.20,17.0,7.9,11.83,Oct,41.7-87.7,0,0,0,0,1,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0
116257,116258,CULEX TERRITANS,T237,73.5,64.5,69.5,10.0,62.0,64.0,0.0,4.5,0.0,NaN,0.0,0.52,29.065,29.78,7.20,17.0,7.9,11.83,Oct,41.7-87.7,0,0,0,0,0,0,1,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0
116258,116259,CULEX TARSALIS,T237,73.5,64.5,69.5,10.0,62.0,64.0,0.0,4.5,0.0,NaN,0.0,0.52,29.065,29.78,7.20,17.0,7.9,11.83,Oct,41.7-87.7,0,0,0,0,0,1,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0
116259,116260,UNSPECIFIED CULEX,T237,73.5,64.5,69.5,10.0,62.0,64.0,0.0,4.5,0.0,NaN,0.0,0.52,29.065,29.78,7.20,17.0,7.9,11.83,Oct,41.7-87.7,0,0,0,0,0,0,0,1,0,0,0,0,1,0,0,0,0,0,0,0,0,0
116260,116261,CULEX ERRATICUS,T237,73.5,64.5,69.5,10.0,62.0,64.0,0.0,4.5,0.0,NaN,0.0,0.52,29.065,29.78,7.20,17.0,7.9,11.83,Oct,41.7-87.7,1,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0
116261,116262,CULEX PIPIENS/RESTUANS,T238,73.5,64.5,69.5,10.0,62.0,64.0,0.0,4.5,0.0,NaN,0.0,0.52,29.065,29.78,7.20,17.0,7.9,11.83,Oct,41.8-87.7,0,0,1,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0
116262,116263,CULEX RESTUANS,T238,73.5,64.5,69.5,10.0,62.0,64.0,0.0,4.5,0.0,NaN,0.0,0.52,29.065,29.78,7.20,17.0,7.9,11.83,Oct,41.8-87.7,0,0,0,1,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0
116263,116264,CULEX PIPIENS,T238,73.5,64.5,69.5,10.0,62.0,64.0,0.0,4.5,0.0,NaN,0.0,0.52,29.065,29.78,7.20,17.0,7.9,11.83,Oct,41.8-87.7,0,1,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0
116264,116265,CULEX SALINARIUS,T238,73.5,64.5,69.5,10.0,62.0,64.0,0.0,4.5,0.0,NaN,0.0,0.52,29.065,29.78,7.20,17.0,7.9,11.83,Oct,41.8-87.7,0,0,0,0,1,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0
116265,116266,CULEX TERRITANS,T238,73.5,64.5,69.5,10.0,62.0,64.0,0.0,4.5,0.0,NaN,0.0,0.52,29.065,29.78,7.20,17.0,7.9,11.83,Oct,41.8-87.7,0,0,0,0,0,0,1,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0
116266,116267,CULEX TARSALIS,T238,73.5,64.5,69.5,10.0,62.0,64.0,0.0,4.5,0.0,NaN,0.0,0.52,29.065,29.78,7.20,17.0,7.9,11.83,Oct,41.8-87.7,0,0,0,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0
116267,116268,UNSPECIFIED CULEX,T238,73.5,64.5,69.5,10.0,62.0,64.0,0.0,4.5,0.0,NaN,0.0,0.52,29.065,29.78,7.20,17.0,7.9,11.83,Oct,41.8-87.7,0,0,0,0,0,0,0,1,0,0,0,0,0,0,1,0,0,0,0,0,0,0
116268,116269,CULEX ERRATICUS,T238,73.5,64.5,69.5,10.0,62.0,64.0,0.0,4.5,0.0,NaN,0.0,0.52,29.065,29.78,7.20,17.0,7.9,11.83,Oct,41.8-87.7,1,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0
116269,116270,CULEX PIPIENS/RESTUANS,T065A,73.5,64.5,69.5,10.0,62.0,64.0,0.0,4.5,0.0,NaN,0.0,0.52,29.065,29.78,7.20,17.0,7.9,11.83,Oct,41.8-87.7,0,0,1,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0
116270,116271,CULEX RESTUANS,T065A,73.5,64.5,69.5,10.0,62.0,64.0,0.0,4.5,0.0,NaN,0.0,0.52,29.065,29.78,7.20,17.0,7.9,11.83,Oct,41.8-87.7,0,0,0,1,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0
116271,116272,CULEX PIPIENS,T065A,73.5,64.5,69.5,10.0,62.0,64.0,0.0,4.5,0.0,NaN,0.0,0.52,29.065,29.78,7.20,17.0,7.9,11.83,Oct,41.8-87.7,0,1,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0
116272,116273,CULEX SALINARIUS,T065A,73.5,64.5,69.5,10.0,62.0,64.0,0.0,4.5,0.0,NaN,0.0,0.52,29.065,29.78,7.20,17.0,7.9,11.83,Oct,41.8-87.7,0,0,0,0,1,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0
116273,116274,CULEX TERRITANS,T065A,73.5,64.5,69.5,10.0,62.0,64.0,0.0,4.5,0.0,NaN,0.0,0.52,29.065,29.78,7.20,17.0,7.9,11.83,Oct,41.8-87.7,0,0,0,0,0,0,1,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0
116274,116275,CULEX TARSALIS,T065A,73.5,64.5,69.5,10.0,62.0,64.0,0.0,4.5,0.0,NaN,0.0,0.52,29.065,29.78,7.20,17.0,7.9,11.83,Oct,41.8-87.7,0,0,0,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0
116275,116276,UNSPECIFIED CULEX,T065A,73.5,64.5,69.5,10.0,62.0,64.0,0.0,4.5,0.0,NaN,0.0,0.52,29.065,29.78,7.20,17.0,7.9,11.83,Oct,41.8-87.7,0,0,0,0,0,0,0,1,0,0,0,0,0,0,1,0,0,0,0,0,0,0
116276,116277,CULEX ERRATICUS,T065A,73.5,64.5,69.5,10.0,62.0,64.0,0.0,4.5,0.0,NaN,0.0,0.52,29.065,29.78,7.20,17.0,7.9,11.83,Oct,41.8-87.7,1,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0
116277,116278,CULEX PIPIENS/RESTUANS,T094B,73.5,64.5,69.5,10.0,62.0,64.0,0.0,4.5,0.0,NaN,0.0,0.52,29.065,29.78,7.20,17.0,7.9,11.83,Oct,41.7-87.7,0,0,1,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0
116278,116279,CULEX RESTUANS,T094B,73.5,64.5,69.5,10.0,62.0,64.0,0.0,4.5,0.0,NaN,0.0,0.52,29.065,29.78,7.20,17.0,7.9,11.83,Oct,41.7-87.7,0,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0
116279,116280,CULEX PIPIENS,T094B,73.5,64.5,69.5,10.0,62.0,64.0,0.0,4.5,0.0,NaN,0.0,0.52,29.065,29.78,7.20,17.0,7.9,11.83,Oct,41.7-87.7,0,1,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0
116280,116281,CULEX SALINARIUS,T094B,73.5,64.5,69.5,10.0,62.0,64.0,0.0,4.5,0.0,NaN,0.0,0.52,29.065,29.78,7.20,17.0,7.9,11.83,Oct,41.7-87.7,0,0,0,0,1,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0
116281,116282,CULEX TERRITANS,T094B,73.5,64.5,69.5,10.0,62.0,64.0,0.0,4.5,0.0,NaN,0.0,0.52,29.065,29.78,7.20,17.0,7.9,11.83,Oct,41.7-87.7,0,0,0,0,0,0,1,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0
116282,116283,CULEX TARSALIS,T094B,73.5,64.5,69.5,10.0,62.0,64.0,0.0,4.5,0.0,NaN,0.0,0.52,29.065,29.78,7.20,17.0,7.9,11.83,Oct,41.7-87.7,0,0,0,0,0,1,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0
116283,116284,UNSPECIFIED CULEX,T094B,73.5,64.5,69.5,10.0,62.0,64.0,0.0,4.5,0.0,NaN,0.0,0.52,29.065,29.78,7.20,17.0,7.9,11.83,Oct,41.7-87.7,0,0,0,0,0,0,0,1,0,0,0,0,1,0,0,0,0,0,0,0,0,0
116284,116285,CULEX ERRATICUS,T094B,73.5,64.5,69.5,10.0,62.0,64.0,0.0,4.5,0.0,NaN,0.0,0.52,29.065,29.78,7.20,17.0,7.9,11.83,Oct,41.7-87.7,1,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0
116285,116286,CULEX PIPIENS/RESTUANS,T054C,73.5,64.5,69.5,10.0,62.0,64.0,0.0,4.5,0.0,NaN,0.0,0.52,29.065,29.78,7.20,17.0,7.9,11.83,Oct,41.9-87.6,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0
116286,116287,CULEX RESTUANS,T054C,73.5,64.5,69.5,10.0,62.0,64.0,0.0,4.5,0.0,NaN,0.0,0.52,29.065,29.78,7.20,17.0,7.9,11.83,Oct,41.9-87.6,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0
116287,116288,CULEX PIPIENS,T054C,73.5,64.5,69.5,10.0,62.0,64.0,0.0,4.5,0.0,NaN,0.0,0.52,29.065,29.78,7.20,17.0,7.9,11.83,Oct,41.9-87.6,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0
116288,116289,CULEX SALINARIUS,T054C,73.5,64.5,69.5,10.0,62.0,64.0,0.0,4.5,0.0,NaN,0.0,0.52,29.065,29.78,7.20,17.0,7.9,11.83,Oct,41.9-87.6,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0
116289,116290,CULEX TERRITANS,T054C,73.5,64.5,69.5,10.0,62.0,64.0,0.0,4.5,0.0,NaN,0.0,0.52,29.065,29.78,7.20,17.0,7.9,11.83,Oct,41.9-87.6,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0
116290,116291,CULEX TARSALIS,T054C,73.5,64.5,69.5,10.0,62.0,64.0,0.0,4.5,0.0,NaN,0.0,0.52,29.065,29.78,7.20,17.0,7.9,11.83,Oct,41.9-87.6,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0
116291,116292,UNSPECIFIED CULEX,T054C,73.5,64.5,69.5,10.0,62.0,64.0,0.0,4.5,0.0,NaN,0.0,0.52,29.065,29.78,7.20,17.0,7.9,11.83,Oct,41.9-87.6,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0
116292,116293,CULEX ERRATICUS,T054C,73.5,64.5,69.5,10.0,62.0,64.0,0.0,4.5,0.0,NaN,0.0,0.52,29.065,29.78,7.20,17.0,7.9,11.83,Oct,41.9-87.6,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0

For the __Month__ column

In [39]:
df = onehot(df, 'Month')
df

,Id,Species,Trap,Tmax,Tmin,Tavg,Depart,DewPoint,WetBulb,Heat,Cool,Depth,Water1,SnowFall,PrecipTotal,StnPressure,SeaLevel,ResultSpeed,ResultDir,AvgSpeed,Daylight,Month,Lat&Long,CULEX ERRATICUS,CULEX PIPIENS,CULEX PIPIENS/RESTUANS,CULEX RESTUANS,CULEX SALINARIUS,CULEX TARSALIS,CULEX TERRITANS,UNSPECIFIED CULEX,41.6-87.5,41.6-87.6,41.7-87.5,41.7-87.6,41.7-87.7,41.8-87.6,41.8-87.7,41.8-87.8,41.9-87.6,41.9-87.7,41.9-87.8,42.0-87.7,42.0-87.8,42.0-87.9,Aug,July,June,Oct,Sept
0,1,CULEX PIPIENS/RESTUANS,T002,86.0,63.5,75.0,7.0,55.5,64.0,0.0,10.0,0.0,NaN,0.0,0.00,29.310,29.98,9.15,18.0,10.2,15.10,June,42.0-87.8,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,1,0,0
1,2,CULEX RESTUANS,T002,86.0,63.5,75.0,7.0,55.5,64.0,0.0,10.0,0.0,NaN,0.0,0.00,29.310,29.98,9.15,18.0,10.2,15.10,June,42.0-87.8,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,1,0,0
2,3,CULEX PIPIENS,T002,86.0,63.5,75.0,7.0,55.5,64.0,0.0,10.0,0.0,NaN,0.0,0.00,29.310,29.98,9.15,18.0,10.2,15.10,June,42.0-87.8,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,1,0,0
3,4,CULEX SALINARIUS,T002,86.0,63.5,75.0,7.0,55.5,64.0,0.0,10.0,0.0,NaN,0.0,0.00,29.310,29.98,9.15,18.0,10.2,15.10,June,42.0-87.8,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,1,0,0
4,5,CULEX TERRITANS,T002,86.0,63.5,75.0,7.0,55.5,64.0,0.0,10.0,0.0,NaN,0.0,0.00,29.310,29.98,9.15,18.0,10.2,15.10,June,42.0-87.8,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,1,0,0
5,6,CULEX TARSALIS,T002,86.0,63.5,75.0,7.0,55.5,64.0,0.0,10.0,0.0,NaN,0.0,0.00,29.310,29.98,9.15,18.0,10.2,15.10,June,42.0-87.8,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,1,0,0
6,7,UNSPECIFIED CULEX,T002,86.0,63.5,75.0,7.0,55.5,64.0,0.0,10.0,0.0,NaN,0.0,0.00,29.310,29.98,9.15,18.0,10.2,15.10,June,42.0-87.8,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,1,0,0
7,8,CULEX ERRATICUS,T002,86.0,63.5,75.0,7.0,55.5,64.0,0.0,10.0,0.0,NaN,0.0,0.00,29.310,29.98,9.15,18.0,10.2,15.10,June,42.0-87.8,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,1,0,0
8,9,CULEX PIPIENS/RESTUANS,T007,86.0,63.5,75.0,7.0,55.5,64.0,0.0,10.0,0.0,NaN,0.0,0.00,29.310,29.98,9.15,18.0,10.2,15.10,June,42.0-87.8,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,1,0,0
9,10,CULEX RESTUANS,T007,86.0,63.5,75.0,7.0,55.5,64.0,0.0,10.0,0.0,NaN,0.0,0.00,29.310,29.98,9.15,18.0,10.2,15.10,June,42.0-87.8,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,1,0,0
10,11,CULEX PIPIENS,T007,86.0,63.5,75.0,7.0,55.5,64.0,0.0,10.0,0.0,NaN,0.0,0.00,29.310,29.98,9.15,18.0,10.2,15.10,June,42.0-87.8,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,1,0,0
11,12,CULEX SALINARIUS,T007,86.0,63.5,75.0,7.0,55.5,64.0,0.0,10.0,0.0,NaN,0.0,0.00,29.310,29.98,9.15,18.0,10.2,15.10,June,42.0-87.8,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,1,0,0
12,13,CULEX TERRITANS,T007,86.0,63.5,75.0,7.0,55.5,64.0,0.0,10.0,0.0,NaN,0.0,0.00,29.310,29.98,9.15,18.0,10.2,15.10,June,42.0-87.8,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,1,0,0
13,14,CULEX TARSALIS,T007,86.0,63.5,75.0,7.0,55.5,64.0,0.0,10.0,0.0,NaN,0.0,0.00,29.310,29.98,9.15,18.0,10.2,15.10,June,42.0-87.8,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,1,0,0
14,15,UNSPECIFIED CULEX,T007,86.0,63.5,75.0,7.0,55.5,64.0,0.0,10.0,0.0,NaN,0.0,0.00,29.310,29.98,9.15,18.0,10.2,15.10,June,42.0-87.8,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,1,0,0
15,16,CULEX ERRATICUS,T007,86.0,63.5,75.0,7.0,55.5,64.0,0.0,10.0,0.0,NaN,0.0,0.00,29.310,29.98,9.15,18.0,10.2,15.10,June,42.0-87.8,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,1,0,0
16,17,CULEX PIPIENS/RESTUANS,T015,86.0,63.5,75.0,7.0,55.5,64.0,0.0,10.0,0.0,NaN,0.0,0.00,29.310,29.98,9.15,18.0,10.2,15.10,June,42.0-87.8,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,1,0,0
17,18,CULEX RESTUANS,T015,86.0,63.5,75.0,7.0,55.5,64.0,0.0,10.0,0.0,NaN,0.0,0.00,29.310,29.98,9.15,18.0,10.2,15.10,June,42.0-87.8,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,1,0,0
18,19,CULEX PIPIENS,T015,86.0,63.5,75.0,7.0,55.5,64.0,0.0,10.0,0.0,NaN,0.0,0.00,29.310,29.98,9.15,18.0,10.2,15.10,June,42.0-87.8,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,1,0,0
19,20,CULEX SALINARIUS,T015,86.0,63.5,75.0,7.0,55.5,64.0,0.0,10.0,0.0,NaN,0.0,0.00,29.310,29.98,9.15,18.0,10.2,15.10,June,42.0-87.8,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,1,0,0
20,21,CULEX TERRITANS,T015,86.0,63.5,75.0,7.0,55.5,64.0,0.0,10.0,0.0,NaN,0.0,0.00,29.310,29.98,9.15,18.0,10.2,15.10,June,42.0-87.8,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,1,0,0
21,22,CULEX TARSALIS,T015,86.0,63.5,75.0,7.0,55.5,64.0,0.0,10.0,0.0,NaN,0.0,0.00,29.310,29.98,9.15,18.0,10.2,15.10,June,42.0-87.8,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,1,0,0
22,23,UNSPECIFIED CULEX,T015,86.0,63.5,75.0,7.0,55.5,64.0,0.0,10.0,0.0,NaN,0.0,0.00,29.310,29.98,9.15,18.0,10.2,15.10,June,42.0-87.8,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,1,0,0
23,24,CULEX ERRATICUS,T015,86.0,63.5,75.0,7.0,55.5,64.0,0.0,10.0,0.0,NaN,0.0,0.00,29.310,29.98,9.15,18.0,10.2,15.10,June,42.0-87.8,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,1,0,0
24,25,CULEX PIPIENS/RESTUANS,T045,86.0,63.5,75.0,7.0,55.5,64.0,0.0,10.0,0.0,NaN,0.0,0.00,29.310,29.98,9.15,18.0,10.2,15.10,June,41.9-87.7,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,1,0,0
25,26,CULEX RESTUANS,T045,86.0,63.5,75.0,7.0,55.5,64.0,0.0,10.0,0.0,NaN,0.0,0.00,29.310,29.98,9.15,18.0,10.2,15.10,June,41.9-87.7,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,1,0,0
26,27,CULEX PIPIENS,T045,86.0,63.5,75.0,7.0,55.5,64.0,0.0,10.0,0.0,NaN,0.0,0.00,29.310,29.98,9.15,18.0,10.2,15.10,June,41.9-87.7,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,1,0,0
27,28,CULEX SALINARIUS,T045,86.0,63.5,75.0,7.0,55.5,64.0,0.0,10.0,0.0,NaN,0.0,0.00,29.310,29.98,9.15,18.0,10.2,15.10,June,41.9-87.7,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,1,0,0
28,29,CULEX TERRITANS,T045,86.0,63.5,75.0,7.0,55.5,64.0,0.0,10.0,0.0,NaN,0.0,0.00,29.310,29.98,9.15,18.0,10.2,15.10,June,41.9-87.7,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,1,0,0
29,30,CULEX TARSALIS,T045,86.0,63.5,75.0,7.0,55.5,64.0,0.0,10.0,0.0,NaN,0.0,0.00,29.310,29.98,9.15,18.0,10.2,15.10,June,41.9-87.7,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,1,0,0
30,31,UNSPECIFIED CULEX,T045,86.0,63.5,75.0,7.0,55.5,64.0,0.0,10.0,0.0,NaN,0.0,0.00,29.310,29.98,9.15,18.0,10.2,15.10,June,41.9-87.7,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,1,0,0
31,32,CULEX ERRATICUS,T045,86.0,63.5,75.0,7.0,55.5,64.0,0.0,10.0,0.0,NaN,0.0,0.00,29.310,29.98,9.15,18.0,10.2,15.10,June,41.9-87.7,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,1,0,0
32,33,CULEX PIPIENS/RESTUANS,T046,86.0,63.5,75.0,7.0,55.5,64.0,0.0,10.0,0.0,NaN,0.0,0.00,29.310,29.98,9.15,18.0,10.2,15.10,June,41.9-87.7,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,1,0,0
33,34,CULEX RESTUANS,T046,86.0,63.5,75.0,7.0,55.5,64.0,0.0,10.0,0.0,NaN,0.0,0.00,29.310,29.98,9.15,18.0,10.2,15.10,June,41.9-87.7,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,1,0,0
34,35,CULEX PIPIENS,T046,86.0,63.5,75.0,7.0,55.5,64.0,0.0,10.0,0.0,NaN,0.0,0.00,29.310,29.98,9.15,18.0,10.2,15.10,June,41.9-87.7,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,1,0,0
35,36,CULEX SALINARIUS,T046,86.0,63.5,75.0,7.0,55.5,64.0,0.0,10.0,0.0,NaN,0.0,0.00,29.310,29.98,9.15,18.0,10.2,15.10,June,41.9-87.7,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,1,0,0
36,37,CULEX TERRITANS,T046,86.0,63.5,75.0,7.0,55.5,64.0,0.0,10.0,0.0,NaN,0.0,0.00,29.310,29.98,9.15,18.0,10.2,15.10,June,41.9-87.7,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,1,0,0
37,38,CULEX TARSALIS,T046,86.0,63.5,75.0,7.0,55.5,64.0,0.0,10.0,0.0,NaN,0.0,0.00,29.310,29.98,9.15,18.0,10.2,15.10,June,41.9-87.7,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,1,0,0
38,39,UNSPECIFIED CULEX,T046,86.0,63.5,75.0,7.0,55.5,64.0,0.0,10.0,0.0,NaN,0.0,0.00,29.310,29.98,9.15,18.0,10.2,15.10,June,41.9-87.7,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,1,0,0
39,40,CULEX ERRATICUS,T046,86.0,63.5,75.0,7.0,55.5,64.0,0.0,10.0,0.0,NaN,0.0,0.00,29.310,29.98,9.15,18.0,10.2,15.10,June,41.9-87.7,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,1,0,0
40,41,CULEX PIPIENS/RESTUANS,T048,86.0,63.5,75.0,7.0,55.5,64.0,0.0,10.0,0.0,NaN,0.0,0.00,29.310,29.98,9.15,18.0,10.2,15.10,June,41.9-87.7,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,1,0,0
41,42,CULEX RESTUANS,T048,86.0,63.5,75.0,7.0,55.5,64.0,0.0,10.0,0.0,NaN,0.0,0.00,29.310,29.98,9.15,18.0,10.2,15.10,June,41.9-87.7,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,1,0,0
42,43,CULEX PIPIENS,T048,86.0,63.5,75.0,7.0,55.5,64.0,0.0,10.0,0.0,NaN,0.0,0.00,29.310,29.98,9.15,18.0,10.2,15.10,June,41.9-87.7,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,1,0,0
43,44,CULEX SALINARIUS,T048,86.0,63.5,75.0,7.0,55.5,64.0,0.0,10.0,0.0,NaN,0.0,0.00,29.310,29.98,9.15,18.0,10.2,15.10,June,41.9-87.7,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,1,0,0
44,45,CULEX TERRITANS,T048,86.0,63.5,75.0,7.0,55.5,64.0,0.0,10.0,0.0,NaN,0.0,0.00,29.310,29.98,9.15,18.0,10.2,15.10,June,41.9-87.7,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,1,0,0
45,46,CULEX TARSALIS,T048,86.0,63.5,75.0,7.0,55.5,64.0,0.0,10.0,0.0,NaN,0.0,0.00,29.310,29.98,9.15,18.0,10.2,15.10,June,41.9-87.7,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,1,0,0
46,47,UNSPECIFIED CULEX,T048,86.0,63.5,75.0,7.0,55.5,64.0,0.0,10.0,0.0,NaN,0.0,0.00,29.310,29.98,9.15,18.0,10.2,15.10,June,41.9-87.7,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,1,0,0
47,48,CULEX ERRATICUS,T048,86.0,63.5,75.0,7.0,55.5,64.0,0.0,10.0,0.0,NaN,0.0,0.00,29.310,29.98,9.15,18.0,10.2,15.10,June,41.9-87.7,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,1,0,0
48,49,CULEX PIPIENS/RESTUANS,T049,86.0,63.5,75.0,7.0,55.5,64.0,0.0,10.0,0.0,NaN,0.0,0.00,29.310,29.98,9.15,18.0,10.2,15.10,June,41.9-87.7,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,1,0,0
49,50,CULEX RESTUANS,T049,86.0,63.5,75.0,7.0,55.5,64.0,0.0,10.0,0.0,NaN,0.0,0.00,29.310,29.98,9.15,18.0,10.2,15.10,June,41.9-87.7,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
116243,116244,UNSPECIFIED CULEX,T235,73.5,64.5,69.5,10.0,62.0,64.0,0.0,4.5,0.0,NaN,0.0,0.52,29.065,29.78,7.20,17.0,7.9,11.83,Oct,41.8-87.6,0,0,0,0,0,0,0,1,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,1,0
116244,116245,CULEX ERRATICUS,T235,73.5,64.5,69.5,10.0,62.0,64.0,0.0,4.5,0.0,NaN,0.0,0.52,29.065,29.78,7.20,17.0,7.9,11.83,Oct,41.8-87.6,1,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,1,0
116245,116246,CULEX PIPIENS/RESTUANS,T236,73.5,64.5,69.5,10.0,62.0,64.0,0.0,4.5,0.0,NaN,0.0,0.52,29.065,29.78,7.20,17.0,7.9,11.83,Oct,42.0-87.8,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,1,0
116246,116247,CULEX RESTUANS,T236,73.5,64.5,69.5,10.0,62.0,64.0,0.0,4.5,0.0,NaN,0.0,0.52,29.065,29.78,7.20,17.0,7.9,11.83,Oct,42.0-87.8,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,1,0
116247,116248,CULEX PIPIENS,T236,73.5,64.5,69.5,10.0,62.0,64.0,0.0,4.5,0.0,NaN,0.0,0.52,29.065,29.78,7.20,17.0,7.9,11.83,Oct,42.0-87.8,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,1,0
116248,116249,CULEX SALINARIUS,T236,73.5,64.5,69.5,10.0,62.0,64.0,0.0,4.5,0.0,NaN,0.0,0.52,29.065,29.78,7.20,17.0,7.9,11.83,Oct,42.0-87.8,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,1,0
116249,116250,CULEX TERRITANS,T236,73.5,64.5,69.5,10.0,62.0,64.0,0.0,4.5,0.0,NaN,0.0,0.52,29.065,29.78,7.20,17.0,7.9,11.83,Oct,42.0-87.8,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,1,0
116250,116251,CULEX TARSALIS,T236,73.5,64.5,69.5,10.0,62.0,64.0,0.0,4.5,0.0,NaN,0.0,0.52,29.065,29.78,7.20,17.0,7.9,11.83,Oct,42.0-87.8,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,1,0
116251,116252,UNSPECIFIED CULEX,T236,73.5,64.5,69.5,10.0,62.0,64.0,0.0,4.5,0.0,NaN,0.0,0.52,29.065,29.78,7.20,17.0,7.9,11.83,Oct,42.0-87.8,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,1,0
116252,116253,CULEX ERRATICUS,T236,73.5,64.5,69.5,10.0,62.0,64.0,0.0,4.5,0.0,NaN,0.0,0.52,29.065,29.78,7.20,17.0,7.9,11.83,Oct,42.0-87.8,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,1,0
116253,116254,CULEX PIPIENS/RESTUANS,T237,73.5,64.5,69.5,10.0,62.0,64.0,0.0,4.5,0.0,NaN,0.0,0.52,29.065,29.78,7.20,17.0,7.9,11.83,Oct,41.7-87.7,0,0,1,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,1,0
116254,116255,CULEX RESTUANS,T237,73.5,64.5,69.5,10.0,62.0,64.0,0.0,4.5,0.0,NaN,0.0,0.52,29.065,29.78,7.20,17.0,7.9,11.83,Oct,41.7-87.7,0,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,1,0
116255,116256,CULEX PIPIENS,T237,73.5,64.5,69.5,10.0,62.0,64.0,0.0,4.5,0.0,NaN,0.0,0.52,29.065,29.78,7.20,17.0,7.9,11.83,Oct,41.7-87.7,0,1,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,1,0
116256,116257,CULEX SALINARIUS,T237,73.5,64.5,69.5,10.0,62.0,64.0,0.0,4.5,0.0,NaN,0.0,0.52,29.065,29.78,7.20,17.0,7.9,11.83,Oct,41.7-87.7,0,0,0,0,1,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,1,0
116257,116258,CULEX TERRITANS,T237,73.5,64.5,69.5,10.0,62.0,64.0,0.0,4.5,0.0,NaN,0.0,0.52,29.065,29.78,7.20,17.0,7.9,11.83,Oct,41.7-87.7,0,0,0,0,0,0,1,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,1,0
116258,116259,CULEX TARSALIS,T237,73.5,64.5,69.5,10.0,62.0,64.0,0.0,4.5,0.0,NaN,0.0,0.52,29.065,29.78,7.20,17.0,7.9,11.83,Oct,41.7-87.7,0,0,0,0,0,1,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,1,0
116259,116260,UNSPECIFIED CULEX,T237,73.5,64.5,69.5,10.0,62.0,64.0,0.0,4.5,0.0,NaN,0.0,0.52,29.065,29.78,7.20,17.0,7.9,11.83,Oct,41.7-87.7,0,0,0,0,0,0,0,1,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,1,0
116260,116261,CULEX ERRATICUS,T237,73.5,64.5,69.5,10.0,62.0,64.0,0.0,4.5,0.0,NaN,0.0,0.52,29.065,29.78,7.20,17.0,7.9,11.83,Oct,41.7-87.7,1,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,1,0
116261,116262,CULEX PIPIENS/RESTUANS,T238,73.5,64.5,69.5,10.0,62.0,64.0,0.0,4.5,0.0,NaN,0.0,0.52,29.065,29.78,7.20,17.0,7.9,11.83,Oct,41.8-87.7,0,0,1,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,1,0
116262,116263,CULEX RESTUANS,T238,73.5,64.5,69.5,10.0,62.0,64.0,0.0,4.5,0.0,NaN,0.0,0.52,29.065,29.78,7.20,17.0,7.9,11.83,Oct,41.8-87.7,0,0,0,1,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,1,0
116263,116264,CULEX PIPIENS,T238,73.5,64.5,69.5,10.0,62.0,64.0,0.0,4.5,0.0,NaN,0.0,0.52,29.065,29.78,7.20,17.0,7.9,11.83,Oct,41.8-87.7,0,1,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,1,0
116264,116265,CULEX SALINARIUS,T238,73.5,64.5,69.5,10.0,62.0,64.0,0.0,4.5,0.0,NaN,0.0,0.52,29.065,29.78,7.20,17.0,7.9,11.83,Oct,41.8-87.7,0,0,0,0,1,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,1,0
116265,116266,CULEX TERRITANS,T238,73.5,64.5,69.5,10.0,62.0,64.0,0.0,4.5,0.0,NaN,0.0,0.52,29.065,29.78,7.20,17.0,7.9,11.83,Oct,41.8-87.7,0,0,0,0,0,0,1,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,1,0
116266,116267,CULEX TARSALIS,T238,73.5,64.5,69.5,10.0,62.0,64.0,0.0,4.5,0.0,NaN,0.0,0.52,29.065,29.78,7.20,17.0,7.9,11.83,Oct,41.8-87.7,0,0,0,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,1,0
116267,116268,UNSPECIFIED CULEX,T238,73.5,64.5,69.5,10.0,62.0,64.0,0.0,4.5,0.0,NaN,0.0,0.52,29.065,29.78,7.20,17.0,7.9,11.83,Oct,41.8-87.7,0,0,0,0,0,0,0,1,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,1,0
116268,116269,CULEX ERRATICUS,T238,73.5,64.5,69.5,10.0,62.0,64.0,0.0,4.5,0.0,NaN,0.0,0.52,29.065,29.78,7.20,17.0,7.9,11.83,Oct,41.8-87.7,1,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,1,0
116269,116270,CULEX PIPIENS/RESTUANS,T065A,73.5,64.5,69.5,10.0,62.0,64.0,0.0,4.5,0.0,NaN,0.0,0.52,29.065,29.78,7.20,17.0,7.9,11.83,Oct,41.8-87.7,0,0,1,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,1,0
116270,116271,CULEX RESTUANS,T065A,73.5,64.5,69.5,10.0,62.0,64.0,0.0,4.5,0.0,NaN,0.0,0.52,29.065,29.78,7.20,17.0,7.9,11.83,Oct,41.8-87.7,0,0,0,1,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,1,0
116271,116272,CULEX PIPIENS,T065A,73.5,64.5,69.5,10.0,62.0,64.0,0.0,4.5,0.0,NaN,0.0,0.52,29.065,29.78,7.20,17.0,7.9,11.83,Oct,41.8-87.7,0,1,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,1,0
116272,116273,CULEX SALINARIUS,T065A,73.5,64.5,69.5,10.0,62.0,64.0,0.0,4.5,0.0,NaN,0.0,0.52,29.065,29.78,7.20,17.0,7.9,11.83,Oct,41.8-87.7,0,0,0,0,1,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,1,0
116273,116274,CULEX TERRITANS,T065A,73.5,64.5,69.5,10.0,62.0,64.0,0.0,4.5,0.0,NaN,0.0,0.52,29.065,29.78,7.20,17.0,7.9,11.83,Oct,41.8-87.7,0,0,0,0,0,0,1,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,1,0
116274,116275,CULEX TARSALIS,T065A,73.5,64.5,69.5,10.0,62.0,64.0,0.0,4.5,0.0,NaN,0.0,0.52,29.065,29.78,7.20,17.0,7.9,11.83,Oct,41.8-87.7,0,0,0,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,1,0
116275,116276,UNSPECIFIED CULEX,T065A,73.5,64.5,69.5,10.0,62.0,64.0,0.0,4.5,0.0,NaN,0.0,0.52,29.065,29.78,7.20,17.0,7.9,11.83,Oct,41.8-87.7,0,0,0,0,0,0,0,1,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,1,0
116276,116277,CULEX ERRATICUS,T065A,73.5,64.5,69.5,10.0,62.0,64.0,0.0,4.5,0.0,NaN,0.0,0.52,29.065,29.78,7.20,17.0,7.9,11.83,Oct,41.8-87.7,1,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,1,0
116277,116278,CULEX PIPIENS/RESTUANS,T094B,73.5,64.5,69.5,10.0,62.0,64.0,0.0,4.5,0.0,NaN,0.0,0.52,29.065,29.78,7.20,17.0,7.9,11.83,Oct,41.7-87.7,0,0,1,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,1,0
116278,116279,CULEX RESTUANS,T094B,73.5,64.5,69.5,10.0,62.0,64.0,0.0,4.5,0.0,NaN,0.0,0.52,29.065,29.78,7.20,17.0,7.9,11.83,Oct,41.7-87.7,0,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,1,0
116279,116280,CULEX PIPIENS,T094B,73.5,64.5,69.5,10.0,62.0,64.0,0.0,4.5,0.0,NaN,0.0,0.52,29.065,29.78,7.20,17.0,7.9,11.83,Oct,41.7-87.7,0,1,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,1,0
116280,116281,CULEX SALINARIUS,T094B,73.5,64.5,69.5,10.0,62.0,64.0,0.0,4.5,0.0,NaN,0.0,0.52,29.065,29.78,7.20,17.0,7.9,11.83,Oct,41.7-87.7,0,0,0,0,1,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,1,0
116281,116282,CULEX TERRITANS,T094B,73.5,64.5,69.5,10.0,62.0,64.0,0.0,4.5,0.0,NaN,0.0,0.52,29.065,29.78,7.20,17.0,7.9,11.83,Oct,41.7-87.7,0,0,0,0,0,0,1,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,1,0
116282,116283,CULEX TARSALIS,T094B,73.5,64.5,69.5,10.0,62.0,64.0,0.0,4.5,0.0,NaN,0.0,0.52,29.065,29.78,7.20,17.0,7.9,11.83,Oct,41.7-87.7,0,0,0,0,0,1,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,1,0
116283,116284,UNSPECIFIED CULEX,T094B,73.5,64.5,69.5,10.0,62.0,64.0,0.0,4.5,0.0,NaN,0.0,0.52,29.065,29.78,7.20,17.0,7.9,11.83,Oct,41.7-87.7,0,0,0,0,0,0,0,1,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,1,0
116284,116285,CULEX ERRATICUS,T094B,73.5,64.5,69.5,10.0,62.0,64.0,0.0,4.5,0.0,NaN,0.0,0.52,29.065,29.78,7.20,17.0,7.9,11.83,Oct,41.7-87.7,1,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,1,0
116285,116286,CULEX PIPIENS/RESTUANS,T054C,73.5,64.5,69.5,10.0,62.0,64.0,0.0,4.5,0.0,NaN,0.0,0.52,29.065,29.78,7.20,17.0,7.9,11.83,Oct,41.9-87.6,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,1,0
116286,116287,CULEX RESTUANS,T054C,73.5,64.5,69.5,10.0,62.0,64.0,0.0,4.5,0.0,NaN,0.0,0.52,29.065,29.78,7.20,17.0,7.9,11.83,Oct,41.9-87.6,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,1,0
116287,116288,CULEX PIPIENS,T054C,73.5,64.5,69.5,10.0,62.0,64.0,0.0,4.5,0.0,NaN,0.0,0.52,29.065,29.78,7.20,17.0,7.9,11.83,Oct,41.9-87.6,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,1,0
116288,116289,CULEX SALINARIUS,T054C,73.5,64.5,69.5,10.0,62.0,64.0,0.0,4.5,0.0,NaN,0.0,0.52,29.065,29.78,7.20,17.0,7.9,11.83,Oct,41.9-87.6,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,1,0
116289,116290,CULEX TERRITANS,T054C,73.5,64.5,69.5,10.0,62.0,64.0,0.0,4.5,0.0,NaN,0.0,0.52,29.065,29.78,7.20,17.0,7.9,11.83,Oct,41.9-87.6,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,1,0
116290,116291,CULEX TARSALIS,T054C,73.5,64.5,69.5,10.0,62.0,64.0,0.0,4.5,0.0,NaN,0.0,0.52,29.065,29.78,7.20,17.0,7.9,11.83,Oct,41.9-87.6,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,1,0
116291,116292,UNSPECIFIED CULEX,T054C,73.5,64.5,69.5,10.0,62.0,64.0,0.0,4.5,0.0,NaN,0.0,0.52,29.065,29.78,7.20,17.0,7.9,11.83,Oct,41.9-87.6,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,1,0
116292,116293,CULEX ERRATICUS,T054C,73.5,64.5,69.5,10.0,62.0,64.0,0.0,4.5,0.0,NaN,0.0,0.52,29.065,29.78,7.20,17.0,7.9,11.83,Oct,41.9-87.6,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,1,0

In [40]:
# Renaming the months number to their apppropriate names
df.rename(columns={5:'May', 
                   6:'June', 
                   7:'July', 
                   8:'Aug', 
                   9:'Sept', 
                   10:'Oct'}, inplace=True)
df

,Id,Species,Trap,Tmax,Tmin,Tavg,Depart,DewPoint,WetBulb,Heat,Cool,Depth,Water1,SnowFall,PrecipTotal,StnPressure,SeaLevel,ResultSpeed,ResultDir,AvgSpeed,Daylight,Month,Lat&Long,CULEX ERRATICUS,CULEX PIPIENS,CULEX PIPIENS/RESTUANS,CULEX RESTUANS,CULEX SALINARIUS,CULEX TARSALIS,CULEX TERRITANS,UNSPECIFIED CULEX,41.6-87.5,41.6-87.6,41.7-87.5,41.7-87.6,41.7-87.7,41.8-87.6,41.8-87.7,41.8-87.8,41.9-87.6,41.9-87.7,41.9-87.8,42.0-87.7,42.0-87.8,42.0-87.9,Aug,July,June,Oct,Sept
0,1,CULEX PIPIENS/RESTUANS,T002,86.0,63.5,75.0,7.0,55.5,64.0,0.0,10.0,0.0,NaN,0.0,0.00,29.310,29.98,9.15,18.0,10.2,15.10,June,42.0-87.8,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,1,0,0
1,2,CULEX RESTUANS,T002,86.0,63.5,75.0,7.0,55.5,64.0,0.0,10.0,0.0,NaN,0.0,0.00,29.310,29.98,9.15,18.0,10.2,15.10,June,42.0-87.8,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,1,0,0
2,3,CULEX PIPIENS,T002,86.0,63.5,75.0,7.0,55.5,64.0,0.0,10.0,0.0,NaN,0.0,0.00,29.310,29.98,9.15,18.0,10.2,15.10,June,42.0-87.8,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,1,0,0
3,4,CULEX SALINARIUS,T002,86.0,63.5,75.0,7.0,55.5,64.0,0.0,10.0,0.0,NaN,0.0,0.00,29.310,29.98,9.15,18.0,10.2,15.10,June,42.0-87.8,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,1,0,0
4,5,CULEX TERRITANS,T002,86.0,63.5,75.0,7.0,55.5,64.0,0.0,10.0,0.0,NaN,0.0,0.00,29.310,29.98,9.15,18.0,10.2,15.10,June,42.0-87.8,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,1,0,0
5,6,CULEX TARSALIS,T002,86.0,63.5,75.0,7.0,55.5,64.0,0.0,10.0,0.0,NaN,0.0,0.00,29.310,29.98,9.15,18.0,10.2,15.10,June,42.0-87.8,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,1,0,0
6,7,UNSPECIFIED CULEX,T002,86.0,63.5,75.0,7.0,55.5,64.0,0.0,10.0,0.0,NaN,0.0,0.00,29.310,29.98,9.15,18.0,10.2,15.10,June,42.0-87.8,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,1,0,0
7,8,CULEX ERRATICUS,T002,86.0,63.5,75.0,7.0,55.5,64.0,0.0,10.0,0.0,NaN,0.0,0.00,29.310,29.98,9.15,18.0,10.2,15.10,June,42.0-87.8,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,1,0,0
8,9,CULEX PIPIENS/RESTUANS,T007,86.0,63.5,75.0,7.0,55.5,64.0,0.0,10.0,0.0,NaN,0.0,0.00,29.310,29.98,9.15,18.0,10.2,15.10,June,42.0-87.8,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,1,0,0
9,10,CULEX RESTUANS,T007,86.0,63.5,75.0,7.0,55.5,64.0,0.0,10.0,0.0,NaN,0.0,0.00,29.310,29.98,9.15,18.0,10.2,15.10,June,42.0-87.8,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,1,0,0
10,11,CULEX PIPIENS,T007,86.0,63.5,75.0,7.0,55.5,64.0,0.0,10.0,0.0,NaN,0.0,0.00,29.310,29.98,9.15,18.0,10.2,15.10,June,42.0-87.8,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,1,0,0
11,12,CULEX SALINARIUS,T007,86.0,63.5,75.0,7.0,55.5,64.0,0.0,10.0,0.0,NaN,0.0,0.00,29.310,29.98,9.15,18.0,10.2,15.10,June,42.0-87.8,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,1,0,0
12,13,CULEX TERRITANS,T007,86.0,63.5,75.0,7.0,55.5,64.0,0.0,10.0,0.0,NaN,0.0,0.00,29.310,29.98,9.15,18.0,10.2,15.10,June,42.0-87.8,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,1,0,0
13,14,CULEX TARSALIS,T007,86.0,63.5,75.0,7.0,55.5,64.0,0.0,10.0,0.0,NaN,0.0,0.00,29.310,29.98,9.15,18.0,10.2,15.10,June,42.0-87.8,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,1,0,0
14,15,UNSPECIFIED CULEX,T007,86.0,63.5,75.0,7.0,55.5,64.0,0.0,10.0,0.0,NaN,0.0,0.00,29.310,29.98,9.15,18.0,10.2,15.10,June,42.0-87.8,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,1,0,0
15,16,CULEX ERRATICUS,T007,86.0,63.5,75.0,7.0,55.5,64.0,0.0,10.0,0.0,NaN,0.0,0.00,29.310,29.98,9.15,18.0,10.2,15.10,June,42.0-87.8,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,1,0,0
16,17,CULEX PIPIENS/RESTUANS,T015,86.0,63.5,75.0,7.0,55.5,64.0,0.0,10.0,0.0,NaN,0.0,0.00,29.310,29.98,9.15,18.0,10.2,15.10,June,42.0-87.8,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,1,0,0
17,18,CULEX RESTUANS,T015,86.0,63.5,75.0,7.0,55.5,64.0,0.0,10.0,0.0,NaN,0.0,0.00,29.310,29.98,9.15,18.0,10.2,15.10,June,42.0-87.8,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,1,0,0
18,19,CULEX PIPIENS,T015,86.0,63.5,75.0,7.0,55.5,64.0,0.0,10.0,0.0,NaN,0.0,0.00,29.310,29.98,9.15,18.0,10.2,15.10,June,42.0-87.8,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,1,0,0
19,20,CULEX SALINARIUS,T015,86.0,63.5,75.0,7.0,55.5,64.0,0.0,10.0,0.0,NaN,0.0,0.00,29.310,29.98,9.15,18.0,10.2,15.10,June,42.0-87.8,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,1,0,0
20,21,CULEX TERRITANS,T015,86.0,63.5,75.0,7.0,55.5,64.0,0.0,10.0,0.0,NaN,0.0,0.00,29.310,29.98,9.15,18.0,10.2,15.10,June,42.0-87.8,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,1,0,0
21,22,CULEX TARSALIS,T015,86.0,63.5,75.0,7.0,55.5,64.0,0.0,10.0,0.0,NaN,0.0,0.00,29.310,29.98,9.15,18.0,10.2,15.10,June,42.0-87.8,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,1,0,0
22,23,UNSPECIFIED CULEX,T015,86.0,63.5,75.0,7.0,55.5,64.0,0.0,10.0,0.0,NaN,0.0,0.00,29.310,29.98,9.15,18.0,10.2,15.10,June,42.0-87.8,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,1,0,0
23,24,CULEX ERRATICUS,T015,86.0,63.5,75.0,7.0,55.5,64.0,0.0,10.0,0.0,NaN,0.0,0.00,29.310,29.98,9.15,18.0,10.2,15.10,June,42.0-87.8,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,1,0,0
24,25,CULEX PIPIENS/RESTUANS,T045,86.0,63.5,75.0,7.0,55.5,64.0,0.0,10.0,0.0,NaN,0.0,0.00,29.310,29.98,9.15,18.0,10.2,15.10,June,41.9-87.7,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,1,0,0
25,26,CULEX RESTUANS,T045,86.0,63.5,75.0,7.0,55.5,64.0,0.0,10.0,0.0,NaN,0.0,0.00,29.310,29.98,9.15,18.0,10.2,15.10,June,41.9-87.7,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,1,0,0
26,27,CULEX PIPIENS,T045,86.0,63.5,75.0,7.0,55.5,64.0,0.0,10.0,0.0,NaN,0.0,0.00,29.310,29.98,9.15,18.0,10.2,15.10,June,41.9-87.7,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,1,0,0
27,28,CULEX SALINARIUS,T045,86.0,63.5,75.0,7.0,55.5,64.0,0.0,10.0,0.0,NaN,0.0,0.00,29.310,29.98,9.15,18.0,10.2,15.10,June,41.9-87.7,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,1,0,0
28,29,CULEX TERRITANS,T045,86.0,63.5,75.0,7.0,55.5,64.0,0.0,10.0,0.0,NaN,0.0,0.00,29.310,29.98,9.15,18.0,10.2,15.10,June,41.9-87.7,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,1,0,0
29,30,CULEX TARSALIS,T045,86.0,63.5,75.0,7.0,55.5,64.0,0.0,10.0,0.0,NaN,0.0,0.00,29.310,29.98,9.15,18.0,10.2,15.10,June,41.9-87.7,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,1,0,0
30,31,UNSPECIFIED CULEX,T045,86.0,63.5,75.0,7.0,55.5,64.0,0.0,10.0,0.0,NaN,0.0,0.00,29.310,29.98,9.15,18.0,10.2,15.10,June,41.9-87.7,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,1,0,0
31,32,CULEX ERRATICUS,T045,86.0,63.5,75.0,7.0,55.5,64.0,0.0,10.0,0.0,NaN,0.0,0.00,29.310,29.98,9.15,18.0,10.2,15.10,June,41.9-87.7,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,1,0,0
32,33,CULEX PIPIENS/RESTUANS,T046,86.0,63.5,75.0,7.0,55.5,64.0,0.0,10.0,0.0,NaN,0.0,0.00,29.310,29.98,9.15,18.0,10.2,15.10,June,41.9-87.7,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,1,0,0
33,34,CULEX RESTUANS,T046,86.0,63.5,75.0,7.0,55.5,64.0,0.0,10.0,0.0,NaN,0.0,0.00,29.310,29.98,9.15,18.0,10.2,15.10,June,41.9-87.7,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,1,0,0
34,35,CULEX PIPIENS,T046,86.0,63.5,75.0,7.0,55.5,64.0,0.0,10.0,0.0,NaN,0.0,0.00,29.310,29.98,9.15,18.0,10.2,15.10,June,41.9-87.7,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,1,0,0
35,36,CULEX SALINARIUS,T046,86.0,63.5,75.0,7.0,55.5,64.0,0.0,10.0,0.0,NaN,0.0,0.00,29.310,29.98,9.15,18.0,10.2,15.10,June,41.9-87.7,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,1,0,0
36,37,CULEX TERRITANS,T046,86.0,63.5,75.0,7.0,55.5,64.0,0.0,10.0,0.0,NaN,0.0,0.00,29.310,29.98,9.15,18.0,10.2,15.10,June,41.9-87.7,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,1,0,0
37,38,CULEX TARSALIS,T046,86.0,63.5,75.0,7.0,55.5,64.0,0.0,10.0,0.0,NaN,0.0,0.00,29.310,29.98,9.15,18.0,10.2,15.10,June,41.9-87.7,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,1,0,0
38,39,UNSPECIFIED CULEX,T046,86.0,63.5,75.0,7.0,55.5,64.0,0.0,10.0,0.0,NaN,0.0,0.00,29.310,29.98,9.15,18.0,10.2,15.10,June,41.9-87.7,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,1,0,0
39,40,CULEX ERRATICUS,T046,86.0,63.5,75.0,7.0,55.5,64.0,0.0,10.0,0.0,NaN,0.0,0.00,29.310,29.98,9.15,18.0,10.2,15.10,June,41.9-87.7,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,1,0,0
40,41,CULEX PIPIENS/RESTUANS,T048,86.0,63.5,75.0,7.0,55.5,64.0,0.0,10.0,0.0,NaN,0.0,0.00,29.310,29.98,9.15,18.0,10.2,15.10,June,41.9-87.7,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,1,0,0
41,42,CULEX RESTUANS,T048,86.0,63.5,75.0,7.0,55.5,64.0,0.0,10.0,0.0,NaN,0.0,0.00,29.310,29.98,9.15,18.0,10.2,15.10,June,41.9-87.7,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,1,0,0
42,43,CULEX PIPIENS,T048,86.0,63.5,75.0,7.0,55.5,64.0,0.0,10.0,0.0,NaN,0.0,0.00,29.310,29.98,9.15,18.0,10.2,15.10,June,41.9-87.7,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,1,0,0
43,44,CULEX SALINARIUS,T048,86.0,63.5,75.0,7.0,55.5,64.0,0.0,10.0,0.0,NaN,0.0,0.00,29.310,29.98,9.15,18.0,10.2,15.10,June,41.9-87.7,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,1,0,0
44,45,CULEX TERRITANS,T048,86.0,63.5,75.0,7.0,55.5,64.0,0.0,10.0,0.0,NaN,0.0,0.00,29.310,29.98,9.15,18.0,10.2,15.10,June,41.9-87.7,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,1,0,0
45,46,CULEX TARSALIS,T048,86.0,63.5,75.0,7.0,55.5,64.0,0.0,10.0,0.0,NaN,0.0,0.00,29.310,29.98,9.15,18.0,10.2,15.10,June,41.9-87.7,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,1,0,0
46,47,UNSPECIFIED CULEX,T048,86.0,63.5,75.0,7.0,55.5,64.0,0.0,10.0,0.0,NaN,0.0,0.00,29.310,29.98,9.15,18.0,10.2,15.10,June,41.9-87.7,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,1,0,0
47,48,CULEX ERRATICUS,T048,86.0,63.5,75.0,7.0,55.5,64.0,0.0,10.0,0.0,NaN,0.0,0.00,29.310,29.98,9.15,18.0,10.2,15.10,June,41.9-87.7,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,1,0,0
48,49,CULEX PIPIENS/RESTUANS,T049,86.0,63.5,75.0,7.0,55.5,64.0,0.0,10.0,0.0,NaN,0.0,0.00,29.310,29.98,9.15,18.0,10.2,15.10,June,41.9-87.7,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,1,0,0
49,50,CULEX RESTUANS,T049,86.0,63.5,75.0,7.0,55.5,64.0,0.0,10.0,0.0,NaN,0.0,0.00,29.310,29.98,9.15,18.0,10.2,15.10,June,41.9-87.7,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
116243,116244,UNSPECIFIED CULEX,T235,73.5,64.5,69.5,10.0,62.0,64.0,0.0,4.5,0.0,NaN,0.0,0.52,29.065,29.78,7.20,17.0,7.9,11.83,Oct,41.8-87.6,0,0,0,0,0,0,0,1,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,1,0
116244,116245,CULEX ERRATICUS,T235,73.5,64.5,69.5,10.0,62.0,64.0,0.0,4.5,0.0,NaN,0.0,0.52,29.065,29.78,7.20,17.0,7.9,11.83,Oct,41.8-87.6,1,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,1,0
116245,116246,CULEX PIPIENS/RESTUANS,T236,73.5,64.5,69.5,10.0,62.0,64.0,0.0,4.5,0.0,NaN,0.0,0.52,29.065,29.78,7.20,17.0,7.9,11.83,Oct,42.0-87.8,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,1,0
116246,116247,CULEX RESTUANS,T236,73.5,64.5,69.5,10.0,62.0,64.0,0.0,4.5,0.0,NaN,0.0,0.52,29.065,29.78,7.20,17.0,7.9,11.83,Oct,42.0-87.8,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,1,0
116247,116248,CULEX PIPIENS,T236,73.5,64.5,69.5,10.0,62.0,64.0,0.0,4.5,0.0,NaN,0.0,0.52,29.065,29.78,7.20,17.0,7.9,11.83,Oct,42.0-87.8,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,1,0
116248,116249,CULEX SALINARIUS,T236,73.5,64.5,69.5,10.0,62.0,64.0,0.0,4.5,0.0,NaN,0.0,0.52,29.065,29.78,7.20,17.0,7.9,11.83,Oct,42.0-87.8,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,1,0
116249,116250,CULEX TERRITANS,T236,73.5,64.5,69.5,10.0,62.0,64.0,0.0,4.5,0.0,NaN,0.0,0.52,29.065,29.78,7.20,17.0,7.9,11.83,Oct,42.0-87.8,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,1,0
116250,116251,CULEX TARSALIS,T236,73.5,64.5,69.5,10.0,62.0,64.0,0.0,4.5,0.0,NaN,0.0,0.52,29.065,29.78,7.20,17.0,7.9,11.83,Oct,42.0-87.8,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,1,0
116251,116252,UNSPECIFIED CULEX,T236,73.5,64.5,69.5,10.0,62.0,64.0,0.0,4.5,0.0,NaN,0.0,0.52,29.065,29.78,7.20,17.0,7.9,11.83,Oct,42.0-87.8,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,1,0
116252,116253,CULEX ERRATICUS,T236,73.5,64.5,69.5,10.0,62.0,64.0,0.0,4.5,0.0,NaN,0.0,0.52,29.065,29.78,7.20,17.0,7.9,11.83,Oct,42.0-87.8,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,1,0
116253,116254,CULEX PIPIENS/RESTUANS,T237,73.5,64.5,69.5,10.0,62.0,64.0,0.0,4.5,0.0,NaN,0.0,0.52,29.065,29.78,7.20,17.0,7.9,11.83,Oct,41.7-87.7,0,0,1,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,1,0
116254,116255,CULEX RESTUANS,T237,73.5,64.5,69.5,10.0,62.0,64.0,0.0,4.5,0.0,NaN,0.0,0.52,29.065,29.78,7.20,17.0,7.9,11.83,Oct,41.7-87.7,0,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,1,0
116255,116256,CULEX PIPIENS,T237,73.5,64.5,69.5,10.0,62.0,64.0,0.0,4.5,0.0,NaN,0.0,0.52,29.065,29.78,7.20,17.0,7.9,11.83,Oct,41.7-87.7,0,1,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,1,0
116256,116257,CULEX SALINARIUS,T237,73.5,64.5,69.5,10.0,62.0,64.0,0.0,4.5,0.0,NaN,0.0,0.52,29.065,29.78,7.20,17.0,7.9,11.83,Oct,41.7-87.7,0,0,0,0,1,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,1,0
116257,116258,CULEX TERRITANS,T237,73.5,64.5,69.5,10.0,62.0,64.0,0.0,4.5,0.0,NaN,0.0,0.52,29.065,29.78,7.20,17.0,7.9,11.83,Oct,41.7-87.7,0,0,0,0,0,0,1,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,1,0
116258,116259,CULEX TARSALIS,T237,73.5,64.5,69.5,10.0,62.0,64.0,0.0,4.5,0.0,NaN,0.0,0.52,29.065,29.78,7.20,17.0,7.9,11.83,Oct,41.7-87.7,0,0,0,0,0,1,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,1,0
116259,116260,UNSPECIFIED CULEX,T237,73.5,64.5,69.5,10.0,62.0,64.0,0.0,4.5,0.0,NaN,0.0,0.52,29.065,29.78,7.20,17.0,7.9,11.83,Oct,41.7-87.7,0,0,0,0,0,0,0,1,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,1,0
116260,116261,CULEX ERRATICUS,T237,73.5,64.5,69.5,10.0,62.0,64.0,0.0,4.5,0.0,NaN,0.0,0.52,29.065,29.78,7.20,17.0,7.9,11.83,Oct,41.7-87.7,1,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,1,0
116261,116262,CULEX PIPIENS/RESTUANS,T238,73.5,64.5,69.5,10.0,62.0,64.0,0.0,4.5,0.0,NaN,0.0,0.52,29.065,29.78,7.20,17.0,7.9,11.83,Oct,41.8-87.7,0,0,1,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,1,0
116262,116263,CULEX RESTUANS,T238,73.5,64.5,69.5,10.0,62.0,64.0,0.0,4.5,0.0,NaN,0.0,0.52,29.065,29.78,7.20,17.0,7.9,11.83,Oct,41.8-87.7,0,0,0,1,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,1,0
116263,116264,CULEX PIPIENS,T238,73.5,64.5,69.5,10.0,62.0,64.0,0.0,4.5,0.0,NaN,0.0,0.52,29.065,29.78,7.20,17.0,7.9,11.83,Oct,41.8-87.7,0,1,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,1,0
116264,116265,CULEX SALINARIUS,T238,73.5,64.5,69.5,10.0,62.0,64.0,0.0,4.5,0.0,NaN,0.0,0.52,29.065,29.78,7.20,17.0,7.9,11.83,Oct,41.8-87.7,0,0,0,0,1,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,1,0
116265,116266,CULEX TERRITANS,T238,73.5,64.5,69.5,10.0,62.0,64.0,0.0,4.5,0.0,NaN,0.0,0.52,29.065,29.78,7.20,17.0,7.9,11.83,Oct,41.8-87.7,0,0,0,0,0,0,1,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,1,0
116266,116267,CULEX TARSALIS,T238,73.5,64.5,69.5,10.0,62.0,64.0,0.0,4.5,0.0,NaN,0.0,0.52,29.065,29.78,7.20,17.0,7.9,11.83,Oct,41.8-87.7,0,0,0,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,1,0
116267,116268,UNSPECIFIED CULEX,T238,73.5,64.5,69.5,10.0,62.0,64.0,0.0,4.5,0.0,NaN,0.0,0.52,29.065,29.78,7.20,17.0,7.9,11.83,Oct,41.8-87.7,0,0,0,0,0,0,0,1,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,1,0
116268,116269,CULEX ERRATICUS,T238,73.5,64.5,69.5,10.0,62.0,64.0,0.0,4.5,0.0,NaN,0.0,0.52,29.065,29.78,7.20,17.0,7.9,11.83,Oct,41.8-87.7,1,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,1,0
116269,116270,CULEX PIPIENS/RESTUANS,T065A,73.5,64.5,69.5,10.0,62.0,64.0,0.0,4.5,0.0,NaN,0.0,0.52,29.065,29.78,7.20,17.0,7.9,11.83,Oct,41.8-87.7,0,0,1,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,1,0
116270,116271,CULEX RESTUANS,T065A,73.5,64.5,69.5,10.0,62.0,64.0,0.0,4.5,0.0,NaN,0.0,0.52,29.065,29.78,7.20,17.0,7.9,11.83,Oct,41.8-87.7,0,0,0,1,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,1,0
116271,116272,CULEX PIPIENS,T065A,73.5,64.5,69.5,10.0,62.0,64.0,0.0,4.5,0.0,NaN,0.0,0.52,29.065,29.78,7.20,17.0,7.9,11.83,Oct,41.8-87.7,0,1,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,1,0
116272,116273,CULEX SALINARIUS,T065A,73.5,64.5,69.5,10.0,62.0,64.0,0.0,4.5,0.0,NaN,0.0,0.52,29.065,29.78,7.20,17.0,7.9,11.83,Oct,41.8-87.7,0,0,0,0,1,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,1,0
116273,116274,CULEX TERRITANS,T065A,73.5,64.5,69.5,10.0,62.0,64.0,0.0,4.5,0.0,NaN,0.0,0.52,29.065,29.78,7.20,17.0,7.9,11.83,Oct,41.8-87.7,0,0,0,0,0,0,1,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,1,0
116274,116275,CULEX TARSALIS,T065A,73.5,64.5,69.5,10.0,62.0,64.0,0.0,4.5,0.0,NaN,0.0,0.52,29.065,29.78,7.20,17.0,7.9,11.83,Oct,41.8-87.7,0,0,0,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,1,0
116275,116276,UNSPECIFIED CULEX,T065A,73.5,64.5,69.5,10.0,62.0,64.0,0.0,4.5,0.0,NaN,0.0,0.52,29.065,29.78,7.20,17.0,7.9,11.83,Oct,41.8-87.7,0,0,0,0,0,0,0,1,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,1,0
116276,116277,CULEX ERRATICUS,T065A,73.5,64.5,69.5,10.0,62.0,64.0,0.0,4.5,0.0,NaN,0.0,0.52,29.065,29.78,7.20,17.0,7.9,11.83,Oct,41.8-87.7,1,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,1,0
116277,116278,CULEX PIPIENS/RESTUANS,T094B,73.5,64.5,69.5,10.0,62.0,64.0,0.0,4.5,0.0,NaN,0.0,0.52,29.065,29.78,7.20,17.0,7.9,11.83,Oct,41.7-87.7,0,0,1,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,1,0
116278,116279,CULEX RESTUANS,T094B,73.5,64.5,69.5,10.0,62.0,64.0,0.0,4.5,0.0,NaN,0.0,0.52,29.065,29.78,7.20,17.0,7.9,11.83,Oct,41.7-87.7,0,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,1,0
116279,116280,CULEX PIPIENS,T094B,73.5,64.5,69.5,10.0,62.0,64.0,0.0,4.5,0.0,NaN,0.0,0.52,29.065,29.78,7.20,17.0,7.9,11.83,Oct,41.7-87.7,0,1,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,1,0
116280,116281,CULEX SALINARIUS,T094B,73.5,64.5,69.5,10.0,62.0,64.0,0.0,4.5,0.0,NaN,0.0,0.52,29.065,29.78,7.20,17.0,7.9,11.83,Oct,41.7-87.7,0,0,0,0,1,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,1,0
116281,116282,CULEX TERRITANS,T094B,73.5,64.5,69.5,10.0,62.0,64.0,0.0,4.5,0.0,NaN,0.0,0.52,29.065,29.78,7.20,17.0,7.9,11.83,Oct,41.7-87.7,0,0,0,0,0,0,1,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,1,0
116282,116283,CULEX TARSALIS,T094B,73.5,64.5,69.5,10.0,62.0,64.0,0.0,4.5,0.0,NaN,0.0,0.52,29.065,29.78,7.20,17.0,7.9,11.83,Oct,41.7-87.7,0,0,0,0,0,1,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,1,0
116283,116284,UNSPECIFIED CULEX,T094B,73.5,64.5,69.5,10.0,62.0,64.0,0.0,4.5,0.0,NaN,0.0,0.52,29.065,29.78,7.20,17.0,7.9,11.83,Oct,41.7-87.7,0,0,0,0,0,0,0,1,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,1,0
116284,116285,CULEX ERRATICUS,T094B,73.5,64.5,69.5,10.0,62.0,64.0,0.0,4.5,0.0,NaN,0.0,0.52,29.065,29.78,7.20,17.0,7.9,11.83,Oct,41.7-87.7,1,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,1,0
116285,116286,CULEX PIPIENS/RESTUANS,T054C,73.5,64.5,69.5,10.0,62.0,64.0,0.0,4.5,0.0,NaN,0.0,0.52,29.065,29.78,7.20,17.0,7.9,11.83,Oct,41.9-87.6,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,1,0
116286,116287,CULEX RESTUANS,T054C,73.5,64.5,69.5,10.0,62.0,64.0,0.0,4.5,0.0,NaN,0.0,0.52,29.065,29.78,7.20,17.0,7.9,11.83,Oct,41.9-87.6,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,1,0
116287,116288,CULEX PIPIENS,T054C,73.5,64.5,69.5,10.0,62.0,64.0,0.0,4.5,0.0,NaN,0.0,0.52,29.065,29.78,7.20,17.0,7.9,11.83,Oct,41.9-87.6,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,1,0
116288,116289,CULEX SALINARIUS,T054C,73.5,64.5,69.5,10.0,62.0,64.0,0.0,4.5,0.0,NaN,0.0,0.52,29.065,29.78,7.20,17.0,7.9,11.83,Oct,41.9-87.6,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,1,0
116289,116290,CULEX TERRITANS,T054C,73.5,64.5,69.5,10.0,62.0,64.0,0.0,4.5,0.0,NaN,0.0,0.52,29.065,29.78,7.20,17.0,7.9,11.83,Oct,41.9-87.6,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,1,0
116290,116291,CULEX TARSALIS,T054C,73.5,64.5,69.5,10.0,62.0,64.0,0.0,4.5,0.0,NaN,0.0,0.52,29.065,29.78,7.20,17.0,7.9,11.83,Oct,41.9-87.6,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,1,0
116291,116292,UNSPECIFIED CULEX,T054C,73.5,64.5,69.5,10.0,62.0,64.0,0.0,4.5,0.0,NaN,0.0,0.52,29.065,29.78,7.20,17.0,7.9,11.83,Oct,41.9-87.6,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,1,0
116292,116293,CULEX ERRATICUS,T054C,73.5,64.5,69.5,10.0,62.0,64.0,0.0,4.5,0.0,NaN,0.0,0.52,29.065,29.78,7.20,17.0,7.9,11.83,Oct,41.9-87.6,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,1,0

### Dropping NaNs

In [41]:
df.dropna(inplace=True, axis=1, how='all')
df

,Id,Species,Trap,Tmax,Tmin,Tavg,Depart,DewPoint,WetBulb,Heat,Cool,Depth,SnowFall,PrecipTotal,StnPressure,SeaLevel,ResultSpeed,ResultDir,AvgSpeed,Daylight,Month,Lat&Long,CULEX ERRATICUS,CULEX PIPIENS,CULEX PIPIENS/RESTUANS,CULEX RESTUANS,CULEX SALINARIUS,CULEX TARSALIS,CULEX TERRITANS,UNSPECIFIED CULEX,41.6-87.5,41.6-87.6,41.7-87.5,41.7-87.6,41.7-87.7,41.8-87.6,41.8-87.7,41.8-87.8,41.9-87.6,41.9-87.7,41.9-87.8,42.0-87.7,42.0-87.8,42.0-87.9,Aug,July,June,Oct,Sept
0,1,CULEX PIPIENS/RESTUANS,T002,86.0,63.5,75.0,7.0,55.5,64.0,0.0,10.0,0.0,0.0,0.00,29.310,29.98,9.15,18.0,10.2,15.10,June,42.0-87.8,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,1,0,0
1,2,CULEX RESTUANS,T002,86.0,63.5,75.0,7.0,55.5,64.0,0.0,10.0,0.0,0.0,0.00,29.310,29.98,9.15,18.0,10.2,15.10,June,42.0-87.8,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,1,0,0
2,3,CULEX PIPIENS,T002,86.0,63.5,75.0,7.0,55.5,64.0,0.0,10.0,0.0,0.0,0.00,29.310,29.98,9.15,18.0,10.2,15.10,June,42.0-87.8,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,1,0,0
3,4,CULEX SALINARIUS,T002,86.0,63.5,75.0,7.0,55.5,64.0,0.0,10.0,0.0,0.0,0.00,29.310,29.98,9.15,18.0,10.2,15.10,June,42.0-87.8,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,1,0,0
4,5,CULEX TERRITANS,T002,86.0,63.5,75.0,7.0,55.5,64.0,0.0,10.0,0.0,0.0,0.00,29.310,29.98,9.15,18.0,10.2,15.10,June,42.0-87.8,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,1,0,0
5,6,CULEX TARSALIS,T002,86.0,63.5,75.0,7.0,55.5,64.0,0.0,10.0,0.0,0.0,0.00,29.310,29.98,9.15,18.0,10.2,15.10,June,42.0-87.8,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,1,0,0
6,7,UNSPECIFIED CULEX,T002,86.0,63.5,75.0,7.0,55.5,64.0,0.0,10.0,0.0,0.0,0.00,29.310,29.98,9.15,18.0,10.2,15.10,June,42.0-87.8,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,1,0,0
7,8,CULEX ERRATICUS,T002,86.0,63.5,75.0,7.0,55.5,64.0,0.0,10.0,0.0,0.0,0.00,29.310,29.98,9.15,18.0,10.2,15.10,June,42.0-87.8,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,1,0,0
8,9,CULEX PIPIENS/RESTUANS,T007,86.0,63.5,75.0,7.0,55.5,64.0,0.0,10.0,0.0,0.0,0.00,29.310,29.98,9.15,18.0,10.2,15.10,June,42.0-87.8,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,1,0,0
9,10,CULEX RESTUANS,T007,86.0,63.5,75.0,7.0,55.5,64.0,0.0,10.0,0.0,0.0,0.00,29.310,29.98,9.15,18.0,10.2,15.10,June,42.0-87.8,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,1,0,0
10,11,CULEX PIPIENS,T007,86.0,63.5,75.0,7.0,55.5,64.0,0.0,10.0,0.0,0.0,0.00,29.310,29.98,9.15,18.0,10.2,15.10,June,42.0-87.8,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,1,0,0
11,12,CULEX SALINARIUS,T007,86.0,63.5,75.0,7.0,55.5,64.0,0.0,10.0,0.0,0.0,0.00,29.310,29.98,9.15,18.0,10.2,15.10,June,42.0-87.8,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,1,0,0
12,13,CULEX TERRITANS,T007,86.0,63.5,75.0,7.0,55.5,64.0,0.0,10.0,0.0,0.0,0.00,29.310,29.98,9.15,18.0,10.2,15.10,June,42.0-87.8,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,1,0,0
13,14,CULEX TARSALIS,T007,86.0,63.5,75.0,7.0,55.5,64.0,0.0,10.0,0.0,0.0,0.00,29.310,29.98,9.15,18.0,10.2,15.10,June,42.0-87.8,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,1,0,0
14,15,UNSPECIFIED CULEX,T007,86.0,63.5,75.0,7.0,55.5,64.0,0.0,10.0,0.0,0.0,0.00,29.310,29.98,9.15,18.0,10.2,15.10,June,42.0-87.8,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,1,0,0
15,16,CULEX ERRATICUS,T007,86.0,63.5,75.0,7.0,55.5,64.0,0.0,10.0,0.0,0.0,0.00,29.310,29.98,9.15,18.0,10.2,15.10,June,42.0-87.8,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,1,0,0
16,17,CULEX PIPIENS/RESTUANS,T015,86.0,63.5,75.0,7.0,55.5,64.0,0.0,10.0,0.0,0.0,0.00,29.310,29.98,9.15,18.0,10.2,15.10,June,42.0-87.8,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,1,0,0
17,18,CULEX RESTUANS,T015,86.0,63.5,75.0,7.0,55.5,64.0,0.0,10.0,0.0,0.0,0.00,29.310,29.98,9.15,18.0,10.2,15.10,June,42.0-87.8,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,1,0,0
18,19,CULEX PIPIENS,T015,86.0,63.5,75.0,7.0,55.5,64.0,0.0,10.0,0.0,0.0,0.00,29.310,29.98,9.15,18.0,10.2,15.10,June,42.0-87.8,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,1,0,0
19,20,CULEX SALINARIUS,T015,86.0,63.5,75.0,7.0,55.5,64.0,0.0,10.0,0.0,0.0,0.00,29.310,29.98,9.15,18.0,10.2,15.10,June,42.0-87.8,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,1,0,0
20,21,CULEX TERRITANS,T015,86.0,63.5,75.0,7.0,55.5,64.0,0.0,10.0,0.0,0.0,0.00,29.310,29.98,9.15,18.0,10.2,15.10,June,42.0-87.8,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,1,0,0
21,22,CULEX TARSALIS,T015,86.0,63.5,75.0,7.0,55.5,64.0,0.0,10.0,0.0,0.0,0.00,29.310,29.98,9.15,18.0,10.2,15.10,June,42.0-87.8,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,1,0,0
22,23,UNSPECIFIED CULEX,T015,86.0,63.5,75.0,7.0,55.5,64.0,0.0,10.0,0.0,0.0,0.00,29.310,29.98,9.15,18.0,10.2,15.10,June,42.0-87.8,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,1,0,0
23,24,CULEX ERRATICUS,T015,86.0,63.5,75.0,7.0,55.5,64.0,0.0,10.0,0.0,0.0,0.00,29.310,29.98,9.15,18.0,10.2,15.10,June,42.0-87.8,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,1,0,0
24,25,CULEX PIPIENS/RESTUANS,T045,86.0,63.5,75.0,7.0,55.5,64.0,0.0,10.0,0.0,0.0,0.00,29.310,29.98,9.15,18.0,10.2,15.10,June,41.9-87.7,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,1,0,0
25,26,CULEX RESTUANS,T045,86.0,63.5,75.0,7.0,55.5,64.0,0.0,10.0,0.0,0.0,0.00,29.310,29.98,9.15,18.0,10.2,15.10,June,41.9-87.7,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,1,0,0
26,27,CULEX PIPIENS,T045,86.0,63.5,75.0,7.0,55.5,64.0,0.0,10.0,0.0,0.0,0.00,29.310,29.98,9.15,18.0,10.2,15.10,June,41.9-87.7,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,1,0,0
27,28,CULEX SALINARIUS,T045,86.0,63.5,75.0,7.0,55.5,64.0,0.0,10.0,0.0,0.0,0.00,29.310,29.98,9.15,18.0,10.2,15.10,June,41.9-87.7,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,1,0,0
28,29,CULEX TERRITANS,T045,86.0,63.5,75.0,7.0,55.5,64.0,0.0,10.0,0.0,0.0,0.00,29.310,29.98,9.15,18.0,10.2,15.10,June,41.9-87.7,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,1,0,0
29,30,CULEX TARSALIS,T045,86.0,63.5,75.0,7.0,55.5,64.0,0.0,10.0,0.0,0.0,0.00,29.310,29.98,9.15,18.0,10.2,15.10,June,41.9-87.7,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,1,0,0
30,31,UNSPECIFIED CULEX,T045,86.0,63.5,75.0,7.0,55.5,64.0,0.0,10.0,0.0,0.0,0.00,29.310,29.98,9.15,18.0,10.2,15.10,June,41.9-87.7,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,1,0,0
31,32,CULEX ERRATICUS,T045,86.0,63.5,75.0,7.0,55.5,64.0,0.0,10.0,0.0,0.0,0.00,29.310,29.98,9.15,18.0,10.2,15.10,June,41.9-87.7,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,1,0,0
32,33,CULEX PIPIENS/RESTUANS,T046,86.0,63.5,75.0,7.0,55.5,64.0,0.0,10.0,0.0,0.0,0.00,29.310,29.98,9.15,18.0,10.2,15.10,June,41.9-87.7,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,1,0,0
33,34,CULEX RESTUANS,T046,86.0,63.5,75.0,7.0,55.5,64.0,0.0,10.0,0.0,0.0,0.00,29.310,29.98,9.15,18.0,10.2,15.10,June,41.9-87.7,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,1,0,0
34,35,CULEX PIPIENS,T046,86.0,63.5,75.0,7.0,55.5,64.0,0.0,10.0,0.0,0.0,0.00,29.310,29.98,9.15,18.0,10.2,15.10,June,41.9-87.7,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,1,0,0
35,36,CULEX SALINARIUS,T046,86.0,63.5,75.0,7.0,55.5,64.0,0.0,10.0,0.0,0.0,0.00,29.310,29.98,9.15,18.0,10.2,15.10,June,41.9-87.7,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,1,0,0
36,37,CULEX TERRITANS,T046,86.0,63.5,75.0,7.0,55.5,64.0,0.0,10.0,0.0,0.0,0.00,29.310,29.98,9.15,18.0,10.2,15.10,June,41.9-87.7,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,1,0,0
37,38,CULEX TARSALIS,T046,86.0,63.5,75.0,7.0,55.5,64.0,0.0,10.0,0.0,0.0,0.00,29.310,29.98,9.15,18.0,10.2,15.10,June,41.9-87.7,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,1,0,0
38,39,UNSPECIFIED CULEX,T046,86.0,63.5,75.0,7.0,55.5,64.0,0.0,10.0,0.0,0.0,0.00,29.310,29.98,9.15,18.0,10.2,15.10,June,41.9-87.7,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,1,0,0
39,40,CULEX ERRATICUS,T046,86.0,63.5,75.0,7.0,55.5,64.0,0.0,10.0,0.0,0.0,0.00,29.310,29.98,9.15,18.0,10.2,15.10,June,41.9-87.7,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,1,0,0
40,41,CULEX PIPIENS/RESTUANS,T048,86.0,63.5,75.0,7.0,55.5,64.0,0.0,10.0,0.0,0.0,0.00,29.310,29.98,9.15,18.0,10.2,15.10,June,41.9-87.7,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,1,0,0
41,42,CULEX RESTUANS,T048,86.0,63.5,75.0,7.0,55.5,64.0,0.0,10.0,0.0,0.0,0.00,29.310,29.98,9.15,18.0,10.2,15.10,June,41.9-87.7,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,1,0,0
42,43,CULEX PIPIENS,T048,86.0,63.5,75.0,7.0,55.5,64.0,0.0,10.0,0.0,0.0,0.00,29.310,29.98,9.15,18.0,10.2,15.10,June,41.9-87.7,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,1,0,0
43,44,CULEX SALINARIUS,T048,86.0,63.5,75.0,7.0,55.5,64.0,0.0,10.0,0.0,0.0,0.00,29.310,29.98,9.15,18.0,10.2,15.10,June,41.9-87.7,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,1,0,0
44,45,CULEX TERRITANS,T048,86.0,63.5,75.0,7.0,55.5,64.0,0.0,10.0,0.0,0.0,0.00,29.310,29.98,9.15,18.0,10.2,15.10,June,41.9-87.7,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,1,0,0
45,46,CULEX TARSALIS,T048,86.0,63.5,75.0,7.0,55.5,64.0,0.0,10.0,0.0,0.0,0.00,29.310,29.98,9.15,18.0,10.2,15.10,June,41.9-87.7,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,1,0,0
46,47,UNSPECIFIED CULEX,T048,86.0,63.5,75.0,7.0,55.5,64.0,0.0,10.0,0.0,0.0,0.00,29.310,29.98,9.15,18.0,10.2,15.10,June,41.9-87.7,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,1,0,0
47,48,CULEX ERRATICUS,T048,86.0,63.5,75.0,7.0,55.5,64.0,0.0,10.0,0.0,0.0,0.00,29.310,29.98,9.15,18.0,10.2,15.10,June,41.9-87.7,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,1,0,0
48,49,CULEX PIPIENS/RESTUANS,T049,86.0,63.5,75.0,7.0,55.5,64.0,0.0,10.0,0.0,0.0,0.00,29.310,29.98,9.15,18.0,10.2,15.10,June,41.9-87.7,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,1,0,0
49,50,CULEX RESTUANS,T049,86.0,63.5,75.0,7.0,55.5,64.0,0.0,10.0,0.0,0.0,0.00,29.310,29.98,9.15,18.0,10.2,15.10,June,41.9-87.7,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
116243,116244,UNSPECIFIED CULEX,T235,73.5,64.5,69.5,10.0,62.0,64.0,0.0,4.5,0.0,0.0,0.52,29.065,29.78,7.20,17.0,7.9,11.83,Oct,41.8-87.6,0,0,0,0,0,0,0,1,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,1,0
116244,116245,CULEX ERRATICUS,T235,73.5,64.5,69.5,10.0,62.0,64.0,0.0,4.5,0.0,0.0,0.52,29.065,29.78,7.20,17.0,7.9,11.83,Oct,41.8-87.6,1,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,1,0
116245,116246,CULEX PIPIENS/RESTUANS,T236,73.5,64.5,69.5,10.0,62.0,64.0,0.0,4.5,0.0,0.0,0.52,29.065,29.78,7.20,17.0,7.9,11.83,Oct,42.0-87.8,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,1,0
116246,116247,CULEX RESTUANS,T236,73.5,64.5,69.5,10.0,62.0,64.0,0.0,4.5,0.0,0.0,0.52,29.065,29.78,7.20,17.0,7.9,11.83,Oct,42.0-87.8,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,1,0
116247,116248,CULEX PIPIENS,T236,73.5,64.5,69.5,10.0,62.0,64.0,0.0,4.5,0.0,0.0,0.52,29.065,29.78,7.20,17.0,7.9,11.83,Oct,42.0-87.8,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,1,0
116248,116249,CULEX SALINARIUS,T236,73.5,64.5,69.5,10.0,62.0,64.0,0.0,4.5,0.0,0.0,0.52,29.065,29.78,7.20,17.0,7.9,11.83,Oct,42.0-87.8,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,1,0
116249,116250,CULEX TERRITANS,T236,73.5,64.5,69.5,10.0,62.0,64.0,0.0,4.5,0.0,0.0,0.52,29.065,29.78,7.20,17.0,7.9,11.83,Oct,42.0-87.8,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,1,0
116250,116251,CULEX TARSALIS,T236,73.5,64.5,69.5,10.0,62.0,64.0,0.0,4.5,0.0,0.0,0.52,29.065,29.78,7.20,17.0,7.9,11.83,Oct,42.0-87.8,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,1,0
116251,116252,UNSPECIFIED CULEX,T236,73.5,64.5,69.5,10.0,62.0,64.0,0.0,4.5,0.0,0.0,0.52,29.065,29.78,7.20,17.0,7.9,11.83,Oct,42.0-87.8,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,1,0
116252,116253,CULEX ERRATICUS,T236,73.5,64.5,69.5,10.0,62.0,64.0,0.0,4.5,0.0,0.0,0.52,29.065,29.78,7.20,17.0,7.9,11.83,Oct,42.0-87.8,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,1,0
116253,116254,CULEX PIPIENS/RESTUANS,T237,73.5,64.5,69.5,10.0,62.0,64.0,0.0,4.5,0.0,0.0,0.52,29.065,29.78,7.20,17.0,7.9,11.83,Oct,41.7-87.7,0,0,1,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,1,0
116254,116255,CULEX RESTUANS,T237,73.5,64.5,69.5,10.0,62.0,64.0,0.0,4.5,0.0,0.0,0.52,29.065,29.78,7.20,17.0,7.9,11.83,Oct,41.7-87.7,0,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,1,0
116255,116256,CULEX PIPIENS,T237,73.5,64.5,69.5,10.0,62.0,64.0,0.0,4.5,0.0,0.0,0.52,29.065,29.78,7.20,17.0,7.9,11.83,Oct,41.7-87.7,0,1,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,1,0
116256,116257,CULEX SALINARIUS,T237,73.5,64.5,69.5,10.0,62.0,64.0,0.0,4.5,0.0,0.0,0.52,29.065,29.78,7.20,17.0,7.9,11.83,Oct,41.7-87.7,0,0,0,0,1,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,1,0
116257,116258,CULEX TERRITANS,T237,73.5,64.5,69.5,10.0,62.0,64.0,0.0,4.5,0.0,0.0,0.52,29.065,29.78,7.20,17.0,7.9,11.83,Oct,41.7-87.7,0,0,0,0,0,0,1,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,1,0
116258,116259,CULEX TARSALIS,T237,73.5,64.5,69.5,10.0,62.0,64.0,0.0,4.5,0.0,0.0,0.52,29.065,29.78,7.20,17.0,7.9,11.83,Oct,41.7-87.7,0,0,0,0,0,1,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,1,0
116259,116260,UNSPECIFIED CULEX,T237,73.5,64.5,69.5,10.0,62.0,64.0,0.0,4.5,0.0,0.0,0.52,29.065,29.78,7.20,17.0,7.9,11.83,Oct,41.7-87.7,0,0,0,0,0,0,0,1,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,1,0
116260,116261,CULEX ERRATICUS,T237,73.5,64.5,69.5,10.0,62.0,64.0,0.0,4.5,0.0,0.0,0.52,29.065,29.78,7.20,17.0,7.9,11.83,Oct,41.7-87.7,1,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,1,0
116261,116262,CULEX PIPIENS/RESTUANS,T238,73.5,64.5,69.5,10.0,62.0,64.0,0.0,4.5,0.0,0.0,0.52,29.065,29.78,7.20,17.0,7.9,11.83,Oct,41.8-87.7,0,0,1,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,1,0
116262,116263,CULEX RESTUANS,T238,73.5,64.5,69.5,10.0,62.0,64.0,0.0,4.5,0.0,0.0,0.52,29.065,29.78,7.20,17.0,7.9,11.83,Oct,41.8-87.7,0,0,0,1,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,1,0
116263,116264,CULEX PIPIENS,T238,73.5,64.5,69.5,10.0,62.0,64.0,0.0,4.5,0.0,0.0,0.52,29.065,29.78,7.20,17.0,7.9,11.83,Oct,41.8-87.7,0,1,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,1,0
116264,116265,CULEX SALINARIUS,T238,73.5,64.5,69.5,10.0,62.0,64.0,0.0,4.5,0.0,0.0,0.52,29.065,29.78,7.20,17.0,7.9,11.83,Oct,41.8-87.7,0,0,0,0,1,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,1,0
116265,116266,CULEX TERRITANS,T238,73.5,64.5,69.5,10.0,62.0,64.0,0.0,4.5,0.0,0.0,0.52,29.065,29.78,7.20,17.0,7.9,11.83,Oct,41.8-87.7,0,0,0,0,0,0,1,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,1,0
116266,116267,CULEX TARSALIS,T238,73.5,64.5,69.5,10.0,62.0,64.0,0.0,4.5,0.0,0.0,0.52,29.065,29.78,7.20,17.0,7.9,11.83,Oct,41.8-87.7,0,0,0,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,1,0
116267,116268,UNSPECIFIED CULEX,T238,73.5,64.5,69.5,10.0,62.0,64.0,0.0,4.5,0.0,0.0,0.52,29.065,29.78,7.20,17.0,7.9,11.83,Oct,41.8-87.7,0,0,0,0,0,0,0,1,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,1,0
116268,116269,CULEX ERRATICUS,T238,73.5,64.5,69.5,10.0,62.0,64.0,0.0,4.5,0.0,0.0,0.52,29.065,29.78,7.20,17.0,7.9,11.83,Oct,41.8-87.7,1,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,1,0
116269,116270,CULEX PIPIENS/RESTUANS,T065A,73.5,64.5,69.5,10.0,62.0,64.0,0.0,4.5,0.0,0.0,0.52,29.065,29.78,7.20,17.0,7.9,11.83,Oct,41.8-87.7,0,0,1,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,1,0
116270,116271,CULEX RESTUANS,T065A,73.5,64.5,69.5,10.0,62.0,64.0,0.0,4.5,0.0,0.0,0.52,29.065,29.78,7.20,17.0,7.9,11.83,Oct,41.8-87.7,0,0,0,1,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,1,0
116271,116272,CULEX PIPIENS,T065A,73.5,64.5,69.5,10.0,62.0,64.0,0.0,4.5,0.0,0.0,0.52,29.065,29.78,7.20,17.0,7.9,11.83,Oct,41.8-87.7,0,1,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,1,0
116272,116273,CULEX SALINARIUS,T065A,73.5,64.5,69.5,10.0,62.0,64.0,0.0,4.5,0.0,0.0,0.52,29.065,29.78,7.20,17.0,7.9,11.83,Oct,41.8-87.7,0,0,0,0,1,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,1,0
116273,116274,CULEX TERRITANS,T065A,73.5,64.5,69.5,10.0,62.0,64.0,0.0,4.5,0.0,0.0,0.52,29.065,29.78,7.20,17.0,7.9,11.83,Oct,41.8-87.7,0,0,0,0,0,0,1,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,1,0
116274,116275,CULEX TARSALIS,T065A,73.5,64.5,69.5,10.0,62.0,64.0,0.0,4.5,0.0,0.0,0.52,29.065,29.78,7.20,17.0,7.9,11.83,Oct,41.8-87.7,0,0,0,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,1,0
116275,116276,UNSPECIFIED CULEX,T065A,73.5,64.5,69.5,10.0,62.0,64.0,0.0,4.5,0.0,0.0,0.52,29.065,29.78,7.20,17.0,7.9,11.83,Oct,41.8-87.7,0,0,0,0,0,0,0,1,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,1,0
116276,116277,CULEX ERRATICUS,T065A,73.5,64.5,69.5,10.0,62.0,64.0,0.0,4.5,0.0,0.0,0.52,29.065,29.78,7.20,17.0,7.9,11.83,Oct,41.8-87.7,1,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,1,0
116277,116278,CULEX PIPIENS/RESTUANS,T094B,73.5,64.5,69.5,10.0,62.0,64.0,0.0,4.5,0.0,0.0,0.52,29.065,29.78,7.20,17.0,7.9,11.83,Oct,41.7-87.7,0,0,1,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,1,0
116278,116279,CULEX RESTUANS,T094B,73.5,64.5,69.5,10.0,62.0,64.0,0.0,4.5,0.0,0.0,0.52,29.065,29.78,7.20,17.0,7.9,11.83,Oct,41.7-87.7,0,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,1,0
116279,116280,CULEX PIPIENS,T094B,73.5,64.5,69.5,10.0,62.0,64.0,0.0,4.5,0.0,0.0,0.52,29.065,29.78,7.20,17.0,7.9,11.83,Oct,41.7-87.7,0,1,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,1,0
116280,116281,CULEX SALINARIUS,T094B,73.5,64.5,69.5,10.0,62.0,64.0,0.0,4.5,0.0,0.0,0.52,29.065,29.78,7.20,17.0,7.9,11.83,Oct,41.7-87.7,0,0,0,0,1,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,1,0
116281,116282,CULEX TERRITANS,T094B,73.5,64.5,69.5,10.0,62.0,64.0,0.0,4.5,0.0,0.0,0.52,29.065,29.78,7.20,17.0,7.9,11.83,Oct,41.7-87.7,0,0,0,0,0,0,1,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,1,0
116282,116283,CULEX TARSALIS,T094B,73.5,64.5,69.5,10.0,62.0,64.0,0.0,4.5,0.0,0.0,0.52,29.065,29.78,7.20,17.0,7.9,11.83,Oct,41.7-87.7,0,0,0,0,0,1,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,1,0
116283,116284,UNSPECIFIED CULEX,T094B,73.5,64.5,69.5,10.0,62.0,64.0,0.0,4.5,0.0,0.0,0.52,29.065,29.78,7.20,17.0,7.9,11.83,Oct,41.7-87.7,0,0,0,0,0,0,0,1,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,1,0
116284,116285,CULEX ERRATICUS,T094B,73.5,64.5,69.5,10.0,62.0,64.0,0.0,4.5,0.0,0.0,0.52,29.065,29.78,7.20,17.0,7.9,11.83,Oct,41.7-87.7,1,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,1,0
116285,116286,CULEX PIPIENS/RESTUANS,T054C,73.5,64.5,69.5,10.0,62.0,64.0,0.0,4.5,0.0,0.0,0.52,29.065,29.78,7.20,17.0,7.9,11.83,Oct,41.9-87.6,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,1,0
116286,116287,CULEX RESTUANS,T054C,73.5,64.5,69.5,10.0,62.0,64.0,0.0,4.5,0.0,0.0,0.52,29.065,29.78,7.20,17.0,7.9,11.83,Oct,41.9-87.6,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,1,0
116287,116288,CULEX PIPIENS,T054C,73.5,64.5,69.5,10.0,62.0,64.0,0.0,4.5,0.0,0.0,0.52,29.065,29.78,7.20,17.0,7.9,11.83,Oct,41.9-87.6,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,1,0
116288,116289,CULEX SALINARIUS,T054C,73.5,64.5,69.5,10.0,62.0,64.0,0.0,4.5,0.0,0.0,0.52,29.065,29.78,7.20,17.0,7.9,11.83,Oct,41.9-87.6,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,1,0
116289,116290,CULEX TERRITANS,T054C,73.5,64.5,69.5,10.0,62.0,64.0,0.0,4.5,0.0,0.0,0.52,29.065,29.78,7.20,17.0,7.9,11.83,Oct,41.9-87.6,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,1,0
116290,116291,CULEX TARSALIS,T054C,73.5,64.5,69.5,10.0,62.0,64.0,0.0,4.5,0.0,0.0,0.52,29.065,29.78,7.20,17.0,7.9,11.83,Oct,41.9-87.6,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,1,0
116291,116292,UNSPECIFIED CULEX,T054C,73.5,64.5,69.5,10.0,62.0,64.0,0.0,4.5,0.0,0.0,0.52,29.065,29.78,7.20,17.0,7.9,11.83,Oct,41.9-87.6,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,1,0
116292,116293,CULEX ERRATICUS,T054C,73.5,64.5,69.5,10.0,62.0,64.0,0.0,4.5,0.0,0.0,0.52,29.065,29.78,7.20,17.0,7.9,11.83,Oct,41.9-87.6,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,1,0

### Dropping Columns
That we already have one-hot encoded

In [42]:
# Dropping Species, Month, and Lat&Long columns
df.drop(['Species', 'Month', 'Lat&Long'], axis=1, inplace=True)

# Also dropping Trap because it is a derivative of location which is already covered in the latitude and longitude.
df.drop('Trap', axis=1, inplace=True)

# Dropping the columns with NaN
df.dropna(axis=1, inplace=True)

## Exporting the Final DF

In [43]:
with open('test_df.pkl', 'wb') as fp:
    pickle.dump(df, fp)

### Information regarding the Final DF
Some duplicate values remain but this is due to the fact that different species would occupy the same trap.